### ISSUE TITLE
Empty cells shown when using money type

### ISSUE THREAD

**Issue by Zensey** [serge-rider/dbeaver#1500] opened 2017-03-30 08:29 UTC
There are empty cells shown and also warnings with esxceptions
when using money type for columns:

> org.jkiss.dbeaver.model.exec.DBCException: SQL Error [22003]: Bad value for type long : 4.28 руб
> 	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:55)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:106)
> 	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:195)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
> 	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
> Caused by: org.postgresql.util.PSQLException: Bad value for type long : 4.28 руб
> 	at org.postgresql.jdbc2.AbstractJdbc2ResultSet.toLong(AbstractJdbc2ResultSet.java:3087)
> 	at org.postgresql.jdbc2.AbstractJdbc2ResultSet.getLong(AbstractJdbc2ResultSet.java:2212)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getLong(JDBCResultSetImpl.java:379)
> 	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCNumberValueHandler.fetchColumnValue(JDBCNumberValueHandler.java:149)
> 	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
> 	... 5 more

version 4.0.3

**Comment by serge-rider** [comment] 2017-03-30 20:11
Duplicate of #1217.
This is limitation of PostgreSQL JDBC driver. I can't fix this.

**Closed by serge-rider** 2017-03-30 20:11 UTC
Labels: bug, duplicate
