### ISSUE TITLE
Broken editing in grid mode

### ISSUE THREAD

**Issue by Azenet** [serge-rider/dbeaver#799] opened 2016-09-30 21:29 UTC
Hi,

Since updating to 3.7.5 I've been having a range of issues with editing, including:
- when viewing a single record trying to set any column to `NULL` with the contextual menu sets the first column to `NULL`,
- sometimes after editing a cell in the grid mode (not opening the dialog or the F7 editor) and pressing enter, the cell will stop being edited and a orange background will show, but very quickly the editing "pops back up" like I had just pressed enter on the cell or started typing, which makes moving through cells using the arrow keys really difficult,
- sometimes `Ctrl-S` will not work to save result sets after setting some cells to `NULL` using `Ctrl-X`, clicking the green tick works fine though.

These might have started with 3.7.4, I haven't had the occasion to test it though.

**Comment by serge-rider** [comment] 2016-09-30 22:11
1. It is a bug, will be fixed in the next version. Thanks for report
2. I didn't get this. Can you make a gif video of this (with ScreenToGif or similar soft)? 
3. Use CTRL+ALT+S to save results changes. CTRL+S saves current editor state (e.g. SQL Editor).

**Comment by Azenet** [comment] 2016-09-30 23:43
2. Find a gif here: https://gfycat.com/WarmEqualImperialeagle all the failures are when I press the enter key, I can get out with the mouse or by pressing tab (nevermind the int overflows, this is because of the column type). Just realised that this only happens with the regular enter key, numpad enter works as intended.
3. Is this new ? I was able to save with CTRL+S before, CTRL+ALT+S works fine though, thanks.

**Comment by serge-rider** [comment] 2016-10-01 17:16
2. Weird. I can't reproduce that but I think that it can be the same issues as in #539. This bug was also fixed.
3. No, this is old. In case of SQL editor CTRL+S saves SQL script to disk and also saves changed results - I'm not sure that it is a 100% correct behavior but it is what it is for now. CTRL+ALT+S saves only results changes.

**Closed** 2016-10-03 13:05 UTC
Labels: bug, question
