### ISSUE TITLE
Hello,for Oracle data display ,the raw data type display was like messy code.

### ISSUE THREAD

**Issue by yxdxx** [serge-rider/dbeaver#1728] opened 2017-06-01 04:04 UTC
Hello,for Oracle data display ,the raw data type display was like messy code.

**Comment by serge-rider** [comment] 2017-06-01 05:13
Duplicate of #1672

**Closed by serge-rider** 2017-06-01 05:13 UTC
Labels: duplicate, question

**Comment by SeabiscuitCZX** [comment] 2018-08-31 02:40
Preferences -> Result Sets -> Editors now, then change "binary data formatter" to "Hex"

**Comment by ovidiugabriel** [comment] 2021-02-09 09:14
This changed once again on 7.3 it is in Editors > Data Editor > Binary Editors
