### ISSUE TITLE
When Change Schema Database Close Window

### ISSUE THREAD

**Issue by drodriguezZen** [serge-rider/dbeaver#1989] opened 2017-08-08 16:33 UTC
In the version 4.1.2.
When Change schema database, the window is minimized
![2017-08-08_11-32-18](https://user-images.githubusercontent.com/30839768/29083153-54e470aa-7c2d-11e7-9fa4-625fdcaeebea.png)

**Comment by serge-rider** [comment] 2017-08-08 20:36
Duplicate of #1860

**Closed by serge-rider** 2017-08-08 20:36 UTC
Labels: bug, duplicate
