### ISSUE TITLE
mariadb jdbc 1.5.6 does't work well

### ISSUE THREAD

**Issue by victor0801x** [serge-rider/dbeaver#1129] opened 2017-01-07 17:19 UTC
Hi,
I use mariadb connector/j version 1.5.6.
can not fresh databases
![2017-01-08 01-27-08](https://cloud.githubusercontent.com/assets/4534038/21743659/a2fbd3fc-d541-11e6-9b4e-24c25617af88.png)

but work well for version 1.5.5
Thanks

**Comment by infectormp** [comment] 2017-01-07 17:33
duplicate of https://github.com/serge-rider/dbeaver/issues/1121

**Closed** 2017-01-08 02:48 UTC
