### ISSUE TITLE
DBeaver 8.0: impossible to specify PostgreSQL client home

### ISSUE THREAD

**Issue by ced75** [serge-rider/dbeaver#988] opened 2016-11-21 13:49 UTC
Hi,

I'm testing the new DBeaver release 8.0 on Linux Mint 17.3.
When I try the new "Backup database" tool, I have a message on top of the "Database backup" window displaying: "Client home is not specified for connection".

So, I edit my connection. There, I suppose the client home can be defined with "Local Client" combobox.
I clic on "Browse...", then on "Add home" and I select the repository where my local PostgreSQL binaries are on my computer.
When I validate, nothing appears in the window. The fields ID, Path, Name, etc. can not be filled in.

I have the same problem in the PostgreSQL driver interface.

What am I doing wrong?

Thanks for your help.
Regards,

Cedric

**Comment by serge-rider** [comment] 2016-11-21 14:18
PostgreSQL native tools seems to be working only on Windows machines in this version (where native client home is taken from Windows registry).
Will be fixed (and improved) in 3.8.1.
Thanks for report.

**Comment by skif-sarmat** [comment] 2016-11-22 09:18
It doesn't work on Windows 10 too. The behavior is similar to the behavior in the first message.

**Comment by serge-rider** [comment] 2016-11-22 09:55
It works only if you have installed PG using windows installer (and thus you have some information in registry). Anyhow this will be fixed in the next version.

**Closed** 2016-11-22 21:06 UTC
Labels: bug

**Comment by phouverneyuff** [comment] 2017-02-20 17:56
This error continues occur in Ubuntu 16.04 on export database.

![image](https://cloud.githubusercontent.com/assets/9394724/23136683/a4502020-f77c-11e6-867a-fc6ed8d02a7c.png)

**Comment by serge-rider** [comment] 2017-02-20 18:30
You can configure PG client home in connection setting dialog. 
Click on Local client combo->Browse->Add home->`/usr/bin` (or other location where psql/pg_dump/pg_restore reside).

**Comment by Gallaecio** [comment] 2017-03-17 11:51
With DBeaver installed at /home/<username>/software/dbeaver, and executing DBeaver from a terminal to see the output, when I try to add ‘/usr/bin’ as client home nothing happens on the GUI and the terminal shows:

    Home '/usr/bin' is not supported

Is that expected?

**Comment by Gallaecio** [comment] 2017-05-28 07:56
```
$ which pg_dump
/usr/bin/pg_dump
```

**Comment by filosssof** [comment] 2017-06-01 14:39
I'm sorry for the stupid question, but where is the ... client combo in 4.0.8 version?

**Comment by serge-rider** [comment] 2017-06-01 15:35
![image](https://cloud.githubusercontent.com/assets/6398845/26687009/6005a154-46f7-11e7-8168-819915a430ca.png)

**Comment by lukaseder** [comment] 2018-02-15 09:58
Stumbling upon this, could that local client setting perhaps be pointed out in the error message to help future users find this setting? I keep forgetting this as I upgrade PostgreSQL to newer versions and delete the older versions...

**Comment by kshitijahuja** [comment] 2018-06-20 12:10
Now that I was able to find the Edit Connection, the Add Home does not allows to input text url. Instead, we have to choose a path by browsing. My Mac does not shows the hidden usr directory in that dropdown despite turning on to view the hidden files.

**Comment by brian-lamb-software-engineer** [comment] 2018-07-18 22:07
on my mac, i had to `brew install postgres`, then `which pg_dump` which was `/usr/local/bin/pg_dump`, then add this to the connection under `Connection settings` tab, `Local Client`

**Comment by lherreranetlink** [comment] 2019-11-25 16:14
@kshitijahuja  were you able to find a solution ? If so, what was it?

**Comment by kshitijahuja** [comment] 2019-11-25 16:26
> @kshitijahuja were you able to find a solution ? If so, what was it?

Nope.

**Comment by minthaka** [comment] 2019-11-29 17:03
You only need to select the home folder for the postgres tools. On Linux I had to select /usr/bin , where the installed pg_dump resides.

**Comment by adamchenwei** [comment] 2020-01-18 05:52
@brian-lamb-software-engineer  solution worked perfectly! Thanks

**Comment by mbasaglia** [comment] 2020-01-30 10:08
I'm getting similar issues, I've set the client home as `/usr/bin` but end up getting the error
```
2020-01-30 11:01:44.712 - IO error: Utility 'pg_dump' not found in client home '/usr/bin' (/usr/bin)
```

The path is correct though
```
$ which pg_dump
/usr/bin/pg_dump
$ ls -l /usr/bin/pg_dump
lrwxrwxrwx 1 root root 37 Nov 13 16:15 /usr/bin/pg_dump -> ../share/postgresql-common/pg_wrapper
```

**Comment by chris-crawford** [comment] 2020-02-24 18:35
> Now that I was able to find the Edit Connection, the Add Home does not allows to input text url. Instead, we have to choose a path by browsing. My Mac does not shows the hidden usr directory in that dropdown despite turning on to view the hidden files.

@kshitijahuja cmd+shift+g within the finder window allows for direct folder input -- I ran through this post and was successfully able to point to my bin directory for postgres install (mine was installed via Brew, so is in `uss/local/Cellar/postgresql/10.5/bin` )

**Comment by alexorbit** [comment] 2020-03-10 06:20
How to set native app on Mac:
Download Postgres.app latest release
https://postgresapp.com/downloads.html
Move to applications folder.

Setup home folder:
Connection settings => Local Client
applications folder => Postgres.app/Resources/Versions/xx/bin

**Comment by thanhdx0** [comment] 2020-04-11 03:59
I can't set client home to `/usr/bin` on ubuntu 18.04 because of permission denied error when I choose `/usr` folder in file browser. How can I do?

**Comment by ingmferrer** [comment] 2020-04-24 22:17
> I can't set client home to `/usr/bin` on ubuntu 19.04 because of permission denied error when I choose `/usr` folder in file browser.
> How can I do? I'm using DBearve-ce 7.0.2 and install DBeaver by snap.

Im having this exact problem in ubuntu 20.04, cannot set /usr/bin/ because denied permissions.

**Comment by jelnur** [comment] 2020-04-25 20:24
> Now that I was able to find the Edit Connection, the Add Home does not allows to input text url. Instead, we have to choose a path by browsing. My Mac does not shows the hidden usr directory in that dropdown despite turning on to view the hidden files.

If you installed Postgres.app the path is like this:
/Applications/Postgres.app/Contents/Versions/11/bin

**Comment by rtriveurbana** [comment] 2020-05-06 06:22
> > I can't set client home to `/usr/bin` on ubuntu 19.04 because of permission denied error when I choose `/usr` folder in file browser.
> > How can I do? I'm using DBearve-ce 7.0.2 and install DBeaver by snap.
> 
> Im having this exact problem in ubuntu 20.04, cannot set /usr/bin/ because denied permissions.

same problem

**Comment by JOSERUIZ7** [comment] 2020-05-09 23:27
The same thing happens to me, what can I do?

**Comment by thanhdx0** [comment] 2020-05-11 12:13
I moved to pgAdmin4 to use instead. It's good enough too.

**Comment by rtriveurbana** [comment] 2020-06-11 10:08
why is this closed? The problem still persist

**Comment by alykamb** [comment] 2020-06-12 12:56
For the Ubuntu permission issue: This issue is related with the Snap version of dbeaver, the one installed through Ubuntu Software. I managed to resolve the issue by uninstalling it, downloading the installer from [https://dbeaver.io/download/](https://dbeaver.io/download/) and running ```sudo dpkg -i dbeaver-ce_7.1.0_amd64.deb``` (the current version)

This version has access to the usr folder.

**Comment by bratislavml** [comment] 2020-07-07 13:41
> For the Ubuntu permission issue: This issue is related with the Snap version of dbeaver, the one installed through Ubuntu Software. I managed to resolve the issue by uninstalling it, downloading the installer from https://dbeaver.io/download/ and running `sudo dpkg -i dbeaver-ce_7.1.0_amd64.deb` (the current version)
> 
> This version has access to the usr folder.

This doesn't work for me on Ubuntu 18.04, I can access /usr/bin/ but no permissions for pg_dump.

**Comment by josemateuss** [comment] 2020-07-07 17:52
Same problem here

**Comment by pleshevskiy** [comment] 2020-07-22 07:27
I also cannot set /bin or /usr/bin as client home. I tried to make link to user home via `ls -s /usr/bin/pg_dump ~/pg_dump` and it also not work

**Comment by kseniiaguzeeva** [comment] 2020-07-22 07:50
Please create a new ticket for this issue

**Comment by embojker** [comment] 2020-08-11 11:47
I've spent an hour trying to figure out how to open a location `/usr/local/bin` in the Browse dialog window in Mac... until I found here the key combination (posted by @brian-lamb-software-engineer). 

Everyone using Mac would have to press `Command + Shift + . (dot)` to be able to see **ALL** the directories in the Browse dialog. Afterwards it is an easy pick. Just open the folder you got as the result of `which pg_dump` execution.

Cheers!

**Comment by Artofaj** [comment] 2020-09-24 07:03
> I also cannot set /bin or /usr/bin as client home. I tried to make link to user home via `ls -s /usr/bin/pg_dump ~/pg_dump` and it also not work

I can confirm this issue.

**Comment by tcampbPPU** [comment] 2020-09-26 18:52
For those on running Ubuntu and having an issue with setting the Local Client for Postgres to the '/usr/bin' through the file selector GUI I have had the same issue. I order to fix,  you cannot install the DBeaver from Snap store directly instead, install via the CLI, via the following:

Make you have Java and JDK
`$ java -version`

Add Debian repository and Install DBeaver CE
`$ wget -O - https://dbeaver.io/debs/dbeaver.gpg.key | sudo apt-key add -`
`$ echo "deb https://dbeaver.io/debs/dbeaver-ce /" | sudo tee /etc/apt/sources.list.d/dbeaver.list`

After adding the repo, update the apt list and install DBeaver CE
`$ sudo apt update`
`$ sudo apt -y install dbeaver-ce`

Hopefully this helps anyone struggling :)

**Comment by yckbilly1929** [comment] 2020-11-29 04:48
> For those on running Ubuntu and having an issue with setting the Local Client for Postgres to the '/usr/bin' through the file selector GUI I have had the same issue. I order to fix, you cannot install the DBeaver from Snap store directly instead, install via the CLI, via the following:
> 
> Make you have Java and JDK
> `$ java -version`
> 
> Add Debian repository and Install DBeaver CE
> `$ wget -O - https://dbeaver.io/debs/dbeaver.gpg.key | sudo apt-key add -`
> `$ echo "deb https://dbeaver.io/debs/dbeaver-ce /" | sudo tee /etc/apt/sources.list.d/dbeaver.list`
> 
> After adding the repo, update the apt list and install DBeaver CE
> `$ sudo apt update`
> `$ sudo apt -y install dbeaver-ce`
> 
> Hopefully this helps anyone struggling :)

can confirm that Permission denied issue exists for snap version in Ubuntu 20.10

current workaround is switching back to apt like above

**Comment by foxbit19** [comment] 2020-12-04 14:24
Unfortunately, public key is outdated.
No way to use `snap` version with `pg_dump`.
I've managed using this link: [https://dbeaver.io/debs/dbeaver-ce/](https://dbeaver.io/debs/dbeaver-ce/) to download the `.deb` package.

**Comment by OzzyTheGiant** [comment] 2020-12-08 15:44
It's definitely proven to be hard to use the snap version of DBeaver to restore. Heck, I don't even trust it to restore CSV files as it messed up my boolean data once. Use pgAdmin instead. Be sure that if you do a back up, try doing it as a TAR file, as the plain format doesn't work since pg_restore complains about it being an SQL file, forcing you to use psql, but then psql complains about null values being written as `\N`, which was basically a dead end for me. PgAdmin works better with TAR files for restores.

**Comment by LeandroRezendeCoutinho** [comment] 2021-01-12 14:27
Same problem on OpenSuse Tumbleweed.
Postgres client already installed.
![image](https://user-images.githubusercontent.com/12284806/104326909-03922080-54c9-11eb-9886-ed63b6836086.png)
![image](https://user-images.githubusercontent.com/12284806/104327012-1d336800-54c9-11eb-9813-3a25a6307084.png)

**Comment by matthaus-dev** [comment] 2021-02-01 12:40
awesome @brian-lamb-software-engineer , all that works!

**Comment by EltonCarreiro** [comment] 2021-02-09 02:58
> Unfortunately, public key is outdated.
> No way to use `snap` version with `pg_dump`.
> I've managed using this link: https://dbeaver.io/debs/dbeaver-ce/ to download the `.deb` package.

Confirming, I had permission issues when trying to specify the `pg_dump` but unfortunately snap version doesn't work, so I've installed the `.deb` package directly from the DBeaver site and it worked! :tada:

**Comment by slash851** [comment] 2021-02-18 11:25
For those using Ubuntu 20.10
I had the same problem with permissions when using DBeaver insalled from Ubuntu Software (snap version)

Solution that works for me:

1. Uninstall snap version of DBeaver from Ubuntu Software panel.
2. Go to: https://dbeaver.io/download/
3. Download DEB **Linux Debian package 64 bit (installer)** (https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb)
4. Simply double click to Install downloaded package via Ubuntu Software

![image](https://user-images.githubusercontent.com/4997107/108350107-1690c280-71e4-11eb-9709-493e7620c656.png)

With newly installed version I can modify the Home Path:

![image](https://user-images.githubusercontent.com/4997107/108350319-5fe11200-71e4-11eb-9a66-1b8d907190ba.png)

**Comment by foxbit19** [comment] 2021-02-18 11:29
Yes, I've done it exactly in that way and it works!
We have to forgot the snap edition for now.

**Comment by abinhho** [comment] 2021-11-23 09:14
This worked for me.
Mac M1 but I think Intel chip should work as well.
```
$ brew install libpq
```

Then add `/opt/homebrew/opt/libpq/bin` to `Local Client`
![image](https://user-images.githubusercontent.com/9253378/142997696-948d37e6-2bcf-4d7d-9432-5af7887d9ce2.png)

**Comment by paladini** [comment] 2022-02-23 23:38
> For those using Ubuntu 20.10 I had the same problem with permissions when using DBeaver insalled from Ubuntu Software (snap version)
> 
> Solution that works for me:
> 
> 1. Uninstall snap version of DBeaver from Ubuntu Software panel.
> 2. Go to: https://dbeaver.io/download/
> 3. Download DEB **Linux Debian package 64 bit (installer)** (https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb)
> 4. Simply double click to Install downloaded package via Ubuntu Software


I was facing the same issue in Ubuntu too and [this comment](https://github.com/dbeaver/dbeaver/issues/988#issuecomment-781276693) solved my problem. 

Also, for the step (1) you can uninstall Dbeaver (Snap Version) via Terminal:

```
sudo snap remove dbeaver-ce
```

Thanks for the tip, mate!

**Comment by krzysztofjeziorny** [comment] 2022-03-03 10:11
My experience on Debian 11 Bullseye, I had DBeaver installed with Flatpak. Trying to add a Native Client home for a Postgresql client located in `/usr/bin`, it changed this path into `/run/user/1000/doc/ff43939c/bin` and then didn't find the binaries.

I've downloaded the 'normal' zip package to extract, it works as intended with `pg_dump` and `pg_restore`.

**Comment by Destrolaric** [comment] 2022-03-03 10:16
@krzysztofjeziorny, Hi we investigated this issue sometime before, unfortunately, it's a flatpack issue. A workaround can be found here https://github.com/dbeaver/dbeaver/issues/5008

**Comment by m4ss1m0g** [comment] 2022-03-23 17:41
Anyone knows if is possible to change the **Name** field on the form (which is then displayed on the combo), on Win this field is read-only. Maybe editing a settings file...

**Comment by JuinEsp** [comment] 2022-05-31 15:23
> For the Ubuntu permission issue: This issue is related with the Snap version of dbeaver, the one installed through Ubuntu Software. I managed to resolve the issue by uninstalling it, downloading the installer from https://dbeaver.io/download/ and running `sudo dpkg -i dbeaver-ce_7.1.0_amd64.deb` (the current version)
> 
> This version has access to the usr folder.

Para mim, isso serviu muito bem.

**Comment by fawazahmed-yara** [comment] 2022-06-28 12:26
> ![image](https://cloud.githubusercontent.com/assets/6398845/26687009/6005a154-46f7-11e7-8168-819915a430ca.png)

Thanks @serge-rider for this. This worked for me to create a dump.
Had to enable hidden files (cmd + shift + .) to select libpq/bin path

Then to restore db, had to use this [cmd](https://stackoverflow.com/questions/40632228/input-file-appears-to-be-a-text-format-dump-please-use-psql):
psql -U username -p 5432 -h 10.10.10.1 -d database < db.dump

**Comment by vanduc1102** [comment] 2022-10-01 03:00
on MAC, it will be 100x faster if we can input the path directly, instead of browsing  😢

**Comment by cyberdude** [comment] 2023-05-26 11:59
> on my mac, i had to `brew install postgres`, then `which pg_dump` which was `/usr/local/bin/pg_dump`. So then add home `/usr/local/bin` to the connection under `Connection settings` tab, `Local Client`. Note when you browse for the path, you need to press `cmd` + `shift` + `.` to expose hidden files to see the `usr` directory.

It would be nice if you can add a field to input it manually. Finder explorer doesn't have all the hidden files exposed by default

**Comment by johnny68** [comment] 2023-05-29 07:51
> on my mac, i had to `brew install postgres`, then `which pg_dump` which was `/usr/local/bin/pg_dump`. So then add home `/usr/local/bin` to the connection under `Connection settings` tab, `Local Client`. Note when you browse for the path, you need to press `cmd` + `shift` + `.` to expose hidden files to see the `usr` directory.

Someone needs to add this to the official documentation for MacOS. this is the third time I forgot the keystrokes and had to find this particular comment.

**Comment by girgirius** [comment] 2023-06-02 13:34
> For those using Ubuntu 20.10 I had the same problem with permissions when using DBeaver insalled from Ubuntu Software (snap version)
> 
> Solution that works for me:
> 
> 1. Uninstall snap version of DBeaver from Ubuntu Software panel.
> 2. Go to: https://dbeaver.io/download/
> 3. Download DEB **Linux Debian package 64 bit (installer)** (https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb)
> 4. Simply double click to Install downloaded package via Ubuntu Software
> 
> ![image](https://user-images.githubusercontent.com/4997107/108350107-1690c280-71e4-11eb-9709-493e7620c656.png)
> 
> With newly installed version I can modify the Home Path:
> 
> ![image](https://user-images.githubusercontent.com/4997107/108350319-5fe11200-71e4-11eb-9a66-1b8d907190ba.png)

Worked for me! Thanks :) that was definitely permission issue

**Comment by mauriau** [comment] 2023-07-05 10:33
I'm on ubuntu, so the most simple way for me, was to uninstall dbeaver from snap and install it with the native package

**Comment by safejace** [comment] 2024-03-19 21:40
adding a comment in 2024 that the snap package is still not working!! why does canonical/ubuntu force these packages when they can't even figure out simple permission/access like this?!?

**Comment by mroeling** [comment] 2024-04-03 08:19
> adding a comment in 2024 that the snap package is still not working!! why does canonical/ubuntu force these packages when they can't even figure out simple permission/access like this?!?

Same with the Flatpak version. That also does not work. Only solution atm that does work, is using the .deb package.

**Comment by rfgonzalezweb** [comment] 2024-08-13 21:00
> For those on running Ubuntu and having an issue with setting the Local Client for Postgres to the '/usr/bin' through the file selector GUI I have had the same issue. I order to fix, you cannot install the DBeaver from Snap store directly instead, install via the CLI, via the following:
> 
> Make you have Java and JDK `$ java -version`
> 
> Add Debian repository and Install DBeaver CE `$ wget -O - https://dbeaver.io/debs/dbeaver.gpg.key | sudo apt-key add -` `$ echo "deb https://dbeaver.io/debs/dbeaver-ce /" | sudo tee /etc/apt/sources.list.d/dbeaver.list`
> 
> After adding the repo, update the apt list and install DBeaver CE `$ sudo apt update` `$ sudo apt -y install dbeaver-ce`
> 
> Hopefully this helps anyone struggling :)

This is the only thing that worked for me on Ubuntu 24.04. I went to their website and downloaded the installable instead. The app from the snap app store was not working in that sense. Thanks mate

**Comment by netosts** [comment] 2024-10-22 00:24
> For those on running Ubuntu and having an issue with setting the Local Client for Postgres to the '/usr/bin' through the file selector GUI I have had the same issue. I order to fix, you cannot install the DBeaver from Snap store directly instead, install via the CLI, via the following:
> 
> Make you have Java and JDK `$ java -version`
> 
> Add Debian repository and Install DBeaver CE `$ wget -O - https://dbeaver.io/debs/dbeaver.gpg.key | sudo apt-key add -` `$ echo "deb https://dbeaver.io/debs/dbeaver-ce /" | sudo tee /etc/apt/sources.list.d/dbeaver.list`
> 
> After adding the repo, update the apt list and install DBeaver CE `$ sudo apt update` `$ sudo apt -y install dbeaver-ce`
> 
> Hopefully this helps anyone struggling :)

This worked for me, thank you!
