### ISSUE TITLE
Select resulting in NullPointerException error

### ISSUE THREAD

**Issue by lrweck** [serge-rider/dbeaver#1815] opened 2017-06-24 06:39 UTC
I am working with JPA on some side projects and when I need to run some of the generated queries, DBeaver gives me a NullPointerException error:

![image](https://user-images.githubusercontent.com/26086198/27506471-8a570076-588e-11e7-9ff2-71279870c632.png)

**Comment by serge-rider** [comment] 2017-06-24 06:41
Please post error stacktrace from Error Log view (or log file itself: https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by lrweck** [comment] 2017-06-24 06:43
[DBeaver Log.txt](https://github.com/serge-rider/dbeaver/files/1099471/DBeaver.Log.txt)

**Comment by serge-rider** [comment] 2017-06-24 06:52
Looks like it is a bug in PostgreSQL driver (exception happens inside driver).
Could you try another driver version? You can choose it in DBeaver driver editor dialog.

And I'll add better exception handling in results metadata extraction in DBeaver.

**Comment by lrweck** [comment] 2017-06-24 07:16
Same error with the default driver suggested by DBeaver
[Log_default driver.txt](https://github.com/serge-rider/dbeaver/files/1099480/Log_default.driver.txt)

**Comment by lrweck** [comment] 2017-06-24 07:26
"select a::text from professor a" returns a text field correctly...

**Comment by serge-rider** [comment] 2017-06-24 08:08
Hmm. Could you post a table DDL - I'll try to reproduce this on my side.

**Comment by lrweck** [comment] 2017-06-24 12:09
Sorry for the dealy. Here it is:

CREATE TABLE public.professor (
	id_professor int8 NOT NULL,
	cpf varchar(255) NULL,
	nome varchar(255) NULL,
	CONSTRAINT professor_pkey PRIMARY KEY (id_professor)
)
WITH (
	OIDS=FALSE
) ;

**Comment by serge-rider** [comment] 2017-06-24 12:49
Thanks for details.
This issue will be fixed in the next version.

**Closed by serge-rider** 2017-06-24 12:49 UTC
Labels: bug, question
