### ISSUE TITLE
SELECT statement shouldn't increase uncommitted transactions count

### ISSUE THREAD

**Issue by bh4dks** [serge-rider/dbeaver#1555] opened 2017-04-10 02:44 UTC
- Version: 4.0.4
- Platform: Ubuntu 16.04
- SQL: MS SQL Server 2012
- Connection Settings:
    - Auto-commit: false
    - Isolation level: Read committed

When I execute the following SELECT statement:

```
select * from alarmruleconditions where alarmruleid = 13035
```

The Commit and Rollback buttons are enabled, and transaction count textbox changes to green with a number "1".

When hover on this textbox, I will get a popup:
```
1 total statements
1 modifying statements
1 seconds uptime
```

I think this is not correct, it is only a SELECT statement, not modifying anything. I remembered this not happens in 4.0.1 ~ 4.0.3.

![selection_023](https://cloud.githubusercontent.com/assets/20015329/24843955/eeabcec4-1d6c-11e7-841b-59cc084c9a69.png)

**Comment by serge-rider** [comment] 2017-04-10 17:50
Duplicate of #1544

**Closed by serge-rider** 2017-04-10 17:50 UTC
Labels: duplicate, question

**Comment by andyexeter** [comment] 2018-07-10 11:23
@serge-rider You marked this as a duplicate but @bh4dks said he had the isolation level set to Read Committed - shouldn't this only happen when the isolation level is set to Repeatable Read?

**Comment by serge-rider** [comment] 2018-07-10 19:38
It depends on database. Besides that even select query may cause data change (by calling some stored procedure).
Perhaps we can handle this better, by adding special handler for each particular database (e.g. MySQL)..

**Comment by andyexeter** [comment] 2018-07-20 08:50
That would be useful - it's so easy to forget to commit just when opening a table which then locks it.

**Comment by codism15** [comment] 2019-03-27 14:41
Please add something like auto-rollback for select statement. From time to time we need to look into a production database for researching an issue - we execute a select with no intention to make any change to database and we don't care about repeatable read.

**Comment by Acidcrawl** [comment] 2019-05-14 20:23
I would also like to see a feature where you can disable the transaction for select statements.  I love this tool, it's so much better than SQL Developer, but the fact that it causes a database lock when you do a select query means that I basically can't use the tool, I don't want to have auto-commit turned on and trying to remember to hit commit after ever query is an accident waiting to happen.  @serge-rider can you please reopen the issue?

**Comment by hasanunlukilinc** [comment] 2019-07-15 20:28
This bug is still continuing. When I execute simple select query, if I don't commit or rollback, other queries is waiting it. There is absolutely  table locked problems.

http://prntscr.com/ofg7z6

**Comment by haugs** [comment] 2020-01-07 11:28
The requests here seem to be resolved by: https://github.com/dbeaver/dbeaver/issues/1562

**Comment by ap-pauloafonso** [comment] 2020-03-02 19:17
It seems that this issue is back in 7.0 version

**Comment by MiqueiasVieira** [comment] 2020-03-12 14:47
This issue is back in 7.0 version

**Comment by rpalloni** [comment] 2020-03-13 09:33
This issue is back in 7.0 version

**Comment by sidneydemoraes** [comment] 2020-03-30 18:33
THe issue remains in 7.0.1.

**Comment by vinhboy** [comment] 2020-04-03 06:13
Damn, glad I stumbled on this thread... I thought I was losing my mind. I even wasted a few hours debugging a db issue because of an uncommitted SELECT.

**Comment by DISKONEKTeD** [comment] 2020-05-03 23:31
It's in 7.0.3 as well, I believe (i'm using Postgres). My uncommitted counter keeps going up after a simple select statement

**Comment by Chris-V-DK** [comment] 2020-08-27 10:46
Hi, it seems that this bug is still there!
Pleas fix it, otherwise we cannot use this wonderful tool for productive DB', because it locks pages each time we execute a  SELECT statement. 
I know that we could set manually the option 'Auto-Commit', but this is tedious and it might get forgotten, in particular when we are under high pressure due to PROD Incidents.

**Comment by Denizzi** [comment] 2020-09-12 16:23
We cannot use it in our production environment because the transaction count goes up when autocommit isn't made.

Due to this reason we are still using version 6.3.5 and can not upgrade to newer versions.


An option for transaction count in select operations would be great.

**Comment by sckiffo2** [comment] 2021-03-03 10:50
7.3.5 It is still there.

**Comment by rberko-8080** [comment] 2021-05-13 07:16
Community Version 21.0.4.202105021514. is still there :=(

**Comment by Chris-V-DK** [comment] 2021-05-17 07:54
Is there anybody taking care of this issue? 
We are back to MSSQL Server Manager until this issue is resolved...

**Comment by mzatko** [comment] 2021-05-25 08:50
still there in version Version 21.0.5

**Comment by jetzerb** [comment] 2021-11-11 14:52
Still in Version 21.2.4.202111011413

I'll add that running each of these statements, including the `rollback`, _increments_ the transaction count _in the UI_.  The _actual_ transaction count within the DB server only increments once.  This is on MSSQL.

#### Select Statement Increments Transaction Count:
An illustration of the OP's point, DBeaver increments the transaction count when I issue a `select` statement:
![image](https://user-images.githubusercontent.com/36859020/141316993-da70073a-c669-42c3-b021-bb180bd8a725.png)

#### Checking the Server for the Transaction Count
Here, I ask the server for the transaction count.  I see that the above `select` statement did indeed open a transaction, as the server returns `1`.  The UI then indicates that transaction count has been incremented.
![image](https://user-images.githubusercontent.com/36859020/141317039-9d177f3b-50a1-4285-86b2-04a9b3aa8134.png)

#### Checking the Server for the Transaction Count again
So did the transaction count _actually_ increase?  No.  When I ask the server again, it indicates that there is just one transaction.  The count in the UI is incremented again.
![image](https://user-images.githubusercontent.com/36859020/141317401-7c0db457-06c0-4228-bdc3-9492e98d94f2.png)

#### Surely Issuing a Rollback Helps?
When I issue a `rollback`, the transaction count in the UI ticks up yet again:
![image](https://user-images.githubusercontent.com/36859020/141317835-fb45ea07-17ad-47af-92e3-4b564e199e59.png)

#### Checking the Server for the Transaction Count after the Rollback
The server correctly shows a transaction count of zero, but in the UI, it looks like I'm now 5 levels deep:
![image](https://user-images.githubusercontent.com/36859020/141318099-eac2526c-3a88-47d7-9880-8420cf91b678.png)

**Comment by whatsupbros** [comment] 2022-06-29 16:20
Issue is still there in Version 22.1.1.202206261508.

It looks like DBeaver mostly covers PostgreSQL behavior. But even there issuing `COMMIT;` or `ROLLBACK;` manually doesn't finish the transaction in DBeaver. You have to click on "Commit" or "Rollback" button in the user interface to finish the transaction.

In other DBMSs, such as i.e. Oracle, the DBeaver user interface doesn't reflect the DBMS rules. I.e. DDL queries always commit current trasaction on Oracle, but DBeaver increments the transaction statement counter instead. This confuses a lot, because user may think that the DDL query is rollbackable, when it is not. And even when the user clicks on "Rollback" button in the UI, this will not do anything. So, I would say this is rather a serious issue.

Same applies to SELECT queries - in Oracle they start a new transaction only for "Serializable" isolation level, but by default (and in 99% of the cases) "Read Committed" is used, and SELECT queries should not increase transaction statements counter in the UI.

**Comment by tiglymigly** [comment] 2022-07-22 10:35
oracle connection. 
autocommit = off, isolation level: read committed.
**select 1 from dual;** counts as a modifying statement
beaver version: 22.1.2.202207091909

this is confusing, bummer! 

Does it mean that query statement locking the table in oracle?

![bummer](https://user-images.githubusercontent.com/95620050/180420714-478f70b3-4929-4b46-a50d-976e9ed9cadb.jpg)

**Comment by claudioweiler** [comment] 2024-04-24 18:00
Still on version 24.0.1.202403241413

**Comment by ip75** [comment] 2024-07-04 10:55
Still on Version 24.1.1.202406231636  for postgres

**Comment by pesmejkal** [comment] 2024-11-06 08:56
still on Version 24.2.0.202409011755
