### ISSUE TITLE
"Locale not recognized" connection error with 4.2.2

### ISSUE THREAD

**Issue by x4C6565** [serge-rider/dbeaver#2242] opened 2017-10-02 01:34 UTC
After upgrading (32-bit zip version) to 4.2.2 I get the "Locale not recognized" error when trying to connect to my Oracle databases.  This has not occurred in previous versions.  My locale setting is "en_AU".
Using ojdbc6.jar with Oracle V9, 10 and 11.

**Comment by serge-rider** [comment] 2017-10-02 05:05
Duplicate of #2243 (see workaround in comments).

**Closed by serge-rider** 2017-10-02 05:05 UTC
Labels: bug, duplicate
