### ISSUE TITLE
null pointer exception with oracle connections

### ISSUE THREAD

**Issue by gianpy** [serge-rider/dbeaver#1300] opened 2017-02-21 11:56 UTC
Hi
I've downloaded version 4.0 and imported connections from 3.8.5, mysql, postgrsql and sql lite connections perfectly works but I receive null pointer exception using or creating an oracle connection.

**Comment by serge-rider** [comment] 2017-02-21 12:06
Duplicate of #1284 
Hotfix versions will be released tomorrow.

**Closed by serge-rider** 2017-02-21 12:06 UTC
Labels: bug, duplicate
