### ISSUE TITLE
Probleman CPU usage 

### ISSUE THREAD

**Issue by grepNova** [serge-rider/dbeaver#1227] opened 2017-02-02 16:28 UTC
> 100% CPU usage dbeaver 3.8.5 (120%)
S.O: Ubuntu 16.04
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

Version 3.8.4 works fine with this configuration.

**Comment by serge-rider** [comment] 2017-02-02 16:33
That's odd (because version 3.8.5 had CPU load issues which were fixed in 3.8.5).

Check this: #1080
If turning GTK 3 off doesn't help then try this:

- Run DBeaver (so CPU load will become near 100%).
- Make a thread dump (https://github.com/serge-rider/dbeaver/wiki/Making-a-thread-dump)
- Post thread dump here

**Comment by jpastuszek** [comment] 2017-02-13 10:55
When running Hive query DBeaver CE 3.8.4 takes around 40% CPU on my MBA.
If I open a new script tab with empty text the CPU drops down to 10%.

JProfiler shows that `ScriptPositionColumn.paint` takes the most time when in the tab of the running SQL script:
```
org.jkiss.dbeaver.ui.editors.text.ScriptPositionColumn.paint(org.eclipse.swt.graphics.GC, org.eclipse.jface.text.source.ILineRange)	271663	65	4179	3400	2367	10904	1590	2.2070588235294117
```

When switched to empty tab this are the top two:
```
com.cloudera.hive.hivecommon.api.HS2ClientWrapper.GetOperationStatus(org.apache.hive.service.cli.thrift.TGetOperationStatusReq)	5004760	1	5004760	5004760	5004760	5004760	15	0.0
com.cloudera.hive.hivecommon.api.HS2ClientWrapper.recv_GetOperationStatus()	5004534	1	5004534	5004534	5004534	5004534	9	0.0
```

**Comment by serge-rider** [comment] 2017-02-13 12:15
Thanks for details. It is interesting, although I can't reproduce it on Windows, Ubuntu.
I will try to improve script position rendering function (redraw less often).

Could you check how this works in EA version (http://dbeaver.jkiss.org/files/ea/) ?

**Comment by jpastuszek** [comment] 2017-02-13 14:52
The EA version looks similar - I am getting ~8% CPU usage on empty tab vs ~38% on the same script while running the query.

**Comment by serge-rider** [comment] 2017-02-13 15:28
Thanks for info.
8% CPU usage seems to be produced by hive driver (reading something from server? just idle mode?)
I've fixed script paint function so it shouldn't consume so much CPU (unfortunately I can't test this myself). Fresh EA version uploaded.

**Closed** 2017-07-29 20:29 UTC
Labels: question
