### ISSUE TITLE
Unable to bind named parameters

### ISSUE THREAD

**Issue by grosmanal** [serge-rider/dbeaver#948] opened 2016-11-07 16:30 UTC
Since dbeaver 3.7.8, I can't use named parameters. Exemple : 
`select :test`
produces the error : 
Can not bind statement parameter
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).

For information anonymous parameters work fine.

**Comment by serge-rider** [comment] 2016-11-07 16:34
Duplicate of  #924

**Closed by serge-rider** 2016-11-07 16:34 UTC
Labels: bug, duplicate
