### ISSUE TITLE
Two Launcher icons in Ubuntu

### ISSUE THREAD

**Issue by rml1997** [serge-rider/dbeaver#1344] opened 2017-02-24 09:09 UTC
There is a second launcher icon created in ubuntu when you launch the app. The reason for this seems to be that there is an entry called swt created and the  wm_class is SWT. The other launcher entry created is called dbeaver with a class of dbeaver. The best fix would be to change the window class for the application (a property called WM_CLASS) to dbeaver. My fix was to edit the dbeaver.desktop file in /usr/share/applications/dbeaver.desktop and change StartupWMClass to SWT.

**Comment by serge-rider** [comment] 2017-02-24 10:59
Seems to be duplicate of #609.

Currently there is no WM_CLASS property in .desktop but StartupWMClass=DBeaver.
Your proposal is to set
```
WM_CLASS=DBeaver
StartupWMClass=SWT
```
Will this resolve the problem in general? Comments in #609 are a bit fuzzy.

**Comment by gloss82** [comment] 2017-03-01 10:06
@serge-rider, this is resolve the problem.

**Comment by serge-rider** [comment] 2017-03-02 10:01
Ok, let's try this in the next version.

**Closed by serge-rider** 2017-03-02 10:01 UTC
Labels: enhancement

**Comment by DemonTPx** [comment] 2017-03-03 11:39
Wouldn't other applications which use "SWT" as WM_CLASS be grouped under the DBeaver icon when it is configured like that?

I think you need to try and use `Display.setAppName("DBeaver")` when creating the SWT display. This should set to WM_CLASS to "DBeaver" and resolve this issue.

See:
https://www.eclipse.org/forums/index.php/t/245304/
http://stackoverflow.com/questions/6690704/swt-on-os-x-change-application-name

**Comment by serge-rider** [comment] 2017-03-03 13:34
You can test how it works after the fix in EA version (http://dbeaver.jkiss.org/files/ea).

Display.setAppName("DBeaver") is already called during Workbench creation.

**Comment by sandinur157** [comment] 2022-03-16 11:23
> Seems to be duplicate of #609.
> 
> Currently there is no WM_CLASS property in .desktop but StartupWMClass=DBeaver. Your proposal is to set
> 
> ```
> WM_CLASS=DBeaver
> StartupWMClass=SWT
> ```
> 
> Will this resolve the problem in general? Comments in #609 are a bit fuzzy.

This is solved my problem.

Ubuntu 21.10
DBeaver 22.0.0
