### ISSUE TITLE
getCharacterStream() currently not supported exception in MonetDB JDBC connection

### ISSUE THREAD

**Issue by palmaresk8** [serge-rider/dbeaver#2113] opened 2017-09-01 12:43 UTC
I use DBeaver as a GUI (https://dbeaver.jkiss.org/) for MonetDB (https://www.monetdb.org/). The connection to the database is done using the MonetDB JDBC driver. Problem is: no matter what I do, I cant' see the content of columns of type `TEXT` (which MonetDB translate do SQL type `CLOB`).

I know that this _could_ be a problem with the MonetDB JDBC driver, and not with DBeaver itself. But the same problem doesn't happen when I configure a JDBC connection in others GUI tools such as SQuirrel and SQL Workbench. In these tools I'm able to see CLOB contents as if they are normal strings. So I was wondering why this happens with DBeaver but not with others JDBC GUI tools.

Reproducible: Always

Steps to Reproduce:
1. Configure MonetDB connection in DBeaver using JDBC driver. Select option 'Cache CLOB values' in Preferences > Database > Result Sets > Binaries to see the content of CLOB columns
2. Create a test table with one column of type `TEXT` and insert a single string in it: `CREATE TABLE foo (name TEXT); INSERT INTO foo VALUES ('Manolo');`
3. Try to vizualize table contents. Column 'name' will show as 'NULL' (which is not). Double click the cell to watch your content and you will see one exception instead.

Actual Results:  
exception java.sql.SQLFeatureNotSupportedException: Operation getCharacterStream() currently not supported at nl.cwi.monetdb.jdbc.MonetClob.getCharacterStream.

Expected Results:  
String content

**Comment by palmaresk8** [comment] 2017-09-01 13:02
https://github.com/serge-rider/dbeaver/issues/2037

**Comment by serge-rider** [comment] 2017-09-02 06:00
I think this is duplicate of #2037
Thanks for additional details.

**Closed by serge-rider** 2017-09-02 06:00 UTC
Labels: duplicate, enhancement
