### ISSUE TITLE
Teradata: Json fields returns JDK6_SQL_Clob

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#1043] opened 2016-12-09 02:30 UTC
when selecting a json field from teradata the field is returned as a string consisting of `[JDK6_SQL_Clob]`

Additionally if I cast it as a string and try and copy and paste the results only the keys are pasted with no spaces. 

However, if I switch to the text view the text can be copy pasted as expected.

<img width="537" alt="screen shot 2016-12-08 at 6 26 17 pm" src="https://cloud.githubusercontent.com/assets/9246654/21035428/dbb6ba08-bd73-11e6-8748-caa1e5c450a9.png">

copy paste from grid view
`timestampcalloutId`
copy paste from text view
`{"timestamp": 1480909216, "calloutId": "To"}`

Same query / driver returns results as expected in another client

<img width="714" alt="aqua" src="https://cloud.githubusercontent.com/assets/9246654/21035489/588da3de-bd74-11e6-92a1-9a5efbbb0d87.png">

**Comment by serge-rider** [comment] 2016-12-13 18:30
For some reason DBeaver thinks that even_json column has complex Object data type (not CLOB).
Does this problem happens when you execute custom SQL query or when you browse table data (or both)?

**Comment by r-richmond** [comment] 2016-12-13 20:32
It happens with custom sql and when browsing table data.

**Comment by serge-rider** [comment] 2016-12-14 10:53
Please open "Metadata" panel and see what actual data type this column has.

**Comment by r-richmond** [comment] 2016-12-14 18:31
|name|label|#|table name|type|max length|precision|scale|not null|auto|
|--|--|--|--|--|--|--|--|--|--|
|event_json|event_json|8|table_name|JSON|2,000|0|0|false|false|

**Comment by serge-rider** [comment] 2016-12-18 11:32
JSON is a new data type in Teradata and it support isn't fully JDBC compliant.
I'll add a workaround in 3.8.2 but I can't test it with real Teradata server.
Please check.

**Comment by r-richmond** [comment] 2016-12-19 18:20
The Json values are now showing up as `[CLOB]` instead of `[JDK6_SQL_Clob]`

**Comment by serge-rider** [comment] 2016-12-19 18:52
What happens if you double click?

**Comment by r-richmond** [comment] 2016-12-19 20:30
If I double click it acts like a text field.

p.s. one thing I'd like to call out is that the strange behavior with copy / paste I mentioned above is fixed.

> copy paste from grid view
> timestampcalloutId
> copy paste from text view
> {"timestamp": 1480909216, "calloutId": "To"}

<img width="156" alt="screen shot 2016-12-19 at 12 26 51 pm" src="https://cloud.githubusercontent.com/assets/9246654/21328023/b33856c4-c5e6-11e6-84ac-85513cf224c3.png">

<img width="312" alt="screen shot 2016-12-19 at 12 27 41 pm" src="https://cloud.githubusercontent.com/assets/9246654/21328024/b6470626-c5e6-11e6-9ca4-c6cd586dbb18.png">

**Comment by serge-rider** [comment] 2016-12-19 20:44
Similar to #538.
Please check error log and debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files). There should be some errors.

**Comment by r-richmond** [comment] 2016-12-20 00:14
Nothing in the error log but I found this in `dbeaver-debug.log`

```
2016-12-19 16:11:21.656 - java.sql.SQLException: java.lang.AbstractMethodError: com.teradata.jdbc.jdk6.JDK6_SQL_Connection.getSchema()Ljava/lang/String;
java.sql.SQLException: java.lang.AbstractMethodError: com.teradata.jdbc.jdk6.JDK6_SQL_Connection.getSchema()Ljava/lang/String;
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.callMethod17(JDBCUtils.java:756)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.getSchema(JDBCConnectionImpl.java:511)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.determineSelectedEntity(GenericDataSource.java:753)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.refreshDefaultObject(GenericDataSource.java:713)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$12.run(SQLEditor.java:2045)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.AbstractMethodError: com.teradata.jdbc.jdk6.JDK6_SQL_Connection.getSchema()Ljava/lang/String;
	at sun.reflect.GeneratedMethodAccessor75.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.callMethod17(JDBCUtils.java:746)
	... 6 more

```

**Comment by serge-rider** [comment] 2016-12-20 10:16
Hm, something is wrong with CLOB fetching but I can't realize what exactly.

Try to enable CLOB caching (preferences->ResultSets->Binaries)

**Comment by r-richmond** [comment] 2016-12-20 18:15
So if I enable that option the json is displayed properly.

Reviewing the logs however reveals the same error regardless of wether or not the option is enabled.

```
2016-12-20 10:04:59.835 - java.sql.SQLException: java.lang.AbstractMethodError: com.teradata.jdbc.jdk6.JDK6_SQL_Connection.getSchema()Ljava/lang/String;
java.sql.SQLException: java.lang.AbstractMethodError: com.teradata.jdbc.jdk6.JDK6_SQL_Connection.getSchema()Ljava/lang/String;
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.callMethod17(JDBCUtils.java:756)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.getSchema(JDBCConnectionImpl.java:511)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.determineSelectedEntity(GenericDataSource.java:753)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.refreshDefaultObject(GenericDataSource.java:713)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$12.run(SQLEditor.java:2045)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.AbstractMethodError: com.teradata.jdbc.jdk6.JDK6_SQL_Connection.getSchema()Ljava/lang/String;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.callMethod17(JDBCUtils.java:746)
	... 6 more
```

Also what I think are unrelated errors that I noticed when viewing the log file after clearing and review. These are logged on connecting to teradata.

```
2016-12-20.09:59:59.930 TERAJDBC4 ERROR [Connect to datasource "Teradata"] TeraDriver/org.jkiss.dbeaver.registry.driver.DriverClassLoader@7f203bff The com.ncr.teradata.TeraDriver class name is deprecated. Please use the com.teradata.jdbc.TeraDriver class name instead.
2016-12-20 10:00:02.066 - Open [http://dbeaver.jkiss.org/product/version.xml]
2016-12-20 10:00:02.384 - java.sql.SQLException: java.lang.AbstractMethodError: com.teradata.jdbc.jdk6.JDK6_SQL_Connection.getSchema()Ljava/lang/String;
java.sql.SQLException: java.lang.AbstractMethodError: com.teradata.jdbc.jdk6.JDK6_SQL_Connection.getSchema()Ljava/lang/String;
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.callMethod17(JDBCUtils.java:756)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.getSchema(JDBCConnectionImpl.java:511)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.determineSelectedEntity(GenericDataSource.java:753)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:426)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:685)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:74)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.AbstractMethodError: com.teradata.jdbc.jdk6.JDK6_SQL_Connection.getSchema()Ljava/lang/String;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.callMethod17(JDBCUtils.java:746)
	... 7 more
2016-12-20 10:00:02.388 - Connected (teradata-156d77c8
```

**Comment by serge-rider** [comment] 2016-12-20 18:19
These errors (warnings actually) are not related to CLOBs.
It is quite strange that there are no CLOB related errors in debug log. I still can't reproduce this problem and thus I can't fix it..

**Comment by serge-rider** [comment] 2016-12-20 18:35
BTW maybe there is an error in results editor status message?
Like this: 
![default](https://cloud.githubusercontent.com/assets/6398845/21363102/3f8a6200-c6fc-11e6-98fb-dc32ed6dbfcd.png)

**Comment by r-richmond** [comment] 2016-12-20 20:59
No error in the status message / error log.

<img width="1317" alt="screen shot 2016-12-20 at 12 58 20 pm" src="https://cloud.githubusercontent.com/assets/9246654/21367729/17a31342-c6b4-11e6-8148-b0f3c947e876.png">

**Comment by serge-rider** [comment] 2016-12-20 23:00
This error may happen (and printed in status bar) when you view LOB in value panel.
I've added a bit more error logging. Hopefully we'll see it in the next version.

**Comment by r-richmond** [comment] 2016-12-21 00:21
I couldn't trigger an error when viewing it in the value panel.

I'll check and see if I can find an error when you release the next version.

**Comment by nasht00** [comment] 2017-01-01 14:13
I am trying to read a json value, all I see is `[CLOB]`, and at the bottom of the screen I see:

`SQL Error [20000] [XJ215]: You cannot invoke other java.sql.Clob/java.sql.Blob methods after calling the free() method or after the Blob/Clob's transaction has been committed or rolled back.`

**Comment by serge-rider** [comment] 2017-01-08 14:36
In order yo work with LOBs in Derby you need to switch into transactional mode (on the main toolbar - toggle auto-commit mode).
Another option - enable CLOB/BLOB caching in preferences.

**Comment by serge-rider** [comment] 2017-01-09 20:53
Please check how it works in 3.8.3

**Comment by r-richmond** [comment] 2017-04-27 21:32
sorry for the long delay on this. Its still showing the value without the cache option enabled.

looking in the logs i see the same error as before.

anyways since i can see the real value with the cache option enabled i guess you can close this?

```
2017-04-27 14:31:13.709 - Connect with 'Teradata' (teradata-156d77c8c3d-9484f66c7c0e459)
2017-04-27 14:31:14.608 - java.sql.SQLException: java.lang.AbstractMethodError: com.teradata.jdbc.jdk6.JDK6_SQL_Connection.getSchema()Ljava/lang/String;
java.sql.SQLException: java.lang.AbstractMethodError: com.teradata.jdbc.jdk6.JDK6_SQL_Connection.getSchema()Ljava/lang/String;
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.callMethod17(JDBCUtils.java:769)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.getSchema(JDBCConnectionImpl.java:533)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.determineSelectedEntity(GenericDataSource.java:784)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:457)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:725)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:73)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.AbstractMethodError: com.teradata.jdbc.jdk6.JDK6_SQL_Connection.getSchema()Ljava/lang/String;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.callMethod17(JDBCUtils.java:759)
	... 7 more
```

**Comment by serge-rider** [comment] 2017-04-28 06:04
Ok

**Closed by serge-rider** 2017-04-28 06:04 UTC
Labels: enhancement
