### ISSUE TITLE
PostgreSQL (4.0.0): function dblink(unknown, text) does not exist

### ISSUE THREAD

**Issue by aviskase** [serge-rider/dbeaver#1299] opened 2017-02-21 11:15 UTC
Hi. I'm using DBeaver 4.0.0 with PostgreSQL. When I trying to execute function with `dblink` I get:

SQL Error [42883]: ERROR: function dblink(unknown, text) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Where: PL/pgSQL function odsm.func_create_esia_user(character varying) line 50 at SQL statement
  org.postgresql.util.PSQLException: ERROR: function dblink(unknown, text) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Where: PL/pgSQL function odsm.func_create_esia_user(character varying) line 50 at SQL statement

In DBeaver 3.8.5 same connection with the same function works fine.

**Comment by serge-rider** [comment] 2017-02-21 11:50
Can't reproduce. Post query example.

BTW did you try to downgrade to 3.8.5 and test it?

**Comment by dizdi** [comment] 2017-02-21 20:34
Sometimes when opening DBeaver the connection on the left side in the tree is not the same as in editor. I had the same problem and checked server logs. The query, that i wanted to fire against db1 was logged at db2. After "Set Active" to db2 and back to db1 the query run successfully. This problem is new to 4.0.0

**Comment by aviskase** [comment] 2017-02-21 20:47
@dizdi's comment gave me an idea. I've reproduced the problem in 3.8.5
Our database has several schemes. By default, when I'm opening SQL Editor for a connection, it uses `orsm`. The function I'm trying to execute is in `odsm`. 
In 3.8.5 function works:
* when SQL Editor is first opened and it *looks* like `orsm` is active
* if I manually set active schema to `public`

In 4.0.0 function works only if I manually set active schema to `public`

So... I'm not even sure that  in my case this behavior in 4.0.0 is a bug. It looks like there was a problem in 3.8.5, am I right?

**Comment by dizdi** [comment] 2017-02-21 20:54
@aviskase just to clarify. I'm talking about databases not schemas. For my tests i used the full qualified name of the relation. 
I think your problem is described here: https://github.com/serge-rider/dbeaver/issues/1303

**Comment by serge-rider** [comment] 2017-02-24 12:31
Was this problem resolved in 4.0.1?

**Comment by aviskase** [comment] 2017-02-24 19:14
Yep, thanks!
So this issue is basically a duplicate of #1303

**Comment by serge-rider** [comment] 2017-02-24 19:44
Ok

**Closed by serge-rider** 2017-02-24 19:44 UTC
Labels: question
