### ISSUE TITLE
Tab key and query editor

### ISSUE THREAD

**Issue by ced75** [serge-rider/dbeaver#2340] opened 2017-10-16 07:01 UTC
Hi,

I've upgraded to DBeaver 4.2.3.
Until now, in the query editor, when typing a query with brackets, or using a template with parameters, I pressed the Tab key to move the cursor to the closing bracket or to switch to the next parameter.
But with 4.2.3 version, typing tabulation moves the focus on the result tab.
I haven't found how to desactivate this new tab shortcut to let the cursor in the query editor.

Thanks in advance for your help.

**Comment by serge-rider** [comment] 2017-10-16 07:37
Duplicate of #2339.
thanks for report anyway.
Will be fixed as hotfix of 4.2.3

**Closed by serge-rider** 2017-10-16 07:37 UTC
Labels: bug
