### ISSUE TITLE
Editing VARCHAR(MAX) column always opens read-only mode in sql server

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [serge-rider/dbeaver#1212] opened 2017-02-01 08:44 UTC
I have some tables with a `VARCHAR(MAX)` column. So when I select, I right-click the cell and select Edit cell in order to edit the value. But it always opens in read-only mode, this is a screenshot:

![image](https://cloud.githubusercontent.com/assets/14179578/22500141/e5ebe36c-e862-11e6-94d1-1ddde26f1ffa.png)

How can I edit the value?

**Comment by serge-rider** [comment] 2017-02-01 10:22
- What is your database?
- Can you edit other columns in the same table?
- What is table DDL?

BTW it is not necessary to open separate editor - you can open value view panel right in results editor.

**Comment by gabriele-ricci-kyklos** [comment] 2017-02-01 10:50
- As in the title, I'm on SQL Server
- Yes, I can
- DDL is 
```SQL 
CREATE TABLE LOL ( A NVARCHAR(MAX) )
```

Opening the panel at the right acts the same - I cannot edit the value

**Comment by serge-rider** [comment] 2017-02-01 11:26
Can't reproduce. I can add/edit column value. Table created using DDL above - and column has type varchar (String, not LOB).

What SQL Server version do you use?
What JDBC driver?

**Comment by gabriele-ricci-kyklos** [comment] 2017-02-01 11:55
I was using jTDS driver.
I can successfully edit the column using the Microsoft Driver, while I cannot using jTDS

**Comment by serge-rider** [comment] 2017-02-02 16:22
That's odd (because in my case jTDS acts exactly as Microsoft)..

**Comment by serge-rider** [comment] 2017-02-05 18:05
Closing (as we have a workaround and I can't reproduce that locally).

**Closed by serge-rider** 2017-02-05 18:05 UTC
Labels: can't reproduce, question
