### ISSUE TITLE
Oracle: index haven't columns detail name

### ISSUE THREAD

**Issue by Xrizoo** [serge-rider/dbeaver#1104] opened 2016-12-28 15:17 UTC
I have a Oracle connection to 10g 64b database throught JDBC connection, but when I try to view the columns detail name on index of a table, I have nothing.

**Comment by serge-rider** [comment] 2016-12-28 15:28
Probable duplicate of #1081 (if I understood the problem).
Please check.

**Comment by Xrizoo** [comment] 2016-12-28 15:36
Ok, seems to be the same issue.
Thanks serge-rider!!!

**Closed** 2016-12-28 16:10 UTC
Labels: question
