### ISSUE TITLE
Firebird column reposition

### ISSUE THREAD

**Issue by adamos42** [serge-rider/dbeaver#110] opened 2015-12-15 09:37 UTC
Firebird support table columns reordering, only need create an alter script with every column new position:
```
ALTER TABLE <table> ALTER <column> POSITION <new_position>;
```
Please add support to reorder columns in a table.

**Comment by serge-rider** [comment] 2015-12-15 12:53
Duplicate of #91

**Closed by serge-rider** 2015-12-15 12:53 UTC
Labels: duplicate
