### ISSUE TITLE
Active catalog/schema in toolbar

### ISSUE THREAD

**Issue by MatyCZ** [serge-rider/dbeaver#628] opened 2016-07-26 07:23 UTC
Can you explain me usage of selectbox in toolbar __Active catalog/schema__? It is only for __SQL Editor__?

# Problem
Running SQL in DBeaver is too complicated compared with HeidiSQL, Navicat or SQLyog. I must open new __SQL Editor__, select database in __Active catalog/schema__, paste query, click to another tab for activating __Execute script__ button in toolbar and finally click to this button for query execution.

# Comparison
Another database tool use current selected database in navigation tree while opening __SQL editor__ so you can only paste query and click to __Execute script__ button. You dont need to select __Datasource__ and __Catalog/Schema__.

# Proposal
- Move selectbox __Active datasource__ and __Active catalog/schema__ from toolbar to toolbar directly in __SQL Editor__ tab
- Populate these selectboxes with values from current selected item in navigation tree - __Datasource__ and __Catalog/Schema__ while opening new __SQL Editor__
- Move related buttons from toolbar to toolbar directly in __SQL Editor__

# Benefits
- You dont need to select __Catalog/Schema__ for new opened __SQL Editor__ for quick query execution
- Related selectboxes and buttons are directly in __SQL Editor__ tab in one place, not globally in every tab in DBeaver, sometimes disabled (selectboxes, buttons) or hidden (buttons)
- Easier recognizing what belongs to __SQL Editor__ (where I can select DB, how I can run Query, how I can reformat code, ...)
- Every __SQL Editor__ has own __Datasource__ or __Catalog/Schema__, you can have one __SQL Editor__ tab for one DB and another __SQL Editor__ for another DB => You dont need to change database in __Catalog/Schema__ if you need run different queries in different databases
- Current usage retained - You can run one query in many databases just with changing __Datasource__ and __Catalog/Schema__ in __SQL Editor__ tab
- There will be place for adding new buttons to toolbar (Format SQL, ...)

**Comment by serge-rider** [comment] 2016-07-26 08:00
DBeaver uses current database (in database navigator) as a context.
To execute SQL you:
- Click on database in the tree (or any node below database)
- Press `Ctrl+Enter` (this will open recent SQL editor associated with this database). Or `F3` (will let you to choose existing/create new script).
- Press `Ctrl+V` (paste SQL)
- Press `Ctrl+Enter` (execute current query)

Usually you should use "Active database" toolbar just for information. You need to switch it only if you use the same SQL script for different databases.

**Comment by MatyCZ** [comment] 2016-07-26 08:50
Thanks for your reply. So it works as I thought.

I really have a problem with this select, because I work in many databases and select is not populated while I open table in different database like any other tools. I must manually change __Active Catalog/Schema__ in toolbar or change it by clicking in context menu in navigator tree.

It is great when I need run one Query in many database at once. But it is too complicated in following example:
1. Do something in one DB
2. Open SQL editor
3. Select database in toolbar
4. Paste SQL and run query (current bug dont activate buttons in toolbar, I must reactivate current tab)
5. Close SQL editor tab
6. Go by navigation tree to another database
7. Do same changes in this DB
8. __Run another SQL query__

Finally when you need to run another query in current edited database you must after opening new SQL editor manually change current DB in toolbar. But when will be database automatically populated in step 6, in step 8 I just open SQL editor and run query - easy. I appreciate your really great work, but for executing query I prefer opening Navicat where is query execution so easy - just 2 click.

What about refactoring proposal? It will keep current use case (run one query in many database), but moving SQL editor parts from main toolbar to SQL editor toolbar will simplify query execution and it brings new comfort.

**Comment by serge-rider** [comment] 2016-07-26 10:07
I still don't understand how can I improve this.
How moving controls from main toolbar into editor toolbar will help? I don't see any difference (besides this bug in combobox which I can't reproduce for now).

If you need to run query in multiple databases you may open just one SQL editor, paste query in it and then run it multiple times by switch active database in the main toolbar. The same two clicks as I see it:
1. Change active database
2. Run active query

**Comment by MatyCZ** [comment] 2016-07-27 07:28
Read __Benefits__ from me first post, there is list of improvements.

I have problem with __Active Catalog/Schema__ in toolbar. This selectbox is not automatically changed to last database, where I do some changes or just activate some object in another DB.

I described everything in the first and second post

**Comment by MatyCZ** [comment] 2016-07-27 10:18
I thing that every user uses the application in a different way.

Yes, main request is to automatically change __Active Catalog/Schema__ to current selection in database navigation.

Thank for your patience with this request.

**Comment by majkinetor** [comment] 2016-07-28 19:19
Perhaps this is a good place to remind about potential to allow establishing a connection from the SQL file comment on the first line (or first few lines). Several other db tools work this way:

```
-- dbaaver: connection: mysql - localhost

sql goes here
...
```

This probably wont work just like that as comment symbol may be different for some databases but that is detail (even if only SQL is supported that would solve majority of cases).

Some people usually put this already at the top of SQL scripts to inform teammates which database is in question. This could be achievable via menu item, context menu or even global setting (I would set for to include this info in all sql files I use) etc. in the active editor that will by default take a active connection.

**Comment by majkinetor** [comment] 2016-07-28 19:26
This could even allow complete connection description such as:

```
-- dbeaver: Server=myServerAddress;Database=myDataBase;Trusted_Connection=True;

sql here...
```

**Comment by serge-rider** [comment] 2016-07-29 10:46
DBeaver uses internal (Eclipse-specific) files meta information storage so it don't need comments in files.
Potentially it could be a good feature (when migrating SQL from other UI tools) but this is definitely not related to active schema toolbar.

You could create another feature request for SQL comments recognition.

**Comment by majkinetor** [comment] 2016-07-29 11:56
OK, created it at https://github.com/serge-rider/dbeaver/issues/639. Thx.

**Comment by MatyCZ** [comment] 2016-08-29 10:20
It doesn`t work. I have to checked Auto-sync connection with navigator, but __Active catalog/schema__ is still empty. Click on __Link with editor__ does nothing. Navigating in tree does nothing too.

**Comment by serge-rider** [comment] 2016-08-29 11:46
Active connection changes but current schema doesn't..

**Comment by serge-rider** [comment] 2016-09-01 19:16
Will be fixed in the next version.
I can make EA if you need.

**Comment by MatyCZ** [comment] 2016-09-02 05:53
if you publish EA I will be glad.

**Comment by serge-rider** [comment] 2016-09-02 13:05
http://dbeaver.jkiss.org/files/ea/

**Comment by MatyCZ** [comment] 2016-09-02 13:20
Value __Active catalog/schema__ in Toolbar is still the same. Clicking in navigation tree does nothing.

Sync is enabled.

**Comment by serge-rider** [comment] 2016-09-02 13:43
This is how it works on my machine:
![active-schema-sync](https://cloud.githubusercontent.com/assets/6398845/18205724/3a622266-712c-11e6-9f6a-fa7af53ec81e.gif)

**Comment by MatyCZ** [comment] 2016-09-02 13:55
I know what is the difference. I expected that selectbox __Active catalog/schema__ in Toolbar will be updated all the time. Right now is updated only if __SQL editor__ is open.

Can you change it?

**Comment by serge-rider** [comment] 2016-09-02 14:01
Active schema/catalog combos doesn't make sense without SQL editor.
It doesn't affect anything else. If you need just to change active schema (for whatever reason) you just right click on schema and choose "Set Active".

**Closed** 2016-09-04 09:45 UTC
Labels: feature request

**Comment by xXLokerXx** [comment] 2018-12-11 01:16
I have a cuestion with this functionality, if i undestood well @MatyCZ wants **active catalog/schema** do what **active data source** actually do:
When you open 2 connections and open one query on each one, those querys belongs to the conection, then if you change between this queys the datasource doesn't change.

i think this change wouldn't afect how people works now, this only improve how it works to be better

PS.
if i didn't explain i'll be glad to be more especific.
