### ISSUE TITLE
Word Highlighter in SQL Editor

### ISSUE THREAD

**Issue by rythym05** [serge-rider/dbeaver#1946] opened 2017-07-31 19:22 UTC
Hello,
  It will be nice if the SQL editor could have a word highlighter feature, like in Notepad ++, where all matching words within the scope of the file is highlighted.  Example below -

![image](https://user-images.githubusercontent.com/29409893/28794342-d4b28e0a-75ea-11e7-8682-e684fd29e908.png)

**Comment by serge-rider** [comment] 2017-07-31 22:28
Duplicate of #222

**Closed by serge-rider** 2017-07-31 22:28 UTC
Labels: duplicate, feature request
