### ISSUE TITLE
dbeaver automatic version update

### ISSUE THREAD

**Issue by norbitheeviljester** [serge-rider/dbeaver#1866] opened 2017-07-11 10:11 UTC
Hi,
are there any plans to introduce an automatic version updater for dbeaver?
The speed of releases is quite amazing (thanks) but this also means that I as a user am required to very often go through the installation process which sometimes is manual depending on my environment setup (sometimes I don't have admin access and need to use dbeaver portably).

Are there any plans to make an automatic update feature?

**Comment by serge-rider** [comment] 2017-07-16 18:32
Duplicate of #1590

**Closed by serge-rider** 2017-07-16 18:32 UTC
Labels: duplicate, feature request
