### ISSUE TITLE
Mac title shows @productName@ instead of DBeaver

### ISSUE THREAD

**Issue by skeltonm** [serge-rider/dbeaver#1331] opened 2017-02-22 18:59 UTC
As seen in the screenshot below, on Mac OS Sierra 10.12.3 instead of DBeaver showing up in the title bar @productName@ shows in the title bar.  This changed when updating from version 3.x to version 4.0.  It has not changed in 4.1.  Also the menu item options such as About DBeaver and Quit DBeaver are showing @productName@ instead of DBeaver.  I was unable to get a screenshot of that menu.

![dbeaver](https://cloud.githubusercontent.com/assets/21675653/23227350/42953590-f8fe-11e6-8cd9-2dfb91352a78.jpeg)

**Comment by serge-rider** [comment] 2017-02-22 19:23
Duplicate of #1308

**Closed by serge-rider** 2017-02-22 19:23 UTC
Labels: bug, duplicate
