### ISSUE TITLE
[3.6.0] PostgreSQL - edit cell error

### ISSUE THREAD

**Issue by NullpointerForever** [serge-rider/dbeaver#211] opened 2016-02-22 08:34 UTC
On edit cell I have exception:
```
java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$ConstraintCache.fetchObjectRow(PostgreSchema.java:503)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$ConstraintCache.fetchObjectRow(PostgreSchema.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.loadObjects(JDBCCompositeCache.java:295)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getObjects(JDBCCompositeCache.java:113)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getTypedObjects(JDBCCompositeCache.java:121)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTable.getForeignKeys(PostgreTable.java:201)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTable.getAssociations(PostgreTable.java:172)
	at org.jkiss.dbeaver.model.DBUtils.getAttributeReferrers(DBUtils.java:619)
	at org.jkiss.dbeaver.ui.data.editors.ReferenceValueEditor.getEnumerableConstraint(ReferenceValueEditor.java:98)
	at org.jkiss.dbeaver.ui.data.editors.ReferenceValueEditor.isReferenceValue(ReferenceValueEditor.java:88)
	at org.jkiss.dbeaver.ui.dialogs.data.TextViewDialog.createDialogArea(TextViewDialog.java:83)
	at org.eclipse.jface.dialogs.Dialog.createContents(Dialog.java:768)
	at org.eclipse.jface.window.Window.create(Window.java:430)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1096)
	at org.eclipse.jface.window.Window.open(Window.java:792)
	at org.jkiss.dbeaver.ui.dialogs.data.ValueViewDialog.open(ValueViewDialog.java:297)
	at org.jkiss.dbeaver.ui.dialogs.data.ValueViewDialog.showValueEditor(ValueViewDialog.java:181)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$9.runInUIThread(SpreadsheetPresentation.java:777)
	at org.eclipse.ui.progress.UIJob$1.run(UIJob.java:97)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4155)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3772)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:110)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
```

**Comment by serge-rider** [comment] 2016-02-22 09:33
I fixed this particular error in code but in fact I can't reproduce this issue. Simple fix of NullPointerException won't fix actual problem. Which seems to be somewhere in metadata read - DBeaver was unable to properly extract foreign key information.
Could you check error log for any errors before that NullPointerException?
Thanks.

**Comment by NullpointerForever** [comment] 2016-02-22 09:48
I have a warning:
```
Reference table 39104 not found
An exception stack trace is not available.
```

**Comment by NullpointerForever** [comment] 2016-02-22 09:51
I have same NullpointerException, when I execute SQL, but with other message:
```
Can't extract column identifier info
```
Before this error, I have warning:
```
Reference table 38337 not found
```

**Comment by serge-rider** [comment] 2016-02-22 10:03
As I thought it was a problem in FK reading. I'll add a workaround for that.
Could you say - is there anything special about your metadata? Maybe referenced table lives in a different schema or there are some specific security policies which don't let DBeaver to find referenced table?

**Comment by NullpointerForever** [comment] 2016-02-22 10:19
My tables lives in different schemas.

**Comment by serge-rider** [comment] 2016-02-22 10:25
Ok. Thanks for report.
Fix will be in the next version (hotfix version will be released on the next week).

**Closed** 2016-02-23 12:27 UTC
Labels: bug
