### ISSUE TITLE
Oracle: FLOAT not handled correctly in view and save

### ISSUE THREAD

**Issue by palbr** [serge-rider/dbeaver#2104] opened 2017-08-30 09:03 UTC
In an Oracle database, I have a table with column defined as `FLOAT`:

```sql
CREATE TABLE mytable (
   price FLOAT,
   productname VARCHAR2(100)
);
```
(Defining no explicit precision for `price` should give me the default precision of 126.)

I add a new row with data:
* price = `321,1234567890123456789`
* productname = "1 kg Kryptonite"

**Problem 1:** After closing the inline edit with Enter, the price value changes to `321,1234436035`!
![01 after add row](https://user-images.githubusercontent.com/2083705/29863444-0823c0fa-8d70-11e7-9f93-4241648fa805.PNG)

**Problem 2:** I commit this change with the "Save" button and refresh the tables view. Now the price value changed to `321,12344`!
![02 after commit and refresh](https://user-images.githubusercontent.com/2083705/29863641-9b53ec38-8d70-11e7-8a33-28cd82e2832d.PNG)

The same process works fine using Oracle SQL Developer, so I guess it is not a problem of my database setup, but with DBeaver handling FLOATs.

**Problem 3:** Inserting a price value of `321,1234567890123456789` in Oracle SQL Developer is shown as `321,123456789` in DBeaver. But copying this value to the clipboard pastes `321.1234567890123456789` in my texteditor.
This FLOAT should be displayed as `321,123456789...` (with dots at the end), to indicate that there are more digits, which are just not shown.
If I enlarge the column width, more digits could be shown. At the moment, DBeaver sticks with 9 digits after the decimal separator whatever I change the columnwidth to.

I am using DBeaver 4.1.3, which is a great peace of software! Thanks a lot for developing it.

**Comment by palbr** [comment] 2017-08-30 09:15
Addition:
Inserting via SQL statement works fine in DBeaver:
```sql
INSERT INTO mytable(price, productname)
VALUES(444.1234567890123456789, 'Insert Test');
```
So it seems to be a GUI issue.

**Comment by serge-rider** [comment] 2017-09-02 06:05
You can configure numbers representation on Data Format preference page (you can have different representations for different connections).
![image](https://user-images.githubusercontent.com/6398845/29993371-b27f3d28-8fbd-11e7-922b-271e00d98884.png)

Unfortunately there is no single floating numbers format which will be good for everyone. Most of people don't want to see more than 3-4 fraction digits.

**Comment by palbr** [comment] 2017-09-05 06:29
Thanks for your reply! I didn't know about these display settings. But unfortunately it does not explain/solve my problem.

The default setting for "max fraction digits" is 10 in my global settings (I do not use connection specific display settings), but in the end my FLOAT value was truncated to 5 fraction digits (`321,12344`).

Explicitly setting "max fraction digits" to 20 did not change this behaviour:
Inserting `321,1234567890123456789` is changed to `321,1234436035156` on Enter and changed to `321,12344` on commit.

Please note that the fraction digits are not just truncated/rounded, but changed:

````
value   321,1234567890123456789
becomes 321,1234436035156
                ^^^^^^^^^  changed fraction digits
````

So I still guess, there is some bug in this process.

**Comment by serge-rider** [comment] 2017-09-06 06:48
Thanks for details. It is a bug in big decimal values binding.
I.e. the problem is in value edit/save (unnecessary rounding happens) but not in value representation.

Will be fixed in the next version.

**Closed by serge-rider** 2017-09-06 06:48 UTC
Labels: bug

**Comment by palbr** [comment] 2017-09-06 17:12
You are great! Thanks for the quick fixing. :)
