### ISSUE TITLE
Debian x64 Version 3.7.4 "Invalid Object name XXX" in SQL Server connections

### ISSUE THREAD

**Issue by anodynos** [serge-rider/dbeaver#729] opened 2016-09-14 10:38 UTC
Debian x64 Version 3.7.4 gives me "Invalid Object name XXX" with SQL Server connections. 

![image](https://cloud.githubusercontent.com/assets/856453/18509159/19895bb2-7a6f-11e6-9f15-94e43892e247.png)

I can connect to the DB, I can see the tables and other objects but when I open any of them I get the "Invalid Object name" error. 

All versions (incl 3.7.3) work perfectly - I  tried uninstalling/reinstalling versions, its only 3.7.4 that has any problems

**Comment by serge-rider** [comment] 2016-09-14 11:12
Duplicate of #719 (check for workaround there)

**Closed by serge-rider** 2016-09-14 11:12 UTC
Labels: duplicate
