### ISSUE TITLE
There is no mark for all occurrences of a word.

### ISSUE THREAD

**Issue by JanKo44** [serge-rider/dbeaver#1136] opened 2017-01-10 14:43 UTC
There is no mark for all occurrences of a word, like in Eclipse and a selection of a color for it. (In Eclipse: Preferences - General - Editors - Text Editors - Annotations – Occurrences)
For large queries it would be greatly useful.

**Comment by serge-rider** [comment] 2017-01-10 15:10
Duplicate of #222 
In fact Eclipse occurrences config is specific for JDT/CDT - but not for any text editor. That's why it is not so easy to do.

**Closed by serge-rider** 2017-01-10 15:10 UTC
Labels: duplicate, feature request
