### ISSUE TITLE
Editor Text Color Issue

### ISSUE THREAD

**Issue by CaptainBlasteroid** [serge-rider/dbeaver#543] opened 2016-06-16 19:44 UTC
Let's say that I have the following line in the editor:

AND FOO = 'BAR2'

But I want to change it to:

AND FOO IN ('BAR1', 'BAR2')

When I start editing that line, if I put an single quote in front of 'BAR2' so that it looks like this:

AND FOO IN (''BAR2')

All of the text below will turn red, which is expected if I have an open single quote. However, after I complete the change so that the line looks like this:

AND FOO IN ('BAR1', 'BAR2')

Despite adding the second single quote, the text below is still red which is incorrect. 

Hopefully this isn't too confusing

**Comment by serge-rider** [comment] 2016-10-05 07:44
I think this was fixed in some other bug.
Anyhow I can't reproduce this now. If you can - please reopen this issue.

**Closed by serge-rider** 2016-10-05 07:44 UTC
Labels: bug
