### ISSUE TITLE
Mac OS 10.12.6 (preview) - DBeaver fails to start

### ISSUE THREAD

**Issue by larrypl** [serge-rider/dbeaver#2016] opened 2017-08-13 18:03 UTC
Here's the error message:
```
!ENTRY org.eclipse.osgi 4 0 2017-08-13 10:59:57.221
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: Application "org.jkis
        at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:248)
        at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:29)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
```

**Comment by serge-rider** [comment] 2017-08-13 20:41
Probably a duplicate of #1740
You need to setup JDK 1.8 (http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)

**Comment by larrypl** [comment] 2017-08-13 20:50
Good - thanks!
- Larry

**Closed** 2017-08-13 21:50 UTC
Labels: question
