### ISSUE TITLE
TNSs not working propertly

### ISSUE THREAD

**Issue by marco-sanjuan** [serge-rider/dbeaver#355] opened 2016-04-11 08:40 UTC
Hi

We noted that oracle connections don't get host properly from TNSNAMES.ORA.

My case is:
1. I select oracle client
2. On TNS combo box, I select one (in this case PRE-ES)
3. I insert user and pass
4. On Test Connection, I noted that app is using TNS name as host, instead extract hostname from tsnnames.ora file.

The TNSNAMES.ORA contains;

```
PRE-ES=
	(DESCRIPTION =
		(ADDRESS_LIST =
			(ADDRESS = (PROTOCOL = TCP)(HOST = bd1.pre.es.sys.company)(PORT = 1521))
		)
		(CONNECT_DATA =
			(SERVER = DEDICATED)
			(SERVICE_NAME = devel)
		)
	)
```

And test connection tries to connect to *PRE-ES* instead of *bd1.pre.es.sys.company*:
![image](https://cloud.githubusercontent.com/assets/4165141/14421395/adf70d30-ffd1-11e5-98cf-0f244aaf6ed6.png)

The error is:
![image](https://cloud.githubusercontent.com/assets/4165141/14422033/eceeb922-ffd4-11e5-9710-b9cd6dbccb70.png)

We have to use Basic conection type to properly connect by setting host, port and database manually.

Thanks!

**Comment by serge-rider** [comment] 2016-04-11 19:09
Oracle driver has to resolve this alias into host/port (and other settings). But for some reason it doesn't do it in your environment.
In theory I can substitute all these parameters and connect using basic method. But that's now how this method should work.

Thoughts?

**Comment by marco-sanjuan** [comment] 2016-04-12 08:29
Hi

I testend several drivers but no one worked for me:

**ojdbc5.jar** and **ojdbc6.jar** result:
SQLException: could not resolve the connect identifier  "PRE-ES"
  oracle.net.ns.NetException: NetException: could not resolve the connect identifier  "PRE-ES"

**ojdbc7.jar**
SQLRecoverableException: Error de E/S: Invalid connection string format, a valid format is: "host:port:sid"

Our database is an Oracle 12.1.0.2

**Comment by serge-rider** [comment] 2016-05-13 10:26
After all I think this is some kind of client misconfiguration.
URL looks correct, TNSNAMES looks correct and it is good enough for DBeaver but for some reason Oracle driver doesn't see it.
I have no clues how to fix this..

**Comment by serge-rider** [comment] 2016-05-13 18:14
http://dbeaver.jkiss.org/forum/posting.php?mode=reply&f=2&t=3026

**Comment by serge-rider** [comment] 2016-05-13 18:50
I changed URL format for TNS connections. If anybody can test it - please do.
I still can't reproduce the problem.

**Comment by marco-sanjuan** [comment] 2016-05-13 19:06
How can I test it? Did you released a new version to download?

**Comment by serge-rider** [comment] 2016-05-13 19:42
http://dbeaver.jkiss.org/files/ea/

**Comment by marco-sanjuan** [comment] 2016-05-13 20:51
Sorry, id didn't work, I re-tested all drivers and combinations with new version but result are same.
Should i do anything special to test new version?

**Comment by serge-rider** [comment] 2016-05-13 20:56
Check the URL (you can see it in Properties view).
It should look like `jdbc:oracle:thin:@(DESCRIPTION = ... )`

**Comment by marco-sanjuan** [comment] 2016-05-13 21:16
I see 
![image](https://cloud.githubusercontent.com/assets/4165141/15262079/757ef80c-1960-11e6-9a33-3bf67a0b16f8.png)
for this config:
![image](https://cloud.githubusercontent.com/assets/4165141/15262095/8b4ce626-1960-11e6-8392-ee961aa4a6b7.png)
And this driver config:
![image](https://cloud.githubusercontent.com/assets/4165141/15262120/a3057850-1960-11e6-93e7-93bb933b5fb8.png)

The exception is:
Error de E/S: could not resolve the connect identifier  "PRE-ES"
 oracle.net.ns.NetException: could not resolve the connect identifier  "PRE-ES"

**Comment by serge-rider** [comment] 2016-05-13 21:22
Try to change any connection setting, it will re-generate the URL.

**Comment by marco-sanjuan** [comment] 2016-05-13 21:30
Sorry, same result. Also created new connection and only have changes when don't select any oracle client (url generated is jdbc:oracle:thin@ instead of jdbc:oracle:thin@PRE-ES

I guess that you couldn,t reproduce this issue, right? In your machine with same TNS the generated url is correct?

**Comment by serge-rider** [comment] 2016-05-13 21:34
Umm.
Looks like DBeaver can't find correct TNSNAMES.ora file. This explains all problems from the very beginning.
I see that Oracle client home was set to `d:\oracle`. Where is your TNSNAMES.ora file located?

**Comment by marco-sanjuan** [comment] 2016-05-13 21:40
Exactly at that location:
d:\oracle\tnsnames.ora

But if DBeaver is listing tns entries, it would be because is locating tnsnames.ora,right?

**Comment by serge-rider** [comment] 2016-05-13 21:48
Nope, DBeaver loads file `%ORA_HOME%/network/admin/tnsnames.ora`. Or, if TNS_ADMIN system variable is set, then from `%TNS_ADMIN%/tnsnames.ora`.
Check it, maybe it is also exist?

**Comment by serge-rider** [comment] 2016-05-13 21:49
In any case I'll fix tnsnames.ora search algorithm.

**Comment by marco-sanjuan** [comment] 2016-05-13 21:49
I use TNS_ADMIN, that point to d:\oracle

**Comment by serge-rider** [comment] 2016-05-13 22:06
Well, I did reproduce this problem, thanks for assistance.
Will be fixed in the next version.

**Comment by marco-sanjuan** [comment] 2016-05-13 22:21
Thanks!! 
If you need to test it please tell me.

**Comment by serge-rider** [comment] 2016-05-13 22:30
You could try EA version again (just built it).
Its not yet well-tested but this issue might be fixed.

**Comment by marco-sanjuan** [comment] 2016-05-13 22:34
It worked!

Great job Serge, thanks!

**Comment by serge-rider** [comment] 2016-05-13 22:40
:+1:

**Closed** 2016-05-16 17:53 UTC
Labels: bug
