### ISSUE TITLE
SQL script output in a single tab

### ISSUE THREAD

**Issue by jheadley** [serge-rider/dbeaver#2643] opened 2017-12-14 20:11 UTC
I have a script of several select statements.  If I click Execute SQL Script or if I click Execute Script's statements in separate results tabs, I get the same thing. A result tab for each query in the script. It would be nice to be able to just get all the output in a single tab in text.  Like:

Results for Query 1                    |
-------------------------------|
999                                            |

Results for Query 2                   |
-------------------------------|
9999                                          |

Results for Query 3                   |
-------------------------------|
99999                                       |

**Comment by serge-rider** [comment] 2017-12-15 18:41
Duplicate of #667
Hopefully we'll find time for this till 5.0.

**Closed by serge-rider** 2017-12-15 18:41 UTC
Labels: duplicate, feature request
