### ISSUE TITLE
Opening and then executing a script file encoded with UTF-8 BOM gives an error

### ISSUE THREAD

**Issue by antonwierenga** [serge-rider/dbeaver#2258] opened 2017-10-03 13:29 UTC
<img width="648" alt="screen shot 2017-10-03 at 15 28 22" src="https://user-images.githubusercontent.com/14827290/31127527-832eee6a-a84f-11e7-8614-6988579240e7.png">

I am using OSX 10.12.6, DBeaver 4.2.2. Attached the script file.

[test.zip](https://github.com/serge-rider/dbeaver/files/1352423/test.zip)

**Comment by nitram509** [comment] 2017-10-05 21:16
Hi, 

I've investigated a bit regarding this topic.
It seems to me, the root cause of this issue is kind of known ;-)
See https://www.eclipse.org/forums/index.php/t/157485/ 
And https://bugs.eclipse.org/bugs/show_bug.cgi?id=160614

My proposal is to follow advice and use the extension point org.eclipse.core.contenttype.contentTypes and make org.eclipse.core.runtime.text as base-type for 'sql' extensions. This should do the job.

**Comment by antonwierenga** [comment] 2017-10-06 06:00
Thanks, that seems to work. Shouldn't this be the default extension point for sql files in DBeaver?

**Comment by serge-rider** [comment] 2017-10-06 06:11
@nitram509 thanks for the link. 
Sql extension was already bound to `org.eclipse.core.runtime.text` but SQL content type describer was badly formed. Now fixed - BOM files are opening just fine.
See fix in 4.2.3.

**Closed** 2017-10-06 06:11 UTC
Labels: bug
