### ISSUE TITLE
Add new row doesn't work with empty table

### ISSUE THREAD

**Issue by zejji** [serge-rider/dbeaver#1796] opened 2017-06-20 15:50 UTC
When trying to add a new row to an empty table with the '+' button, nothing happens (see attached image). However, if at least one row already exists, this feature works without problems.

I am using DBeaver 4.0.8 on Windows 10 x64 with MariaDB 10.2.

![untitled](https://user-images.githubusercontent.com/3524191/27342687-c53af3ae-55d8-11e7-96e8-bf29147cc744.png)

**Comment by serge-rider** [comment] 2017-06-20 18:29
Duplicate of #1722

**Closed by serge-rider** 2017-06-20 18:29 UTC
Labels: bug, duplicate
