### ISSUE TITLE
NPE on connecting to an Oracle db

### ISSUE THREAD

**Issue by Spoilt** [serge-rider/dbeaver#1287] opened 2017-02-20 14:16 UTC
Hi, after upgrading from 3.8.4 (I think ?) to 4.0.0, I can't connect anymore on my DBs.

```
Internal error connecting to NVR - DEV
  java.lang.NullPointerException: 
``` 
No other lines. Did I miss a log file somewhere ?

I tried to uninstall completly then reinstall, no change. However, my connections are still present on the Database Navigator, so I think there's some conf file somewhere.

I'm on a Windows 7 64bits. I took the installer + jre.

It works fine with 3.8.5 (which I'll use for now ;) )

**Comment by serge-rider** [comment] 2017-02-20 14:20
Duplicate of #1284

**Closed by serge-rider** 2017-02-20 14:20 UTC
Labels: bug, duplicate
