### ISSUE TITLE
New SQL Editor command doesn't fire

### ISSUE THREAD

**Issue by conceptrat** [serge-rider/dbeaver#507] opened 2016-06-02 04:18 UTC
Not sure if this is the intended action and I'm sure that this used to work from the current SQL Editor window.  However in the latest two versions v3.6.8 and v3.6.9, both enterprise and community edition, the "New SQL Editor" command only works when you are highlighting a connection in the "Connections" group (you get a popup asking to select a connection in this case) in the "Project Explorer".

I can see in the Keys area of the preferences that the "New SQL Editor" category is "Connection" and so I can understand that it's locked to the "Connection" context which probably means that it'll only trigger when in the "Connections" group.

When I'm in the current SQL Editor window, then clicking the New SQL Editor button or using the shortcut key that I've assigned, in this case Ctrl+Alt+L, I see in the bottom right of the status bar "Building workspace".  Again I'm sure this used to work and bring up a new SQL editor window.

**Comment by serge-rider** [comment] 2016-06-02 07:16
Can't reproduce. In my environment "New SQL Editor" always opens new editor, no matter what view/editor is currently active.
Are you using standalone or Eclipse plugin version? (btw in Eclipse ctrl+alt+l may be bound to a very different command).

You could try these tricks:
- Execute "Reset Perspective" command (in main menu Window)
- Try to run DBeaver with parameter "-data <path to some local folder>". It will create new workspace. Check how "New SQL Editor" works in it.

**Comment by carlosjrcabello** [comment] 2016-06-06 14:39
Hi there,

Previous versions this button comes with "Ctrl + Alt + L" as shortcut. The action of click --> open seems normally here.

**Comment by carlosjrcabello** [comment] 2016-06-06 14:41
@serge-rider , could you adjust resource result, look the size of icons:

![image](https://cloud.githubusercontent.com/assets/637767/15825793/85188a02-2bdb-11e6-83f2-f27714d1493e.png)

@conceptrat, if you trigger "Ctrl + Alt + L", you can use it normally.

**Comment by serge-rider** [comment] 2016-06-06 14:45
Yep. I had to remove this shortcut because it conflicts with standard Eclipse shortcut and it made plugin version inconsistent.
And this is not very frequent action so I think it may remain without shortcut at all. For most users at least.

**Comment by carlosjrcabello** [comment] 2016-06-06 14:50
I'm with you. Final users can set their custom shortcuts using keys control. 

For this issue, just for appearance reasons, fix those giant icons, keep them on original sizes or doesn't show icons.

**Comment by conceptrat** [comment] 2016-06-07 23:04
Howdy,

Sorry for delay in responding.  Work has been keeping me pretty busy.

I'm using the standalone version of Dbeaver.  I tried "Reset Perspective" but that didn't seem to change anything.  So I ran Dbeaver with the "-data" option to create a new workspace.  This seems to have fixed the problem I was having.  So it appears that my workspace may have got out of sync with the standard Dbeaver setup.

Of note is that I have modified some of the ".project" files directly due to the virtual folder linking not working correctly.  This may have contributed to my problems although I've not verified this by recreating every step.

I completely understand your reasoning behind removing the "Ctrl+Alt+L" shortcut due to potential conflict.  As a user if I want to override this then it should be my responsibility, not yours, and the consequences mine to deal with.  The interface for keyboard shortcuts does indicate if there's a conflict when you enter a shortcut combination that already exists so it should be obvious.

Thanks for checking things @serge-rider

**Comment by conceptrat** [comment] 2016-06-07 23:06
@carlosjrcabello I couldn't see those large icons you're getting but that's a seperate issue perhaps?

**Comment by carlosjrcabello** [comment] 2016-06-07 23:25
Hi @conceptrat ,

No problem, I just thought that it would change some, can add a little fix about icons.

:)

**Comment by serge-rider** [comment] 2016-06-08 10:04
Ok, so I'm closing it.

**Closed by serge-rider** 2016-06-08 10:04 UTC
Labels: can't reproduce, question
