### ISSUE TITLE
DBeaver on Ubuntu 16.04 inside VBox guest - very high cpu

### ISSUE THREAD

**Issue by anesthesi** [serge-rider/dbeaver#1388] opened 2017-03-03 09:50 UTC
Hello,
I'm using DBeaver on Ubuntu 16.04 that runs as a guest on VirtualBox under Windows 10.
Never had troubles with this configuration until some time ago, when an Ubuntu internal desktop process called "Compiz" started using extremely high CPU and caused my (guest) computer to hang frequently.
Reinstalling Ubuntu, tweaking Compiz, playing with the hardware acceleration settings - nothing helped.
Until today, when I found who's causing this Compiz process to go mad :)
It seems that DBeaver (no matter which version) causes the thing.
Attached is a video capture of the thing.
Any tips?
[out-2.ogv.zip](https://github.com/serge-rider/dbeaver/files/816394/out-2.ogv.zip)

**Comment by serge-rider** [comment] 2017-03-03 09:57
Compiz is your Window manager.

Check this: https://ubuntuforums.org/showthread.php?t=2271938
Actually there are pretty many topics on Stackoverflow about Compiz high CPU usage.

**Comment by anesthesi** [comment] 2017-03-03 10:28
Hello,
Naturally I didn't suspect that the problem is connected to DBeaver. For the last 2 weeks, I googled and tried to understand this high cpu issue. As I wrote - I played with the acceleration, tweaked, etc, all the recommendations I received from variety of articles.
Today, after another forced reboot I decided to see if I can isolate the problem.
As I'm writing to you now, the following application are running on my computer:
Terminal, FireFox, System Monitor, Google Chrome, WebStorm, Rider.
Compiz CPU: between 3 and 9%.
Now executing DBeaver.
Waiting a minutes of NOOP.
Compiz: CPU between 42% and 60%!  (and it's not even in the foreground!)
Now turning it off and waiting a minute.
Compiz: CPU: Less than 10%.

**Comment by serge-rider** [comment] 2017-03-03 11:13
Most likely the problem is in SWT+Compiz.
Try to run `export SWT_GTK3=0` befor DBeaver run.
https://bugs.launchpad.net/ubuntu/+source/java-common/+bug/1552764

**Comment by anesthesi** [comment] 2017-03-03 12:32
This seems to solve it, thank you.

**Comment by serge-rider** [comment] 2017-03-03 13:36
Actually this problem had to be fixed in Eclipse 4.6 (and DBeaver 4.0).
And it was fixed partially. 
Unfortunately I can't fix it because it is produced by SWT (Eclipse).

**Closed by serge-rider** 2017-03-03 13:36 UTC
Labels: question
