### ISSUE TITLE
java.lang.NullPointerException thrown on "Export to CSV"

### ISSUE THREAD

**Issue by aarondd** [serge-rider/dbeaver#1592] opened 2017-04-21 00:23 UTC
Hi,

Using DBeaver 4.0.5 EE on a Vertica cluster. I am trying to export query results directly to CSV, but DBeaver throws a NullPointerException unless I first stream them into the results window.

Steps to reproduce:
1. Right click a statement in the SQL Editor
2. Select Execute > Export From Query
3. Choose CSV, default options
4. Click Finish; exception thrown.

Stack trace:
```
java.lang.NullPointerException
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:772)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1820)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:120)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.transferData(DataTransferJob.java:102)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.run(DataTransferJob.java:65)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

Environment:
```
eclipse.buildId=unknown
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
```

This also occurs on 4.0.5 CE. 

PS: this is a super amazing product and I love using it!

**Comment by serge-rider** [comment] 2017-04-22 07:32
Can't reproduce.
This stacktrace is a bit outdated and I can't figure out what happens.
Could you install EA version from http://dbeaver.jkiss.org/files/ea/ and try to run export one more time?

**Comment by serge-rider** [comment] 2017-05-01 20:11
Probably fixed in 4.0.6

**Comment by aarondd** [comment] 2017-05-01 22:55
Hi,

Thanks for investigating this issue. I tried it using EA last week, and today I tried CE 4.0.6 and the issue was the same.

The stacktrace hasn't changed. I also noticed that on loading DBeaver I get the following error:
`Unable to retrieve the bundle from the URI: bundleclass://org.eclipse.ui.ide.application/org.eclipse.ui.internal.ide.application.addons.ModelCleanupAddon`

This occurs on all installations where I run the error (EA 4.0.5, CE 4.0.5, CE 4.0.6). However, I am running EE 3.8.5 and there is no such error, and I can also export to CSV just fine.

Thanks a lot.

**Comment by serge-rider** [comment] 2017-05-02 05:48
Stacktrace can't be the same. There were many changes in SQLQueryJob class recently. Please repost error stacktrace.

**Comment by SantiPS** [comment] 2017-05-08 10:21
I have the same problem. 

For export data I have to execute the query first and I can export after the execution.

Allways export the last execute query.

I back to the old version 3.8.4 and works well again but witch new version I have this bug.

**Comment by serge-rider** [comment] 2017-05-08 10:47
Once again: please post error stacktrace or error/debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by serge-rider** [comment] 2017-05-13 11:10
I've reproduced that.
Happens if no queries were executed in current editor before data export.

**Closed** 2017-05-13 11:22 UTC
Labels: bug

**Comment by alaz1987** [comment] 2022-08-03 10:47
The error appears when exporting data from a PostgresSQL table on a Windows platform.

![image](https://user-images.githubusercontent.com/6562482/182590301-bc447ecc-ce69-4393-9736-542f3187057b.png)

![image](https://user-images.githubusercontent.com/6562482/182590501-06b18246-c43c-4cc4-ac83-94a97117a580.png)
