### ISSUE TITLE
Unable to query binary data using bind parameters

### ISSUE THREAD

**Issue by adkhare** [serge-rider/dbeaver#956] opened 2016-11-08 20:15 UTC
`select * from auditlog where tenant_id = :tenant_id` where i need to put :tenant_id as binary

**Comment by adkhare** [comment] 2016-11-08 20:16
@serge-rider any recommendations?

**Comment by serge-rider** [comment] 2016-11-08 20:27
Duplicate of #942

**Closed by serge-rider** 2016-11-08 20:27 UTC
Labels: duplicate, feature request
