### ISSUE TITLE
Cassandra: codec not found exception

### ISSUE THREAD

**Issue by ffissore** [serge-rider/dbeaver#236] opened 2016-02-25 15:48 UTC
When fetching data from a table featuring a `created_at` column of type `timestamp`, stored into cassandra 2.2.5, dbeaver replies with 
`com.datastax.driver.core.exceptions.CodecNotFoundException: CodecNotFoundException: Codec not found for requested operation: [timestamp <-> com.datastax.driver.core.LocalDate]`

I suppose this is due to the a slight API change with java driver version 3. See http://www.datastax.com/dev/blog/datastax-java-driver-3-0-0-released#compatibility-with-cassandra-3.0

In essence: what was `{g,s}etDate` is now `{g,s}etTimestamp`, unless the column is of type `date` or `time`, in which case the method to use is `{g,s}etDate`

**Comment by ffissore** [comment] 2016-02-25 15:48
Forgot to mention: using just release dbeaver 3.6.0

**Comment by ffissore** [comment] 2016-02-25 15:49
I see you're also bundling 3.0.0_rc1: 3.0.0 went public, so you might also want to upgrade the jars

**Comment by serge-rider** [comment] 2016-02-25 18:40
Duplicate of #218
3.0.0_rc1 dependency came from cassandra-driver-dse dependency. for some reason Datastax didn't yet release dse 3.0.

**Closed by serge-rider** 2016-02-25 18:40 UTC
Labels: duplicate
