### ISSUE TITLE
Database navigation show cassandra bug

### ISSUE THREAD

**Issue by evildecay** [serge-rider/dbeaver#1274] opened 2017-02-16 02:15 UTC
![error](https://cloud.githubusercontent.com/assets/6789367/23004264/9d254e82-f430-11e6-9334-6ca7d1e90a5f.png)

In the script, drop the keyspace and then refresh the connection.

**Comment by serge-rider** [comment] 2017-02-16 07:03
Duplicate of #1236

**Closed by serge-rider** 2017-02-16 07:03 UTC
Labels: bug, duplicate
