### ISSUE TITLE
Application v3.8.2 won't start, OSX 10.11.6

### ISSUE THREAD

**Issue by Rob2015** [serge-rider/dbeaver#1095] opened 2016-12-22 18:22 UTC
Hi,
I have downloaded and installed _dbeaver-ce-3.8.2-macos.dmg_ under Applications on OSX 10.11.6.
When I start DBeaver and I get the following message.
See Schermafbeelding 2016-12-22 om.......jpg

That's all see. I have attached the logfile.
Could any one help me with whats is going on and why the application won't start.

Many thanks in advance for your advice.

![Uploading Schermafbeelding 2016-12-22 om 18.22.18.jpg…]()
[Uploading 1482427288598_log.txt…]()

**Comment by r-richmond** [comment] 2016-12-22 19:35
I think you commented before the files finished uploading...

**Comment by Rob2015** [comment] 2016-12-22 20:23
Retry uploading files
[1482427288598_log.txt](https://github.com/serge-rider/dbeaver/files/669722/1482427288598_log.txt)
![schermafbeelding 2016-12-22 om 18 22 18](https://cloud.githubusercontent.com/assets/14185674/21439191/e3e54072-c88c-11e6-8f36-d6bf7b33e6ad.jpg)

**Comment by serge-rider** [comment] 2016-12-23 12:39
Duplicate of #891
You need to install JDK 1.7.

**Closed by serge-rider** 2016-12-23 12:39 UTC
Labels: duplicate, question
