### ISSUE TITLE
After updating mysql driver,got error The server time zone 'fsf' is unrecognized or represent more than one time zone

### ISSUE THREAD

**Issue by AlexLuya** [serge-rider/dbeaver#590] opened 2016-07-11 08:51 UTC
Details like this:
The server time zone value '�й���׼ʱ��' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
  com.mysql.cj.core.exceptions.InvalidConnectionAttributeException: The server time zone value '�й���׼ʱ��' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.

**Comment by serge-rider** [comment] 2016-07-11 09:13
Duplicate of #573

**Closed by serge-rider** 2016-07-11 09:13 UTC
Labels: duplicate, question
