### ISSUE TITLE
Bug: Sql Parameters don't work in certain queries

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#1766] opened 2017-06-13 21:08 UTC
Hey Serge,

Certain queries don't appear to trigger the parameter dialog. See below for an example.

![parameter_bug](https://user-images.githubusercontent.com/9246654/27104644-c8857d96-5041-11e7-96a2-846116514413.gif)

Note: it would also be helpful if when searching preferences "parameters" returned a result rather than having to remember "processing" as these settings are quite hidden.

general > editors > sql editor > sql processing

<img width="455" alt="screen shot 2017-06-13 at 2 10 47 pm" src="https://user-images.githubusercontent.com/9246654/27104780-21abff6c-5042-11e7-9145-ccc2facc7351.png">

**Comment by serge-rider** [comment] 2017-06-13 21:22
Can't reproduce, could you post query sample (as text)?

**Comment by r-richmond** [comment] 2017-06-14 15:08
please note I've changed my Named Parameter Prefix in general > editors > sql editor > sql processing > parameters > named parameter prefix to $

```
-- works in postgres
select *
from $schema.$table;

--errors in postgres
create table $schema.$table as
select 1;
```

**Comment by serge-rider** [comment] 2017-06-16 19:29
Parameters are disabled for DDL queries. This was made on purpose - because DDL may contain parameters patterns which shouldn't be evaluated as parameters.

BTW the way you are using parameters is quite unusual :)
Potentially this problem can be resolved by adding extra config option. Any other ideas?

**Comment by r-richmond** [comment] 2017-06-18 23:21
> This was made on purpose - because DDL may contain parameters patterns which shouldn't be evaluated as parameters.

Oh could you expand on this a little?

> BTW the way you are using parameters is quite unusual :)

I could see it being unusual for applications but for data analytics its very common. In my particular use case we have some bash scripts that are creating tables & moving data and testing the scripts in Dbeaver would be super convenient. 

> Potentially this problem can be resolved by adding extra config option. Any other ideas?

An extra config option would be fine with me. i.e. Enable parameters for DDL queries.

The only other thing I can think to mention is perhaps it makes sense to have another option entirely. Call it something like Variable Substitution. With an option for variable prefix. As I'm not really trying to parameterize these queries just substitute variables in my scripts in this use case. It seems like you could probably subclass/modify the function the existing parameter function to accomplish this. That we could have a similar dialog screen for binding variables and we wouldn't allow parameters for ddl queries if that is something you wanted to avoid. (Although again I'm not sure why its advantageous to disallow parameters in ddl queries, and just allowing parameters in ddl queries would be great).


<img width="311" alt="screen shot 2017-06-18 at 4 17 02 pm" src="https://user-images.githubusercontent.com/9246654/27265023-0d20ff58-5442-11e7-8c5d-0ceb79ce57eb.png">

**Comment by serge-rider** [comment] 2017-06-20 05:23
> Oh could you expand on this a little?  

For instance DDL may contain CREATE PROCEDURE code and procedure declaration itself may contain usage of dynamic SQL parameters. Very often situation in Oracle and some other dbs.

So, extra config option it is:
![default](https://user-images.githubusercontent.com/6398845/27317753-35470810-5591-11e7-8fa9-38088b10141f.png)

![default](https://user-images.githubusercontent.com/6398845/27317766-4c2f3372-5591-11e7-918d-238d68be2367.png)

In regards to "variables". Potentially it can be useful but I don't want to overcomplicate UI at the moment.

**Closed** 2017-06-20 05:23 UTC
Labels: enhancement

**Comment by r-richmond** [comment] 2017-06-21 17:21
Thanks Serge! this looks great.
