### ISSUE TITLE
After creating a new table, cannot add a new row.

### ISSUE THREAD

**Issue by questioner9** [serge-rider/dbeaver#1789] opened 2017-06-16 18:33 UTC
Using version 4.0.8 amd64.deb package. 
I created a table with a CREATE TABLE statement, then refreshed the db connection, then opened the new table in the view, navigated to the 'Data' tab and pressed the '+' add new row button; but no new row was added. 

This issue seems to have been introduced in the latest version. I uninstalled v4.0.8 and reinstalled the v4.0.7 amd64.deb package. I went to the same view on the existing table made in v4.0.8 and used the add new row button which worked as expected and added a new row.

I'm not sure that the datatypes of the columns would affect things in trying to reproduce, but just in case I had various columns with types including INT UNSIGNED, TINYINT, VARCHAR, BOOLEAN, DATE. With a Primary key on INT UNSIGNED.

**Comment by kyleflan** [comment] 2017-06-16 20:10
Duplicate of #1722 

Workaround is available at the link above.

**Closed** 2017-06-19 19:27 UTC
Labels: bug, duplicate
