### ISSUE TITLE
NullPointerException when create table in MySQL

### ISSUE THREAD

**Issue by mifisa** [serge-rider/dbeaver#1340] opened 2017-02-23 15:22 UTC
When I try to create a table of MySQL database, it throws a NullPointerException.

<img width="392" alt="captura de pantalla 2017-02-23 a la s 09 21 37" src="https://cloud.githubusercontent.com/assets/17954258/23265219/a02a162a-f9a9-11e6-89a9-313a785ce299.png">

**Comment by serge-rider** [comment] 2017-02-23 16:08
Duplicate of  #1310

**Closed by serge-rider** 2017-02-23 16:08 UTC
Labels: bug, duplicate
