### ISSUE TITLE
Format - Index out of bounds 

### ISSUE THREAD

**Issue by kawinga** [serge-rider/dbeaver#263] opened 2016-03-03 15:12 UTC
Hello,

after using "Edit - Format - Format SQL" i get an "Index out of bounds"-error.

Log-File: [format.txt](https://github.com/serge-rider/dbeaver/files/157028/format.txt)

Java 1.8.0_73

Kind regards,

Robert

**Comment by carlosjrcabello** [comment] 2016-03-03 15:58
Hi @kawinga ,

What's database you were/are using? I'll try to reproduce here.

**Comment by serge-rider** [comment] 2016-03-03 18:49
Duplicate of  #242.
Will be fixed in the next version.

**Closed by serge-rider** 2016-03-03 18:49 UTC
Labels: bug, duplicate
