### ISSUE TITLE
DB Compare with DDL generation

### ISSUE THREAD

**Issue by lrweck** [serge-rider/dbeaver#1793] opened 2017-06-19 18:47 UTC
Hello!

I would like to suggest a new feature/improvement to the database compare feature.

In the window where you choose the compare settings for the objects there would be an option to create DDL for the missing objects.

For example, in the origin db you have an index that doesn't exist in the target db, so DBeaver generates a "CREATE INDEX" with the same rules as the origin db.

Thanks!

**Comment by djonatanfav** [comment] 2017-06-19 19:17
**up**

**Comment by serge-rider** [comment] 2017-06-22 05:12
Duplicate of #957

**Closed by serge-rider** 2017-06-22 05:12 UTC
Labels: duplicate, feature request
