### ISSUE TITLE
Oracle connection error in 4.0.0

### ISSUE THREAD

**Issue by acsdev** [serge-rider/dbeaver#1284] opened 2017-02-20 12:31 UTC
I have many connection on oracle that use connection string like:
this:jdbc:oracle:thin:user@myhost:1521/my.service.name

(There are actually dot on myservicename)

After I update dbeaver 3.8.5 for dbeaver 4.0.0 every connection stops to work.

Maybe there is a bug in this kind of jdbc url.

**Messge on dbeaver:
Internal error connecting to this:jdbc:oracle:thin:user@myhost:1521/my.service.name
java.lang.NullPointerExceptio**n:

**Comment by acsdev** [comment] 2017-02-20 12:33
Using terminal to monitor dbeaver I got this.

org.jkiss.dbeaver.DBException: Internal error connecting to <MY_CONNECTION_NAME>
org.jkiss.dbeaver.DBException: Internal error connecting to <MY_CONNECTION_NAME>
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:766)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:73)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.initializeContextState(OracleDataSource.java:144)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:119)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeMainContext(JDBCDataSource.java:117)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:111)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:100)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.<init>(OracleDataSource.java:80)
	at org.jkiss.dbeaver.ext.oracle.OracleDataSourceProvider.openDataSource(OracleDataSourceProvider.java:131)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:715)
	... 3 more

**Comment by loboaureo** [comment] 2017-02-20 12:39
i've got same issue

**Comment by Darych** [comment] 2017-02-20 12:50
Hi all,

I've got the same issue too.

**Comment by serge-rider** [comment] 2017-02-20 12:56
Thanks for report. This is a bug in Oracle connector.
Will be fixed in hotfix version (probably on this week).

**Comment by nikodc** [comment] 2017-02-20 12:59
I have the same issue. Is there any workwaround?

**Comment by loboaureo** [comment] 2017-02-20 13:04
Return to 3.8.5 works for me

**Comment by serge-rider** [comment] 2017-02-20 13:10
Workarounds:
- Rollback to 3.8.5
- Use EA version (http://dbeaver.jkiss.org/files/ea) - just built with this fix included

**Comment by nikodc** [comment] 2017-02-20 13:25
EA version works ok regarding this issue. But, I've found another error that could be related. When you open an Oracle connection by clicking the icon in the Projects tree (under Connections) this message appears:

java.sql.SQLException: ORA-01034: ORACLE not available
ORA-27101: shared memory realm does not exist
Linux-x86_64 Error: 2: No such file or directory

**Comment by serge-rider** [comment] 2017-02-20 13:29
@nikodc Does 3.8.5 connects ok? Looks like very different issue (some problem with connection parameters). Check this: https://community.oracle.com/thread/241281?start=30&tstart=0

**Comment by nikodc** [comment] 2017-02-20 13:37
3.8.5 works ok, the problem started with 4.0.0. I'm able to connect and run queries, the popup message appears only browing through the Projects tree.

BTW, I don't think the problem is related to Oracle (as your link suggests) because at my company we have many different Oracle instances running, with multiple versions of the DBMS, and I'm having this error    with all the connections I have configured.

**Comment by serge-rider** [comment] 2017-02-20 13:40
I don't quite understand when exactly this error happens. Could you post error stacktrace (you can get it in Error Log view)?

**Comment by Marcusg562** [comment] 2017-02-20 13:47
I've got the same issue. 3.8.5 worked fine for me a few minutes ago.

**Comment by serge-rider** [comment] 2017-02-20 13:53
@Marcusg562 if you have connectivity error then workarounds are:
- Rollback to 3.8.5
- Use EA version (http://dbeaver.jkiss.org/files/ea)

Fix will be added in hotfix version (probably on this week)

**Comment by Marcusg562** [comment] 2017-02-20 13:54
Thanks works fine.

**Comment by majkinetor** [comment] 2017-02-20 14:06
I confirm this. I reverted to 3.8.5

**Comment by fgroch** [comment] 2017-02-20 14:45
In my case Postgres connections works fine, I have issue with Oracle connections only

**Comment by nikodc** [comment] 2017-02-20 14:58
@serge-rider I can't get the log right now, but I'll try to get it for you as soon as I can. 

The error happens when you are at the "Projects" view. There, open the project node, then the Connections node and then open the Oracle connection by clicking in the arrow. Maybe it's something related to the migration of the date in my workspace from 3.8.5 to 4.0.0. I experienced some problems with the migration of my connections the first time I opened 4.0.0 EA (an old version, from 8 days ago, a link you sent me regarding #893).

**Comment by nmadham** [comment] 2017-02-20 17:13
org.jkiss.dbeaver.DBException: Can't load driver class 'oracle.jdbc.OracleDriver'
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:839)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:815)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getDriverInstance(DriverDescriptor.java:495)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSourceProvider.getConnectionProperties(JDBCDataSourceProvider.java:62)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPropertiesControl.loadDriverProperties(ConnectionPropertiesControl.java:138)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPropertiesControl.makeProperties(ConnectionPropertiesControl.java:64)
	at org.jkiss.dbeaver.ui.dialogs.connection.DriverPropertiesDialogPage$1.run(DriverPropertiesDialogPage.java:84)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate$1.run(RunnableContextDelegate.java:44)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: java.lang.ClassNotFoundException: oracle.jdbc.OracleDriver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:836)

**Comment by serge-rider** [comment] 2017-02-20 17:42
@nmadham This is a very different error. Most likely you didn't configure Oracle driver libraries - thus driver can't be loaded.

**Comment by nikodc** [comment] 2017-02-20 17:50
@serge-rider ignore me, i've found something wrong with my settings. My mistake.

**Comment by miguelavg** [comment] 2017-02-20 20:25
Same issue when migrating from 3.85

2017-02-20 15:22:09.184 - DBeaver 4.0.0 is starting
2017-02-20 15:22:09.186 - Install path: 'file:/C:/Program Files/DBeaver/'
2017-02-20 15:22:09.187 - Instance path: 'file:/C:/Users/Miguel/.dbeaver4/'
2017-02-20 15:22:09.189 - Memory available 61Mb/889Mb
2017-02-20 15:22:09.206 - Starting RMI server at 21883
2017-02-20 15:22:09.291 - Create display
2017-02-20 15:22:09.317 - Run workbench
2017-02-20 15:22:11.186 - Initializing DBeaver 4.0.0
2017-02-20 15:22:11.191 - Host plugin: org.jkiss.dbeaver.core.application 4.0.0
2017-02-20 15:22:11.195 - Initialize Core...
2017-02-20 15:22:11.413 - Core initialized (218ms)
2017-02-20 15:22:11.416 - Configure workbench window
2017-02-20 15:22:11.473 - Create actions
2017-02-20 15:22:11.477 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2017-02-20 15:22:11.483 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.navigation'
2017-02-20 15:22:11.488 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2017-02-20 15:22:11.920 - Initialize workbench window
2017-02-20 15:22:11.946 - Finish initialization
2017-02-20 15:22:39.502 - Connect with 'PDESAORA_STG' (oracle_thin-15a3ade2d49-6372fcb3f9f57ea0)
2017-02-20 15:22:40.172 - Connection failed (oracle_thin-15a3ade2d49-6372fcb3f9f57ea0)
2017-02-20 15:22:40.176 - org.jkiss.dbeaver.DBException: Internal error connecting to PDESAORA_STG
org.jkiss.dbeaver.DBException: Internal error connecting to PDESAORA_STG
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:766)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:73)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.initializeContextState(OracleDataSource.java:144)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:119)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeMainContext(JDBCDataSource.java:117)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:111)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:100)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.<init>(OracleDataSource.java:80)
	at org.jkiss.dbeaver.ext.oracle.OracleDataSourceProvider.openDataSource(OracleDataSourceProvider.java:131)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:715)
	... 3 more

**Comment by serge-rider** [comment] 2017-02-20 20:27
Copy from comments above: this is a bug in 4.0.0.
Workarounds:
- Rollback to 3.8.5 (http://dbeaver.jkiss.org/files/3.8.5/)
- Use EA version (http://dbeaver.jkiss.org/files/ea)

**Comment by miguelavg** [comment] 2017-02-20 21:30
Justo to confirm EA version is working for me. Thanks!

**Comment by Xrizoo** [comment] 2017-02-21 16:19
For me,  works fine on MySQL, MariaDB, PostgreSQL and Informix.... But ORACLE, any of my 4 DDBB instances let me in.

### Internal error connecting to Oracle - GIS
  java.lang.NullPointerException:

**Closed** 2017-02-22 07:30 UTC
Labels: bug, p:major

**Comment by dvdgsng** [comment] 2017-02-23 10:25
Any idea when the update-site for the Eclipse plugin will be updated to 4.0.1?

**Comment by serge-rider** [comment] 2017-02-23 11:04
It was updated along with standalone version. 
At the moment http://dbeaver.jkiss.org/update/latest/ point at 4.0.1 version.

**Comment by dvdgsng** [comment] 2017-02-23 11:33
Ah, somehow Eclipse didn't 'reload' the update site automatically. Works. Thanks
