### ISSUE TITLE
ctrl-scroll font-sizing (feature request)

### ISSUE THREAD

**Issue by Lonniebiz** [serge-rider/dbeaver#837] opened 2016-10-12 04:22 UTC
In 2015, dbeaver could not easily implement ctrl-scroll font sizing on top of the eclipse framework:
http://dbeaver.jkiss.org/forum/viewtopic.php?f=2&t=1826

Is this still the case in 2016? If so, how difficult would it be to tie the control-scroll-up and control-scroll-down events to the methods by which eclipse does indeed allow font-size changes (as a shortcut)?

**Comment by serge-rider** [comment] 2016-10-12 07:11
Duplicate of #671 
We going to migrate on Eclipse 4.6 in next couple of months.

**Closed by serge-rider** 2016-10-12 07:11 UTC
Labels: duplicate

**Comment by Lonniebiz** [comment] 2020-06-21 18:01
This is not an exact duplicate of #671. #671 is closed because the scaling can be achieved via `ctrl+` and `ctrl-`, which does indeed meet the `either or` nature of that feature request.

In my feature request, I'm specifically wanting to be able to achieve the font scaling via `ctrl + mouse-scroll-wheel`, which makes my request slightly different from #671.

Are there in upstream feature requests in Eclipse that may one day lead to this functionality? If not, where would you submit that?

Lastly, would it be possible for Dbeaver to implement this feature without the help of Eclipse, by listening for ctrl+scroll-wheel events and redirecting those events to the event handler for `ctrl`+ and `ctrl-`?

**Comment by Lonniebiz** [comment] 2021-06-30 09:57
Can we please open this issue? In my previous post (over a year ago), I explained why this issue is NOT a duplicate of #671. At the top of this issue, you can see that I've been requesting this since 2015.

**Comment by p91paul** [comment] 2021-06-30 16:26
I suggest you open a new issue. I think your point is valid and this issue was closed by mistake, but sometimes comments on old closed issues will get lost.

**Comment by NFSpeedy** [comment] 2021-12-29 20:11
Are we dragging the zoom feature into 2022? Is there a new ticket?
