### ISSUE TITLE
v4 connect to oracle NullPointerException

### ISSUE THREAD

**Issue by yanOnGithub** [serge-rider/dbeaver#1309] opened 2017-02-22 08:38 UTC
The driver is ojdbc6_g.jar

![image](https://cloud.githubusercontent.com/assets/25423046/23203378/3e8127ec-f91d-11e6-9156-c6aebc6de2ef.png)

**Comment by serge-rider** [comment] 2017-02-22 08:39
Duplicate of #1284. 
Already fixed, you can download 4.0.1.

**Closed by serge-rider** 2017-02-22 08:39 UTC
Labels: bug, duplicate
