### ISSUE TITLE
Problem with MySql and column name

### ISSUE THREAD

**Issue by jalzur** [serge-rider/dbeaver#2099] opened 2017-08-29 04:32 UTC
If we are working with MySql and have a table with a column that has the name "SOURCELOCALE" then the behaviour of DBeaver is weird.  If we try to do a select:
`select SOURCELOCALE from table`
then:
- It mark the word SOURCELOCALE in pink (and all the words after it)
- If we put the cursor in the query and hit ctrl + enter then we have an error:
```
SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
  com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
```

- If we select all the query and hit ctrl + enter then the query run properly
- if we write the word between backticks then it behaves normally

**Comment by jalzur** [comment] 2017-08-29 04:33
I tested with versions 4.1.2 and 4.1.3

**Comment by eanvafaei** [comment] 2017-08-29 04:42
I tested this and it happens to me too (version 4.1.3 on macOS Sierra).

**Comment by serge-rider** [comment] 2017-08-29 19:52
Duplicate of #2094

**Closed by serge-rider** 2017-08-29 19:52 UTC
Labels: bug, duplicate
