### ISSUE TITLE
ClassNotFoundException on Postgre connect

### ISSUE THREAD

**Issue by fgblomqvist** [serge-rider/dbeaver#1611] opened 2017-04-26 20:47 UTC
If I try to connect to my PostgreSQL db I get this error:
```
java/sql/SQLException
  java.lang.ClassNotFoundException: java.sql.SQLException
```
I'm running DBeaver 4.0.5 with Java 9-ea+162 using the `--add-modules=java.se.ee` fix.

**Comment by fgblomqvist** [comment] 2017-04-26 20:58
I switched to Java 8 and removed the fix. Now it works. But maybe this bug report could still be of interest.

**Comment by serge-rider** [comment] 2017-04-26 21:24
Interesting. Java 9 keeps me surprising again and again.
Thanks for information.

**Comment by nachaos** [comment] 2017-05-02 15:13
I'm having exactly the same issue. Any workaround to make it work? Thanks in advance.

**Comment by serge-rider** [comment] 2017-05-02 16:23
Standard workaround: use Java 8.

BTW could you post the complete stacktrace of this error (you can get it in Error Log view). I can't reproduce this in my environment.

**Comment by serge-rider** [comment] 2017-05-06 19:38
https://bugs.eclipse.org/bugs/show_bug.cgi?id=507417
This will be automatically resolved in DBeaver with next Eclipse Neon platform update.

**Closed by serge-rider** 2017-05-06 19:38 UTC
Labels: question
