### ISSUE TITLE
SQL editor problem

### ISSUE THREAD

**Issue by davitof** [serge-rider/dbeaver#802] opened 2016-10-02 23:48 UTC
Hello
I am completely new to dBeaver. I am trying to connect to a local Oracle XE 11.2.0.2.0 on my Windows 10 64 bits laptop. Everything seems to work fine with Oracle's SQL Developer. I installed dBeaver with 11.2.0.4 drivers. I can open the database, see it's schemas, even browse the table contents. But whenever I try to open the SQL editor, I get 
`org.eclipse.core.internal.resources.ResourceException: Resource '/General/Scripts' does not exist.`
Am I doing anything wrong or is this a bug?

**Comment by serge-rider** [comment] 2016-10-03 07:57
This seems to be a bug but I can't reproduce it.
Could you post error stacktrace? (open Error Log view in main menu Windows->Show View, double click on error).

**Comment by davitof** [comment] 2016-10-03 20:47
Thank you for your answer.

Wow, that was one of the strangest bug squashings I ever saw. This is going to be frustrating for you too. 

Because the log was full of all the errors I got when installing and setting up the drivers for Oracle, I decided to empty the log first and then trigger the error again. That was a bad idea: since I emptied the log, the error does not happen anymore. I checked in the dBeaver folders but obviously dBeaver erases the errors immediately from the disc, which makes sense. Sorry, there was maybe a bug, but I won't help you find out where it is. The only thing I can tell you is that I was having a lot of errors because of drivers issues. At first, I thought this bug was part of the drivers issues, but I finally managed to get the right drivers and this error stayed so I thought this was finally a real bug. Maybe it wasn't, maybe it was only dBeaver needing one more exit and restart before fixing everything.

**Comment by serge-rider** [comment] 2016-10-05 10:26
Ok, thanks for report anyway.
I'll close this issue for now. If you (or someone else) will reproduce this (and will have error stacktrace) - please reopen.

**Comment by sschaeckel** [comment] 2016-10-11 07:37
Hi. I have the same problem.

!SESSION 2016-10-11 09:31:19.011 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.jkiss.dbeaver.model 4 0 2016-10-11 09:31:44.804
!MESSAGE org.eclipse.core.internal.resources.ResourceException: Resource '/General/Scripts' does not exist.
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2016-10-11 09:31:44.804
!MESSAGE Resource '/General/Scripts' does not exist.
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource '/General/Scripts' does not exist.
	at org.eclipse.core.internal.resources.Resource.checkExists(Resource.java:334)
	at org.eclipse.core.internal.resources.Resource.checkAccessible(Resource.java:208)
	at org.eclipse.core.internal.resources.File.create(File.java:109)
	at org.eclipse.core.internal.resources.File.create(File.java:180)
	at org.jkiss.dbeaver.ui.resources.ResourceUtils.createNewScript(ResourceUtils.java:265)
	at org.jkiss.dbeaver.ui.editors.sql.handlers.OpenHandler.openEditor(OpenHandler.java:100)
	at org.jkiss.dbeaver.ui.editors.sql.handlers.OpenHandler.execute(OpenHandler.java:72)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:286)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:507)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:558)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:378)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:324)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:86)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1266)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1112)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1137)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1122)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1164)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1160)
	at org.eclipse.swt.widgets.Widget.wmKeyDown(Widget.java:1883)
	at org.eclipse.swt.widgets.Control.WM_KEYDOWN(Control.java:5049)
	at org.eclipse.swt.widgets.Tree.WM_KEYDOWN(Tree.java:6156)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4708)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:6024)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5050)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2549)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3767)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:203)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
!SUBENTRY 2 org.eclipse.core.resources 4 368 2016-10-11 09:31:44.804
!MESSAGE Resource '/General/Scripts' does not exist.

**Comment by serge-rider** [comment] 2016-10-11 20:49
Thanks for details.

**Closed by serge-rider** 2016-10-11 20:49 UTC
Labels: bug
