### ISSUE TITLE
[F5] refreshing data issues

### ISSUE THREAD

**Issue by qishibo** [serge-rider/dbeaver#2294] opened 2017-10-09 01:18 UTC
Select a table on [data] mode, point the cursor to a data line ,then enter [TAB],the data will show in cloumn mode , (id: such as 999 ), but when you enter [f5] to refresh the data, the data will change to id:1,not the prefer data (id:999)  

I don't konw what makes this happened...

Package: Linux Debian package 64 bit (installer)
Download Url: https://dbeaver.jkiss.org/files/dbeaver-ce_latest_amd64.deb
Version: 4.2.2
OS: Linux qii-PC 4.9.0-deepin4-amd64 #1 SMP PREEMPT Deepin 4.9.8-4 (2017-04-17) x86_64 GNU/Linux

:100:

**Comment by serge-rider** [comment] 2017-10-09 21:00
Duplicate of #2269
Thanks for report anyway.

**Closed by serge-rider** 2017-10-09 21:00 UTC
Labels: bug, duplicate
