### ISSUE TITLE
“Dbeaver” is damaged and can’t be opened. You should move it to the Trash, after upgrading to CE 3.8.5.

### ISSUE THREAD

**Issue by connercowling** [serge-rider/dbeaver#1218] opened 2017-02-01 21:43 UTC
Cannot open DBeaver application after installing: “Dbeaver” is damaged and can’t be opened. You should move it to the Trash.

**Comment by serge-rider** [comment] 2017-02-01 22:25
Duplicate of #95 .
This isn't result of upgrade (more likely result of MacOS update).

**Closed by serge-rider** 2017-02-01 22:25 UTC
Labels: bug, duplicate

**Comment by connercowling** [comment] 2017-02-02 16:03
DBeaver 3.8.4 was working great. I updated to latest OS: Sierra 10.12.3 and tried again with 3.8.5, same issue.

**Comment by serge-rider** [comment] 2017-02-02 16:08
There are no any differences between 3.8.4 and 3.8.5 in regards to MacOS version.
Update to Sierra is the reason why this problem appeared. Because now MacOS versions have more restrictive software install policy.
Check for workarounds in #95.

Hopefully DBeaver 4.x will resolve this problem (by signing Mac application).

**Comment by connercowling** [comment] 2017-02-02 16:10
I was still on Sierra before with DBeaver 3.8.4.  I'll keep fiddling, try building from source. Thanks for the prompt response.

**Comment by connercowling** [comment] 2017-02-06 15:21
This worked:

```
xattr -rc /Applications/DBeaver.app
```

See [here](https://github.com/serge-rider/dbeaver/issues/95)
