### ISSUE TITLE
JDBC connection to Oracle failed after upgrading to 4.0

### ISSUE THREAD

**Issue by Teofast** [serge-rider/dbeaver#1297] opened 2017-02-21 08:34 UTC
Internal error connecting to jdbc:oracle:thin:@(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = <somehost>)(PORT = 1521)) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME =<service>) ) )
  java.lang.NullPointerException: 

![s_20170221-01](https://cloud.githubusercontent.com/assets/25922798/23156828/2d8a2be8-f821-11e6-8219-14640d25af99.png)

Rollback to 3.5 is the only way to resolve. Same configuration working without issue on previous to 4.0 versions.

**Comment by serge-rider** [comment] 2017-02-21 08:45
Duplicate of #1284

**Closed by serge-rider** 2017-02-21 08:45 UTC
Labels: bug, duplicate
