### ISSUE TITLE
Missing foreign keys

### ISSUE THREAD

**Issue by Azenet** [serge-rider/dbeaver#1000] opened 2016-11-24 12:45 UTC
Hi,

I am not sure this is easily reproducible, if reproducible at all. I have an issue with DBeaver 3.8, sometimes the foreign keys will not load when I open a table, so fields that actually have foreign keys will not show the button to go to the linked row in another table.

Steps that seems to have the best reproducibility for me:
1. Click once a disconnected connection
2. Press Enter, a SQL editor will open and the connection will connect
3. Open a table that contains foreign keys
4. Foreign keys are not loaded until you go in Properties > Foreign keys and press F5.

**Comment by temporaryaccount** [comment] 2016-11-24 12:49
I can confirm, I had the same issue today on a MySQL connection.

**Comment by serge-rider** [comment] 2016-11-24 13:38
I saw this once but can't reproduce again. Will try again later.
Maybe it is a result of recent object editor redesign..

**Comment by serge-rider** [comment] 2016-11-29 17:42
I think this problem was a result of bug in metadata cache reading. It was fixed in https://github.com/serge-rider/dbeaver/commit/e267ec0ca45dd52384fc7b4897447c415c3bcaf1

**Closed by serge-rider** 2016-11-29 17:42 UTC
Labels: bug, can't reproduce
