### ISSUE TITLE
Repeating toolbar buttons, reset to normal when restarted

### ISSUE THREAD

**Issue by dbza** [serge-rider/dbeaver#785] opened 2016-09-28 20:02 UTC
I don't know what keystroke etc. created this or how to reproduce. Just reporting FYI

![image](https://cloud.githubusercontent.com/assets/419093/18929968/1628a6fa-857b-11e6-8799-851a7b724386.png)

This resolved after restarting

**Comment by serge-rider** [comment] 2016-09-29 07:57
Yes, I saw this weird thing a couple of times (you can fix it by closing all open SQL editors).
Looks like a bug but I also don't now how to reproduce that.

Will keep this issue open, maybe somebody sees this more often and will provide steps to reproduce.

**Comment by carlosjrcabello** [comment] 2016-09-29 09:53
One day some of group bar just 'moved' from left to right on toolbar, to
fix it that time, I used perspective reset..but it was older versions +-
early this year.

**Comment by serge-rider** [comment] 2016-10-31 15:23
Please check how it works in 3.7.8

**Closed** 2016-11-21 10:24 UTC
Labels: bug
