### ISSUE TITLE
Oracle - Function based indexes are not shown correctly

### ISSUE THREAD

**Issue by prog-rajkamal** [serge-rider/dbeaver#2456] opened 2017-10-31 11:43 UTC
**Issue**:

When I try to view indexes of a table, fucntion based indexes are shown as DB based indentifier instead of  underlying function

**Steps to reproduce**:

1. Create a table with function based index. Refer to https://oracle-base.com/articles/8i/function-based-indexes for SQL query examples

2. In the Database navigator, select the table and right click on it.

3. In context menu choose, "Edit Table" (shortcut is F4).

4. In the "Edit Table" view, there is a set of tabs "columns", "constraints" etc.  Select "indexes" tab.

5. Expand the function based index to view its constituents columns.

**Expected Result**: User should see te function on which the index is based on.

**Actual Result**: User sees a system generated identifier

**Screenshot**:

![dbeaver__oracle__function_based_indexing_not_working](https://user-images.githubusercontent.com/11518519/32222296-ba5bd964-be5e-11e7-8d4e-ca6b83c91328.png)

**Comment by serge-rider** [comment] 2017-11-26 11:48
Duplicate of #2573 (sorry, I just missed this ticket and made 2573 earlier).

**Closed by serge-rider** 2017-11-26 11:48 UTC
Labels: enhancement
