### ISSUE TITLE
Move items in Database Navigator up and down

### ISSUE THREAD

**Issue by shivan** [serge-rider/dbeaver#833] opened 2016-10-11 07:02 UTC
Is it currently anyhow possible to move items up/down in the Database Navigator?
For example with two buttons in the toolbar there (up, down)

**Comment by serge-rider** [comment] 2016-10-26 18:31
No, it is not possible. If you mean changing columns order then it is duplicate of #91.

**Comment by shivan** [comment] 2016-10-27 08:12
Do we talk about the same feature? I'm talking about manually sorting the database connections in the treeview.

**Comment by serge-rider** [comment] 2016-10-27 09:46
Then we are talking about different things.

Well, connections are sorted in alphabetical order. Thus manual reordering doesn't make sense.
But you can organize connection using folders.

**Comment by shivan** [comment] 2016-10-27 09:50
But the sort isn't done always. After adding a new entry (by copy for example) it isn't sorted.

By renaming an item, it isn't resorted.

So I think that re-sort should be done after copy and after rename finished, too. Even when renaming via edit dialog (F4).

**Comment by serge-rider** [comment] 2016-10-27 10:29
Agreed

**Closed** 2016-10-29 13:52 UTC
Labels: enhancement
