### ISSUE TITLE
debater 4.2.2 don't start on OS X

### ISSUE THREAD

**Issue by laurentleseigneur** [serge-rider/dbeaver#2333] opened 2017-10-13 19:57 UTC
java is latest available oracle jdk

```
JAVA_HOME set to /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

my $HOME/.dbeaver4/.log says:

```
Caused by: java.lang.ClassNotFoundException: javax.annotation.PreDestroy cannot be found by org.eclipse.e4.core.di_1.6.100.v20170421-1418
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 21 more
```

**Comment by laurentleseigneur** [comment] 2017-10-13 19:58
installed with `brew cask install dbeaver-community`

**Comment by serge-rider** [comment] 2017-10-14 08:11
Seems to be duplicate of #2333
Thanks for report anyway

**Closed by serge-rider** 2017-10-14 08:11 UTC
Labels: duplicate

**Comment by giacgbj** [comment] 2017-10-16 15:43
@serge-rider probably meant a duplicate of #1559 :-)
