### ISSUE TITLE
Cannot connect to Oracle Dbases

### ISSUE THREAD

**Issue by nmadham** [serge-rider/dbeaver#1289] opened 2017-02-20 17:02 UTC
I am using same settings as I used for earlier version of Dbeaver .Still unable to connect...please review.

![image](https://cloud.githubusercontent.com/assets/16705400/23135002/deb8d2b0-f764-11e6-942f-1620de6268a0.png)

**Comment by serge-rider** [comment] 2017-02-20 17:39
Duplicate of #1284

**Closed by serge-rider** 2017-02-20 17:39 UTC
Labels: bug, duplicate
