### ISSUE TITLE
Oracle: Missing IN or OUT parameter

### ISSUE THREAD

**Issue by creage** [serge-rider/dbeaver#917] opened 2016-10-31 07:22 UTC
After upgrading to 3.7.7 I get this exception
```
SQL Error [17041] [99999]: Missing IN or OUT parameter at index:: 1
  java.sql.SQLException: Missing IN or OUT parameter at index:: 1
```
And I didn't have such issue before.

I'm running Oracle11g on Windows2012, using ojdbc6

Here is a link to the log file https://dl.dropboxusercontent.com/u/17692263/log.txt

**Comment by infectormp** [comment] 2016-10-31 09:06
Duplicate of https://github.com/serge-rider/dbeaver/issues/882, please use search before post bugs.

**Comment by serge-rider** [comment] 2016-10-31 15:21
Yes, this is a duplicate.
You can check how it works in 3.7.8 (just released)

**Closed by serge-rider** 2016-10-31 15:21 UTC
Labels: duplicate
