### ISSUE TITLE
MS SQLServer DDL problems...

### ISSUE THREAD

**Issue by undertherainITA** [serge-rider/dbeaver#1070] opened 2016-12-15 16:44 UTC
Hi.
After using DBeaver for years with IBM DB2, now I'm doing a project with MS SQLServer.
I encountered some problems with DDL generation:

1) They are custom data formats generated incorrectly: 

Ex.)
CREATE TABLE SCHEMA.TABLENAME (
	ID int NOT NULL IDENTITY(1,1),
	NAME varchar(50) NOT NULL,
	VALUE UT_IDENTIFIER(64) NOT NULL,
)go

UT_IDENTIFIER is a VARCHAR(64) but the correct DDL is:

CREATE TABLE SCHEMA.TABLENAME (
	ID int NOT NULL IDENTITY(1,1),
	NAME varchar(50) NOT NULL,
	VALUE UT_IDENTIFIER NOT NULL,
)go

2) Constraint are generated both on table and on separate unique index (and it is wrong):

CREATE TABLE SCHEMA.TABLENAME (
	ID int NOT NULL IDENTITY(1,1),
	NAME varchar(50) NOT NULL,
	VALUE UT_IDENTIFIER NOT NULL,
	CONSTRAINT PK_INDEX PRIMARY KEY (ID)
)go
CREATE UNIQUE INDEX PK_INDEX ON SCHEMA.TABLENAME (ID)go

3) Functions for default values are generated as strings:

Ex.)
CREATE TABLE SCHEMA.TABLENAME (
	ID int NOT NULL IDENTITY(1,1),
	NAME varchar(50) NOT NULL,
	VALUE UT_IDENTIFIER NOT NULL,
	DAT_ATT_RECORD datetime NOT NULL DEFAULT '(getdate())',
	CONSTRAINT PK_INDEX PRIMARY KEY (ID)
)go

Correct is:

CREATE TABLE SCHEMA.TABLENAME (
	ID int NOT NULL IDENTITY(1,1),
	NAME varchar(50) NOT NULL,
	VALUE UT_IDENTIFIER NOT NULL,
	DAT_ATT_RECORD datetime NOT NULL DEFAULT (getdate()),
	CONSTRAINT PK_INDEX PRIMARY KEY (ID)
)go

Thanks for DBeaver, really!
Ciao... ;)

**Comment by undertherainITA** [comment] 2017-01-05 11:33
Hi.
News? ;)

**Comment by serge-rider** [comment] 2017-01-13 17:41
1. What is UT_IDENTIFIER? Maybe some sample DDL?
2. Will be fixed in 3.8.4
3. Can't reproduce. getdate() isn't string:
```sql
CREATE TABLE sample.dbo.Example (
	id tinyint NOT NULL IDENTITY(1,1),
	sname varchar(50) NOT NULL,
	id_usr varchar(50) NOT NULL,
	fecha datetimeoffset(34) NOT NULL DEFAULT (getdate()),
	date_value date(10),
	time_column time(16),
	ts_column timestamp NOT NULL,
	dt_column datetime,
	Column1 varchar(100) DEFAULT (getdate())
)go
CREATE INDEX Example_sname_IDX ON sample.dbo.Example (sname)go
```

**Comment by undertherainITA** [comment] 2017-01-19 14:21
Hi.
Excuse me for the late reply.

1) UT_IDENTIFIER is a user-defined datatype.
The problem is that the DDL must contain UT_IDENTIFIER and not UT_IDENTIFIER (64) which is a "strange" merge because UT_IDENTIFIER is defined as VARCHAR (64), you know?
2) Ok.
3) The problem is that default values ​​that are enhanced with functions put quotes by mistake.
Es.)

ERROR	==>	DAT_ATT_RECORD datetime NOT NULL DEFAULT '(getdate())',
OK	        ==>	DAT_ATT_RECORD datetime NOT NULL DEFAULT (getdate()),

Thanks for your wonderful work.
Ciao... ;)

**Comment by serge-rider** [comment] 2017-01-19 14:33
1. That's what I thought. DBeaver doesn't support UDTs in Generic driver.
3. I can't reproduce that - when I set default value to an expression then it is not quoted in DDL. The same about default values set externally.
What SQL Server driver do you use? Could you try another one?

**Comment by undertherainITA** [comment] 2017-01-19 14:43
1) Ok, but... it's a problem...
There is a way to solve?
For example by reading from some system table...
2) I use sqljdbc_6.0 with SQL Server 12.0.5000.0.

DDL with SQLServer Management Studio:

CREATE TABLE [EMIR].[EMIR_NORMALIZER_RULE](
	[ID] [decimal](19, 0) IDENTITY(1,1) NOT NULL,
	[DAT_ATT_RECORD] [datetime] NOT NULL,
	[COD_OPID] [varchar](20) NOT NULL,
	[TIPODATO] [varchar](50) NOT NULL,
	[COD_REGOLA] [varchar](30) NOT NULL,
	[DES_REGOLA] [varchar](255) NULL,
	[TABLE_DEST] [varchar](50) NOT NULL,
	[COMMENT] [varchar](64) NULL,
 CONSTRAINT [PK_EMIR_NORMALIZER_RULE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [EMIR].[EMIR_NORMALIZER_RULE] ADD  DEFAULT (getdate()) FOR [DAT_ATT_RECORD]
GO

DDL with DBeaver:

CREATE TABLE EMIR_D_DUEMME.EMIR.EMIR_NORMALIZER_RULE (
	ID decimal() NOT NULL IDENTITY(1,1),
	DAT_ATT_RECORD datetime NOT NULL DEFAULT '(getdate())',
	COD_OPID varchar(20) NOT NULL,
	TIPODATO varchar(50) NOT NULL,
	COD_REGOLA varchar(30) NOT NULL,
	DES_REGOLA varchar(255),
	TABLE_DEST varchar(50) NOT NULL,
	COMMENT varchar(64),
	CONSTRAINT PK_EMIR_NORMALIZER_RULE PRIMARY KEY (ID)
)go
CREATE UNIQUE INDEX PK_EMIR_NORMALIZER_RULE ON EMIR_D_DUEMME.EMIR.EMIR_NORMALIZER_RULE (ID)go

Thanks.
Ciao... ;)

**Comment by serge-rider** [comment] 2017-01-20 19:52
I've reproduced that, thanks for details.

All issues (quoted default value, precision specification for UDT and wrong DECIMAL type definition will be fixed in the next version.

**Closed** 2017-01-20 19:52 UTC
Labels: bug
