### ISSUE TITLE
[NFR] Autocomplete match keys on join

### ISSUE THREAD

**Issue by williamokano** [serge-rider/dbeaver#868] opened 2016-10-20 12:42 UTC
Hi Serge, is it possible to when I'm writing the query, on the part of the inner join, after I type ON, scan the meta and suggest/auto complete the match against the keys? Ex.:

Tbl `user`: `id, name`
Tbl `role`: `id, name`
Tbl `role_user`: `id_user, id_role`

```
SELECT * FROM user u
INNER JOIN role_user ru ON
```

then when I ask for completion after the `ON` it should "suggest" for me

```
ru.id_user = u.id_user
```

Thanks a lot, dbeaver is the best :)

PS.: JetBrain's datagrip have this feature, if benchmark needed! (There's a trial version :P)

**Comment by serge-rider** [comment] 2016-10-20 18:04
Duplicate of #397 
Will try to add this in the next version..

**Closed** 2016-10-20 18:04 UTC
Labels: duplicate, feature request
