### ISSUE TITLE
HIVE datasource doesn't work due to missing features in HIVE driver

### ISSUE THREAD

**Issue by jischebeck** [serge-rider/dbeaver#145] opened 2016-01-03 21:51 UTC
HIVE jdbc driver always raises an *SQLError* in the *isWritable* method of *org.apache.hive.jdbc.HiveResultSetMetaData*. See driver source code: https://github.com/apache/hive/blob/master/jdbc/src/java/org/apache/hive/jdbc/HiveResultSetMetaData.java

I used the following patch as workaround.
```diff
diff --git a/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/jdbc/exec/JDBCColumnMetaData.java b/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/jdbc/exec/JDBCColumnMetaData.java
index 69abf79..6175482 100644
--- a/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/jdbc/exec/JDBCColumnMetaData.java
+++ b/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/jdbc/exec/JDBCColumnMetaData.java
@@ -53,7 +53,7 @@
     private final int typeID;
     private final String typeName;
     private final boolean readOnly;
-    private final boolean writable;
+    private boolean writable;
     private final boolean sequence;
     private final DBPDataKind dataKind;
     private JDBCTableMetaData tableMetaData;
@@ -90,7 +90,15 @@
         // TODO: some drivers (DB2) always mark all columns as read only. Dunno why. So let's ignore this property
         // read-only connections are detected separately.
         this.readOnly = false;//resultSetMeta.isReadOnly(ordinalPosition + 1);
-        this.writable = resultSetMeta.isWritable(ordinalPosition + 1);
+        try {
+        	this.writable = resultSetMeta.isWritable(ordinalPosition + 1);
+        } catch (SQLException e) {
+        	if (e.getMessage()=="Method not supported") {
+        		this.writable = false;
+        	} else {
+        		throw e;
+        	}
+        }
 
         String fetchedTableName = null;
         try {
```

**Comment by codebling** [comment] 2016-01-07 00:41
Sweet!   Something seems a little wonky with that driver, though.. 

```
  public boolean isReadOnly(int column) throws SQLException {
    return true;
  }
```

If every column is read-only, shouldn't it follow that every column is also definitely not writable? And yet...
```
  public boolean isWritable(int column) throws SQLException {
    throw new SQLException("Method not supported");
  }
```
```
  public boolean isDefinitelyWritable(int column) throws SQLException {
    throw new SQLException("Method not supported");
  }
```


Seems like it would be better to fix this in the driver, if we can, changing the return value of both of those methods to `false`. What do you think?

**Comment by codebling** [comment] 2016-01-07 00:49
[HIVE 0.14 supports UPDATE](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DML#LanguageManualDML-Update), which implies that every column is NOT read-only. Looks like that driver needs some work.

**Comment by jischebeck** [comment] 2016-01-07 10:15
The driver needs definitely to be improved. 
Still the current behaviour of Dbeaver to just fail is not good. Squirrel or Eclipse Data Management Tools are working fine with HIVE. 

I thought of creating a new plugin for HIVE which works around the Metadata topics, but I haven't fully understood how to inherit/overwrite the jdbc exec classes.
A new plugin would also allow to handle JAR uploads for user defined functions etc.

**Comment by serge-rider** [comment] 2016-02-21 18:31
This (a few other) workarounds are present in 3.6.0.
So I'll close this issue.

**Comment by cdatta** [comment] 2016-08-30 15:29
Hi,
We are using 3.6.0 and Hive 0.12. Still getting the same error.
Is there any specific settings exists from DBeaver standpoint in order to connect? Just wondering.
Thanks..

**Comment by serge-rider** [comment] 2016-08-30 15:46
Could you clarify - what exactly error are you getting?

**Comment by cdatta** [comment] 2016-08-30 15:53
We are able to connect to the Hive successfully but while fetching data we are getting "Method not supported" exception.

**Comment by serge-rider** [comment] 2016-08-30 17:14
That's odd.
Can you test it with the recent DBeaver version? And if it still doesn't work - could you send stacktrace of this error (you can get it in Error Log view).

**Comment by cdatta** [comment] 2016-08-30 19:37
Error Log 1:

2016-08-30 14:19:32.597 - Can't get column 'IS_AUTOINCREMENT': null
2016-08-30 14:19:57.049 - org.jkiss.dbeaver.DBException: SQL Error: Method not supported
org.jkiss.dbeaver.DBException: SQL Error: Method not supported
       	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.loadObjects(JDBCCompositeCache.java:315)
       	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getObjects(JDBCCompositeCache.java:113)
       	at org.jkiss.dbeaver.ext.generic.model.GenericTable.getIndexes(GenericTable.java:160)
       	at org.jkiss.dbeaver.model.DBUtils.getBestTableIdentifier(DBUtils.java:658)
       	at org.jkiss.dbeaver.ext.erd.model.ERDEntity.fromObject(ERDEntity.java:251)
       	at org.jkiss.dbeaver.ext.erd.model.EntityDiagram.fillTables(EntityDiagram.java:250)
       	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded.loadFromDatabase(ERDEditorEmbedded.java:168)
       	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded.access$1(ERDEditorEmbedded.java:154)
       	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded$1.evaluate(ERDEditorEmbedded.java:129)
       	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded$1.evaluate(ERDEditorEmbedded.java:1)
       	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:82)
       	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:69)
       	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
       	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.sql.SQLException: Method not supported
       	at org.apache.hive.jdbc.HiveDatabaseMetaData.getIndexInfo(HiveDatabaseMetaData.java:382)
       	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getIndexInfo(JDBCDatabaseMetaDataImpl.java:1248)
       	at org.jkiss.dbeaver.ext.generic.model.IndexCache.prepareObjectsStatement(IndexCache.java:63)
       	at org.jkiss.dbeaver.ext.generic.model.IndexCache.prepareObjectsStatement(IndexCache.java:1)
       	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.loadObjects(JDBCCompositeCache.java:235)
       	... 13 more
2016-08-30 14:20:43.012 - Can't get column 'IS_AUTOINCREMENT': null
2016-08-30 14:20:43.012 - Can't get column 'IS_AUTOINCREMENT': null

#########################################

Error Log 2:
org.jkiss.dbeaver.model.impl.jdbc.JDBCException: SQL Error: Method not supported
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:167)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:1)
	at org.jkiss.dbeaver.model.DBUtils.createStatement(DBUtils.java:830)
	at org.jkiss.dbeaver.model.DBUtils.prepareStatement(DBUtils.java:806)
	at org.jkiss.dbeaver.model.DBUtils.prepareStatement(DBUtils.java:763)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:304)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:667)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1203)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:131)
	at org.jkiss.dbeaver.runtime.AbstractJob.run(AbstractJob.java:100)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.sql.SQLException: Method not supported
	at org.apache.hive.jdbc.HiveConnection.createStatement(HiveConnection.java:430)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.createStatement(JDBCConnectionImpl.java:353)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:120)
	... 10 more

###################################

**Comment by serge-rider** [comment] 2016-08-30 19:59
Thanks. But this stacktrace is definitely not from the 3.7.3 version. Can you try 3.7.3?

**Comment by cdatta** [comment] 2016-08-30 21:50
Another log: 

org.jkiss.dbeaver.DBException: SQL Error: Method not supported
org.jkiss.dbeaver.DBException: SQL Error: Method not supported
       at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.loadObjects(JDBCCompositeCache.java:315)
       at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getObjects(JDBCCompositeCache.java:113)
       at org.jkiss.dbeaver.ext.generic.model.GenericTable.getIndexes(GenericTable.java:160)
       at org.jkiss.dbeaver.model.DBUtils.getBestTableIdentifier(DBUtils.java:658)
       at org.jkiss.dbeaver.ext.erd.model.ERDEntity.fromObject(ERDEntity.java:251)
       at org.jkiss.dbeaver.ext.erd.model.EntityDiagram.fillTables(EntityDiagram.java:250)
       at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded.loadFromDatabase(ERDEditorEmbedded.java:168)
       at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded.access$1(ERDEditorEmbedded.java:154)
       at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded$1.evaluate(ERDEditorEmbedded.java:129)
       at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded$1.evaluate(ERDEditorEmbedded.java:1)
       at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:82)
       at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:69)
       at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
       at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.sql.SQLException: Method not supported
       at org.apache.hive.jdbc.HiveDatabaseMetaData.getIndexInfo(HiveDatabaseMetaData.java:382)
       at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getIndexInfo(JDBCDatabaseMetaDataImpl.java:1248)
       at org.jkiss.dbeaver.ext.generic.model.IndexCache.prepareObjectsStatement(IndexCache.java:63)
       at org.jkiss.dbeaver.ext.generic.model.IndexCache.prepareObjectsStatement(IndexCache.java:1)
       at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.loadObjects(JDBCCompositeCache.java:235)
       ... 13 more

**Comment by cdatta** [comment] 2016-08-30 21:50
Please let me know if you need more information. Thanks.

**Comment by serge-rider** [comment] 2016-08-30 21:59
Yeah, that's better, this stacktrace is from 3.7.3. But it isn't related to query execution (it is a warning during indexes metadata reading). 
Please post stack for error which happens during query execution.

**Comment by cdatta** [comment] 2016-08-31 13:53
Please see more stack below..

!ENTRY org.jkiss.dbeaver.model 4 0 2016-08-31 02:13:30.844
!MESSAGE org.jkiss.dbeaver.model.impl.jdbc.JDBCException: SQL Error: Method not supported
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2016-08-31 02:13:30.844
!MESSAGE SQL Error: Method not supported
!STACK 0
org.jkiss.dbeaver.model.impl.jdbc.JDBCException: SQL Error: Method not supported
       	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:178)
       	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:1)
       	at org.jkiss.dbeaver.model.DBUtils.createStatement(DBUtils.java:949)
       	at org.jkiss.dbeaver.model.DBUtils.prepareStatement(DBUtils.java:920)
       	at org.jkiss.dbeaver.model.DBUtils.prepareStatement(DBUtils.java:870)
       	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:161)
       	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:139)
       	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
       	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.sql.SQLException: Method not supported
       	at org.apache.hive.jdbc.HiveConnection.createStatement(HiveConnection.java:430)
       	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.createStatement(JDBCConnectionImpl.java:367)
       	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:123)
       	... 8 more

Thanks

**Comment by serge-rider** [comment] 2016-08-31 14:13
Thanks for details. Now I see the source error. Will add another workaround in the next version.

**Comment by cdatta** [comment] 2016-08-31 14:22
Concurrency resultset  and scroll sensitive result set are not supported from Hive stand point. So, please take a look at the result set type as well. 

Thanks.

**Closed** 2016-09-01 18:30 UTC
Labels: bug, can't reproduce
