### ISSUE TITLE
View/Procedure DDL unavailable - DB2 iSeries

### ISSUE THREAD

**Issue by gabesimoes** [serge-rider/dbeaver#965] opened 2016-11-11 16:32 UTC
Hello,

I am recently trying this application 3.7.8 and it seems great so far but I'm running into an issue with DB2 on the iSeries 7.1. 

When I try to extract the DDL for a view I get: "view definition not available."

When attempting to extract DDL for a procedure I get: "source code not available." 

Neither message generates anything written to the debug.log. Table DDL works fine. Is DDL for other objects not support for this version of DB2? Or is there another driver or add-on I need to source?

Thank you!!

**Comment by serge-rider** [comment] 2016-11-13 15:02
Duplicate of #632

**Closed by serge-rider** 2016-11-13 15:02 UTC
Labels: duplicate, feature request
