### ISSUE TITLE
SQL Error [17041] [99999]: Missing IN or OUT parameter at index:: 1 when using with OracleDB

### ISSUE THREAD

**Issue by chrismoors** [serge-rider/dbeaver#882] opened 2016-10-24 10:59 UTC
Just updated to 3.7.7 x64 on windows 7, now whenever I bring up the SQL Worksheet for an OracleDB instance I get the above message. I can still run queries against the database. This doesn't seem to affect MariaDB or MS SQL DBs.

![dbeaver error](https://cloud.githubusercontent.com/assets/12589460/19643249/c39eea3a-99bf-11e6-8f67-49b20b7d8aec.jpg)

**Comment by serge-rider** [comment] 2016-10-24 12:28
Can't reproduce.
Please post error stacktrace (you can get in ErrorLog view)

**Comment by serge-rider** [comment] 2016-10-24 13:28
This error happens if you have Oracle schema filters.
Will be fixed in the next version.

**Comment by JamesCZ** [comment] 2016-10-24 14:42
@serge-rider May I asked you when a new version of DBeaver will be available?

**Comment by serge-rider** [comment] 2016-10-24 14:54
After a week, I think. You can see it on milestones page.

Next version will be a pure a bugfixing version. 
And it will be the last 3.7.x version.

**Closed** 2016-10-24 22:45 UTC
Labels: bug
