### ISSUE TITLE
Postgresql insert columns proposals

### ISSUE THREAD

**Issue by ems2811** [serge-rider/dbeaver#828] opened 2016-10-10 18:37 UTC
DBeaver 3.7.6 x86
Postgresql 9.5
When typing "INSERT INTO table_name(" and press ctrl+space - empty search (no proposals)
When i specify the scheme - everything works correctly (i receive list of columns)

**Comment by serge-rider** [comment] 2016-10-11 08:10
I assume that you inserting into non-default schema.
Change active schema in database navigator or in main toolbar. SQL completion proposals are shown for "visible" objects, i.e. for active database/schema.

**Comment by ems2811** [comment] 2016-10-11 11:08
I'm sorry, I was wrong
The problem arises if you do not write the beginning of the column name
Those to do so if:
"INSERT INTO some_table(some_col" and press ctrl+space - i receive proposals
if so:
"INSERT INTO some_table(" and press ctrl+space - empty search (no proposals) (in previous versions i receive full list of columns)

**Comment by serge-rider** [comment] 2016-10-12 09:53
Can't reproduce that.
Is "some_table" is in your default schema/search path?

**Comment by ems2811** [comment] 2016-10-12 10:52
The same problem with "SELECT" (if search string is empty - dbeaver doesn't return results)
![example](https://cloud.githubusercontent.com/assets/22142845/19307446/23b23c9c-9083-11e6-9da8-56ae3aba50f4.JPG)

**Comment by serge-rider** [comment] 2016-10-12 11:54
Maybe it is the same problem as in #809 ?
After manual table create you need to refresh metadata to make autocomplete work.

**Comment by ems2811** [comment] 2016-10-12 13:00
Really refreshing metadata helps, but i still can not correctly describe the problem. another variant:
blank search does not work if the table contains no scheme
examples:
select *press here ctrl+space without typing anything* from some_table - no proposals
select i *press here ctrl+space after typing "i'* from some_table - list of matching columns
select *press here ctrl+space without typing anything* from public.some_table - list of all columns from public.some_table
it may be easier to make a video and upload it on any resource?

**Comment by tati-kru** [comment] 2017-08-21 19:05
If it's an actual problem, please send a link to the video with current problem.

**Comment by serge-rider** [comment] 2017-08-25 09:30
Closing. Please reopen if problem still exists.

**Closed by serge-rider** 2017-08-25 09:30 UTC
Labels: question, x:postgresql
