### ISSUE TITLE
High CPU usage when querying

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [serge-rider/dbeaver#1195] opened 2017-01-26 15:52 UTC
I updated dbeaver to the latest version this morning. Then, I started having some high CPU usage (60-70%) randomly on executing queries.

I'm running windows 10 N 64 bit

**Comment by serge-rider** [comment] 2017-01-26 15:55
Duplicate of #1189.
Will be fixed in hotfix version (30.01)

**Closed** 2017-01-26 15:55 UTC
Labels: bug, duplicate

**Comment by gabriele-ricci-kyklos** [comment] 2017-01-26 16:19
I searched issues for 'cpu' to see if somebody else had reported this one, but I searched only for the open issues :D
