### ISSUE TITLE
"View script" button do nothing (as #2337)

### ISSUE THREAD

**Issue by offstate** [serge-rider/dbeaver#2433] opened 2017-10-30 04:58 UTC
The bug is still present as in #2337. And I cannot send the log because there is no records about the bug appears. 
I even recorded the video.
[dbeaver.mp4.zip](https://github.com/serge-rider/dbeaver/files/1425988/dbeaver.mp4.zip)

**Comment by serge-rider** [comment] 2017-10-30 05:26
Please check dbeaver-debug.log file.
There should be something.

**Comment by offstate** [comment] 2017-10-30 06:26
You can see on the video that this file doesn't appear when I press the button. I think DBeaver doesn't treat this as an error

**Comment by offstate** [comment] 2017-10-31 23:11
Today I rebooted my computer and this bug disappeared. I don't know why

**Comment by serge-rider** [comment] 2017-11-01 20:28
Well. As I still can't reproduce it (on Windows, Mac or Ubuntu) I'm closing it.
If anybody will see this again - please reopen (no need to create a new ticket, just reopen this one).

**Closed by serge-rider** 2017-11-01 20:28 UTC
Labels: bug, can't reproduce
