### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by karser** [serge-rider/dbeaver#1141] opened 2017-01-11 10:09 UTC
I use Linux Mint 18.1, the resolution is 3840x2160. DBeaver on HiDPI is usable but sometimes it looks awkward, icons and controls are too small.
![image](https://cloud.githubusercontent.com/assets/1675033/21844057/da9d8cea-d7f5-11e6-9e58-6ad7f5e663c0.png)

![image](https://cloud.githubusercontent.com/assets/1675033/21844156/45cb3d6e-d7f6-11e6-9fdc-e64d01c75ce1.png)

**Comment by serge-rider** [comment] 2017-01-11 10:14
Duplicate of #8 (oldest open issue at the moment)
Will be resolved in 4.0

**Closed by serge-rider** 2017-01-11 10:14 UTC
Labels: duplicate, enhancement

**Comment by serge-rider** [comment] 2017-02-11 09:50
Please test how it works in 4.0 EA version (http://dbeaver.jkiss.org/files/ea/)

**Comment by akoshman** [comment] 2018-11-09 15:01
In DBeaver 5.1.4 this problem is still present

**Comment by elman22** [comment] 2018-12-18 02:48
I'm using flatpak with HiDPI display. With version 5.2.x, I had correctly 2x scaled text and icons were scaled 4x, so they were cut. With version 5.3 nothing is scaled and both text and icons are 1x and therefore small.

**Comment by jjzazuet** [comment] 2019-06-04 06:16
I can also see a mixture of small/large icons and text in version 6.x.x, using Debian buster RC1 under Gnome with 300% display scaling. Thanks!

![Screenshot from 2019-06-04 02-14-19](https://user-images.githubusercontent.com/1002433/58855722-bdc77200-866e-11e9-8b24-a764c2a4406b.png)
