### ISSUE TITLE
Ctrl+hover/click doesn't work when database_name=schema_name

### ISSUE THREAD

**Issue by jk3us** [serge-rider/dbeaver#863] opened 2016-10-19 17:01 UTC
In the SQL Editor, you can hold ctrl and hover over table names, they turn blue and underline, and you can click them to open a tab for that table.  This does not work if the schema name and the database name are the same. Even specifying the database name doesn't work.

`--connect to database "testdb", which has schema "testdb"
select * FROM testdb.test_table;`

Result: Can't ctrl+click testdb.test_table.

Unfortunately, changing the names of the database or schema isn't an option right now.

**Comment by serge-rider** [comment] 2016-10-19 20:27
Actually it a duplicate of #329
Rising priority..

**Closed** 2016-10-20 18:24 UTC
Labels: bug, duplicate
