### ISSUE TITLE
release package(s) broken for macOS

### ISSUE THREAD

**Issue by cederom** [serge-rider/dbeaver#986] opened 2016-11-20 16:06 UTC
Hey! dBeaver Community Edition 3.7.8 package contains broken binary release. macOS 10.12.1 says it's broken and asks to remove it..
<img width="420" alt="screen shot 2016-11-20 at 17 05 38" src="https://cloud.githubusercontent.com/assets/3051832/20464197/a78e191c-af43-11e6-9673-095a7ced0589.png">

**Comment by cederom** [comment] 2016-11-20 16:29
I have noticed that on my macOS 10.12.1 NONE of the release packages will run! Either from DMG nor TAR.GZ. When unpacked in Finder double click always tells the application is broken.

However, running the binary from a shell works fine...

'''
2016-11-20 17:24:15.090 - DBeaver 3.7.8 is starting
2016-11-20 17:24:15.099 - Install path: '/Applications/DBeaver.app/Contents/Eclipse'
2016-11-20 17:24:15.100 - Instance path: 'file:/Users/cederom/.dbeaver/'
2016-11-20 17:24:15.100 - Memory available 155Mb/1820Mb
2016-11-20 17:24:15.123 - Starting RMI server at 30433
2016-11-20 17:24:20.200 - Initialize display
2016-11-20 17:24:24.525 - Initializing DBeaver 3.7.8
2016-11-20 17:24:24.533 - Host plugin: org.jkiss.dbeaver.core.application 3.7.8
2016-11-20 17:24:24.543 - Initialize Core...
2016-11-20 17:24:25.075 - Core initialized (532ms)
2016-11-20 17:24:25.080 - Configure workbench window
2016-11-20 17:24:25.304 - Create actions
2016-11-20 17:24:26.178 - Initialize workbench window
2016-11-20 17:24:26.212 - Error parsing command line: Unrecognized option: --help
2016-11-20 17:24:26.229 - Finish initialization
'''

**Comment by serge-rider** [comment] 2016-11-21 14:16
Duplicate of #95 (check it for workarounds).
Hopefully this problem will be resolved in 4.x version.

**Closed by serge-rider** 2016-11-21 14:16 UTC
Labels: duplicate, question
