### ISSUE TITLE
Very small Fonts and Icons on 4k screens

### ISSUE THREAD

**Issue by abhilash156** [serge-rider/dbeaver#976] opened 2016-11-15 20:04 UTC
![screenshot 2016-11-16 01 28 10](https://cloud.githubusercontent.com/assets/5432718/20321813/c1669666-ab9c-11e6-94bb-d5cca67a4064.png)

**Comment by lBilali** [comment] 2016-11-16 11:33
I think this has to do with eclipse version used by DBeaver.
Because of this, I use DBeaver as an eclipse extension on eclipse 4.6. 
Except the extend/collapse arrow on the tree view, it works great. 
I think, the arrow on the tree view, again is an issue of eclipse because the same issue is on the eclipse preferences window form which has nothing to do with DBeaver

**Comment by serge-rider** [comment] 2016-11-16 21:18
Duplicate of #8 (one of the oldest bugs). Unfortunately Eclipse 4.5 isn't ready for that.
Will see what can be done in 4.6..

**Closed by serge-rider** 2016-11-16 21:18 UTC
Labels: duplicate, feature request
