### ISSUE TITLE
Image for Mac OS is damaged

### ISSUE THREAD

**Issue by Jeetah** [serge-rider/dbeaver#156] opened 2016-01-08 10:51 UTC
OSX says to latest DBeaver app 3.6.8  - "Damaged and should be removed"... (to zipped as well as to img packaged). Tried in Chrome and FF.

**Comment by codebling** [comment] 2016-01-08 20:11
I think that this is an issue with file extensions. 

DBeaver is distributed for Mac as `.dmg` or `.tar.gz`. Please make sure that the files that you download have the `.dmg` or `.tar.gz` extensions (see links below). `.img` and `.zip` are incorrect (DBeaver website incorrectly refers to the archive as "zip archive" when in fact it is a `.tar.gz`. This needs to be corrected on the website @serge-rider).


`.dmg`: DBeaver 3.5.8 Community Edition [here](http://dbeaver.jkiss.org/files/dbeaver-ce-latest-macos.dmg) and Enterprise Edition [here](http://dbeaver.jkiss.org/files/dbeaver-ee-latest-macos.dmg))  
`.tar.gz`: DBeaver 3.5.8 Community Edition [here](http://dbeaver.jkiss.org/files/dbeaver-ce-latest-macosx.cocoa.x86_64.tar.gz) and Enterprise Edition [here](http://dbeaver.jkiss.org/files/dbeaver-ee-latest-macosx.cocoa.x86_64.tar.gz))

**Comment by serge-rider** [comment] 2016-01-10 08:25
It is a duplicate of #95.
Check for workaround in comment.

**Closed by serge-rider** 2016-01-10 08:25 UTC
Labels: duplicate

**Comment by codebling** [comment] 2016-01-10 09:24
@serge-rider it might still be worth changing "zip archive" to "tar.gz archive" on the site.. ?

**Comment by serge-rider** [comment] 2016-01-10 10:10
Good point
