### ISSUE TITLE
Auto complete still not working on double quoted tables and columns

### ISSUE THREAD

**Issue by esulistio** [serge-rider/dbeaver#2261] opened 2017-10-03 17:33 UTC
I reported this on #2191 but was marked as a duplicate of #2169 .
My tables and columns are double quoted, the last version the auto complete on columns is working is 4.1.2 (I'm still using that version because of it).

**Comment by serge-rider** [comment] 2017-10-04 06:10
Looks like 2169 was another issue with autop-complete. Anyhow I can't reproduce problem with quotes.
Please post some example (table DDL) and how to reproduce this problem. 
Thanks.

**Comment by esulistio** [comment] 2017-10-12 18:08
CREATE TABLE dbo."TestTable" (
	"Id" int4 NOT NULL,
	"CategoryId" int4 NOT NULL DEFAULT 0) 
;

When you start typing:
update dbo.t -> (dbo."TestTable" will appear)
But there's no autocomplete on:
update dbo."TestTable" set c -> (I'm expecting "CategoryId", but nothing showing)

Tested on Mac OS X.

**Comment by serge-rider** [comment] 2017-10-12 19:14
Thanks for details.
It'll be fixed in the next version

**Closed** 2017-10-12 19:13 UTC
Labels: bug
