### ISSUE TITLE
MySQL procedure source not loading

### ISSUE THREAD

**Issue by KrissMu** [serge-rider/dbeaver#1997] opened 2017-08-09 12:13 UTC
All is in the title, with last update 4.1.2, the procedure source does not load, I get only the message saying  
--  Loading 'proc_name' source...

and nothing happens.

**Comment by serge-rider** [comment] 2017-08-09 18:13
Duplicate of #1987
Thanks for report anyway

**Closed by serge-rider** 2017-08-09 18:13 UTC
Labels: bug, duplicate
