### ISSUE TITLE
Problem can't start dBeaver.exe

### ISSUE THREAD

**Issue by Wichart009** [serge-rider/dbeaver#509] opened 2016-06-04 16:25 UTC
I got problem after update new version 3.6.8&3.6.9, can't start and got message "An error has occured, see log file.... I attached a log to help me to find out the way to solve the problem, Thanks in advace.

[1465056546822.zip](https://github.com/serge-rider/dbeaver/files/298922/1465056546822.zip)

# #105

**Comment by serge-rider** [comment] 2016-06-04 17:56
Probably a duplicate of #495
Is your Windows profile name has spaces?
If so then you can download EA version.

**Closed** 2016-06-06 09:59 UTC
Labels: duplicate, question

**Comment by Wichart009** [comment] 2016-06-06 16:30
Thanks a lot, I had install 3.6.10 instead and it work now.
