### ISSUE TITLE
Menu and toolbars gets messy after changing database/schema in sql editor [4.2.1]

### ISSUE THREAD

**Issue by isapa1984** [serge-rider/dbeaver#2235] opened 2017-09-29 14:42 UTC
Hi guys, what's up ?

I'm having the following issue with Dbeaver 4.2.1 as described by the pics below.

Dbeaver in its normal state
![dbeaver bug pic1](https://user-images.githubusercontent.com/4210569/31020410-ebeee90c-a500-11e7-8709-bcf4b6c40ff7.jpg)

If i change that field,
![dbeaver bug pic2](https://user-images.githubusercontent.com/4210569/31020462-13226706-a501-11e7-83fc-9a592fd00bb3.jpg)

this happen
![dbeaver bug pic3](https://user-images.githubusercontent.com/4210569/31020465-16aabe96-a501-11e7-9889-ab4500e0e26c.jpg)

placing the mouse over the menus and toolbars just makes things worse
![dbeaver bug pic4](https://user-images.githubusercontent.com/4210569/31020470-1b6b9c02-a501-11e7-8c90-0526e006f182.jpg)

Only restarting makes things back to normal, but changing the field again makes this issue happen. 

what can it be ?

And thank you very much in advance for the support and for this great tool.

UPDATE

This issue also occurs when changing the datasource field.

**Comment by serge-rider** [comment] 2017-09-30 10:59
Looks like some SWT+GTK issue. 
Please recheck this in DBeaver 4.2.2 (it will be based on new SWT E4.7).

**Comment by SylwesterZarebski** [comment] 2017-10-01 11:03
When will be released 4.2.2? I do not see it in updates and/or releases here.

Temporary solution is change tab, which refresh menus and toolbars.

**Comment by serge-rider** [comment] 2017-10-01 12:22
https://github.com/serge-rider/dbeaver/milestones

**Comment by SylwesterZarebski** [comment] 2017-10-01 13:23
I didn't know that, thanks :-).

**Comment by cpum** [comment] 2017-10-02 10:39
I'm having the same issue, more accurately with the "Active datasource"-field, it still persists in 4.2.2. It's not required to actually change the datasource, just opening and closing the dropdown menu is enough to screw up the menu/toolbars.

Before:
![before](https://user-images.githubusercontent.com/20456094/31073738-6c692b6a-a76d-11e7-84a5-238cd510922c.jpg)

After:
![after](https://user-images.githubusercontent.com/20456094/31073743-70aa35e8-a76d-11e7-8af4-7b10299e02b9.jpg)

Best temporary fix for me is resetting perspective via "Window > Reset Perspective". Minimizing and opening Dbeaver window works too, but this doesn't fully recover all menu/toolbar sections.

**Comment by SylwesterZarebski** [comment] 2017-10-02 11:13
For me menus and toolbars are no more vanishing, but there are some other weirdness now - i will report it in another issue.

**Comment by serge-rider** [comment] 2017-10-02 11:44
@cpum Please provide more details about your environment.
OS, screen resolution (4k?), zoom factor.

BTW you could try to reset workspace settings (https://github.com/serge-rider/dbeaver/wiki/Reset-workspace) - sometimes this is a root cause of visual rendering problems.

**Comment by SylwesterZarebski** [comment] 2017-10-03 08:34
After testing my other PCs, it looks like problem exists on Windows 7, and not on Windows 10.

I would like to reset workspace, but have to many keyboard changes and with no export/import option, this is tedious task...

**Comment by cpum** [comment] 2017-10-03 09:17
Resetting my workspace settings unfortunately did't help. I've only deleted the .xmi file, I'm a little opposed to deleting my .metadata folder, I rather live with the rendering problems ^^

My environment:
OS: Windows 10 Enterprise 64-Bit (10.0, Build 14393)
Integrated Graphics: Intel HD Graphics 520
3x Monitors (scaling factor for all 3 of them is 100% in windows):
  1x laptop in docking station (1920x1080)
  2x external monitor (1920x1200, with one of them being my main display)
JRE = 1.8.0_144 (x86)
I also have Eclipse installed, Version: Neon.2 Release (4.6.2)

DBeaver is placed mostly on my main display, the rendering issues persist on any screen though.

Please let me know if you need any further infos.

**Comment by isapa1984** [comment] 2017-10-03 14:13
> BTW you could try to reset workspace settings (https://github.com/serge-rider/dbeaver/wiki/Reset-workspace) - sometimes this is a root cause of visual rendering problems.

After updating Dbeaver to 4.2.2 and trying the solution above the problem still persists but only affects the menu bar. Minimizing and restoring the window fixs but the behaviors occurs when changing either datasource or schema.

**Comment by jeff-bowles** [comment] 2017-10-04 16:53
I have been able to fix the GUI by clicking the "transaction log" box in the toolbar, then closing the transaction log dialog.

**Comment by serge-rider** [comment] 2017-10-12 21:15
Please check how it works in EA version: https://dbeaver.jkiss.org/files/ea

**Comment by SylwesterZarebski** [comment] 2017-10-13 06:46
On Windows 10 it behaves the same like previous 4.2.2 - changing active database sometimes makes most buttons on toolbars grey (only first toolbar has active buttons).
I'll try on Windows 7 later.

**Comment by serge-rider** [comment] 2017-10-14 13:27
Ok, thanks for testing.
In 4.2.3 I'll redo these drop-downs completely (there will be popup dialogs with folders/details).
EA updated.

**Closed** 2017-10-15 16:11 UTC
Labels: bug

**Comment by rafaelsanchezsouza** [comment] 2021-12-27 13:26
Hello!

I'm on Windows 10, working with Dbeaver 21.3.2

I have been using DBeaver with Informix and I'm experiencing exactly the same issues described here in [2322](https://github.com/dbeaver/dbeaver/issues/2322): autocomplete won't work for columns and I have to explicit the schema for tables

Thank you for this amazing tool!
