### ISSUE TITLE
Transaction log does not list Update statement after editing cell

### ISSUE THREAD

**Issue by vascool** [serge-rider/dbeaver#2313] opened 2017-10-11 09:59 UTC
1. Switch to manual commit.
2. Edit a cell in a table data tab and click save.
3. In Query Manager notice a SQL / UTIL line with the Update statement.
4. Open the transaction log and notice it has no entry.

I would expect the same Update statement in Query Manager to be visible in the transaction log. Also the box in toolbar states "None" as it has not counted the statement. Hover the box and it reads "1 total statement 0 modifying statements".
DBeaver 4.2.2.

**Comment by serge-rider** [comment] 2017-10-11 19:42
Seems to be duplicate of #2263
Will be fixed in 4.2.3

**Closed by serge-rider** 2017-10-11 19:42 UTC
Labels: enhancement
