### ISSUE TITLE
Export data - Error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by clydde** [serge-rider/dbeaver#493] opened 2016-05-28 22:08 UTC
DBeaver 3.6.8

MS SQL Server / Export Data
 
SQL Export to SQL INSERT statments:

Error

java.lang.NullPointerException

**Comment by serge-rider** [comment] 2016-05-29 14:41
Duplicate of #480

**Closed by serge-rider** 2016-05-29 14:41 UTC
Labels: duplicate
