### ISSUE TITLE
Wrong column size in table properties

### ISSUE THREAD

**Issue by MauroMichelotti** [serge-rider/dbeaver#888] opened 2016-10-25 07:06 UTC
As you can see in the attached image

![image](https://cloud.githubusercontent.com/assets/23048228/19675936/84171572-9a91-11e6-9e33-aa3d1c3c8748.png)

The column panel in table properties screen shows the column details fully compressed.
I searched in DBeaver properties but I didn't find anything,
I'm using DBeaver (version 3.7.*, 3.7.7 actually) on Ubuntu 14.04.5.

Is it a bug or there is a way to solve ?
Tnx

**Comment by serge-rider** [comment] 2016-10-25 08:33
Seems to be duplicate of #875.
Try to click on column pack button:
![column-list-pack](https://cloud.githubusercontent.com/assets/6398845/19678512/bfd71b10-9aa6-11e6-859b-4bd795955854.png)
Does this help?

**Comment by MauroMichelotti** [comment] 2016-10-25 09:21
Thanks  @serge-rider 
Yes, it's true, the button 'Pack Column' solves the issue.
I sow your code fix, but I actually don't have the time understand if there will be a way to have column always unpacked (I didn't find any option in DBeaver Preferences).
Are you inserting a specific option in Preferences window ?

**Comment by serge-rider** [comment] 2016-10-25 09:39
I think that columns resize problem happens because DBeaver packs columns before actual editor becomes visible.
I've committed a fix which is supposed to resolve this.
I can make EA version to let you test this.

**Comment by MauroMichelotti** [comment] 2016-10-25 13:17
If you have time tu build an EA version, I will test it, yust to confirm the solution.
Thanks

**Comment by serge-rider** [comment] 2016-10-25 13:21
This doesn't  take much time.
EA is here: http://dbeaver.jkiss.org/files/ea/

**Comment by MauroMichelotti** [comment] 2016-10-25 15:13
Great !
It is working well!
For me, your solution works.

**Closed** 2016-10-25 18:42 UTC
Labels: bug
