### ISSUE TITLE
CPU heavy load using autocomplete on 3.8.4 release

### ISSUE THREAD

**Issue by StefanoRomano71** [serge-rider/dbeaver#1190] opened 2017-01-26 10:20 UTC
Hi @serge-rider ,

We are experiencing cpu heavy load on latest release 3.8.4 mostly used with vertica connections and then we need to kill the app to continue to work.

We found for sure the problem on windows with native 6.1.2 driver and on osx with 7.2.3 vertica driver.

The problem happens once you try to autocomplete names sing CTRL+SPACE on osx, on windows we are not sure but seems the same.

Let me know If you need more data and/or which kind of.

SR

**Comment by serge-rider** [comment] 2017-01-26 10:23
Duplicate of #1189.
4.0 release will take much time so I'm going to release hotfix version next Monday.

**Closed by serge-rider** 2017-01-26 10:23 UTC
Labels: bug, duplicate
