### ISSUE TITLE
MongoDB Connection Timeout

### ISSUE THREAD

**Issue by krzysztofantczak** [serge-rider/dbeaver#2017] opened 2017-08-14 00:11 UTC
Hello,

My setup: Dbeaver 4.1.1 EE (Windows 10) / MongoDB 3.2.12 on Ubuntu 16.04 under _local_ Hyper-V Virtual Machine.

Lets start with what i get from dbeaver: 
1)
```
Error connecting to Mongo instance [127.0.0.1]
  com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that 
matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is 
{type=REPLICA_SET, servers=[{address=wslu.sys:27017, type=UNKNOWN, state=CONNECTING, 
exception={com.mongodb.MongoSocketException: wslu.sys}, caused by 
{java.net.UnknownHostException: wslu.sys}}]
```

and

2)
```
Error connecting to Mongo instance [192.168.1.2]
  com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that 
matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is 
{type=REPLICA_SET, servers=[{address=wslu.sys:27017, type=UNKNOWN, state=CONNECTING, 
exception={com.mongodb.MongoSocketException: wslu.sys}, caused by 
{java.net.UnknownHostException: wslu.sys}}]
```

Ad.1)
Odd thing about this part is, i'm trying to connect here, to my mongodb using SSH tunnel, which is set to my local VM ip: 192.168.1.2 and mongo instance on that VM, also with IP 192.168.1.2. However in that error we can see both: 127.0.0.1 AND wslu.sys (vm hostname) - its odd. It should be 192.168.1.2 in both places, shouldn't it?

Ad.2)
This time, i'm trying to connect to my mongo instance DIRECTLY, so by using VM ip 192.168.1.2, but again, we can see here, that somehow its trying to connect to server wslu.sys.

Both, errors are popping up when i'm NOT filling Replica Set field in connection settings. But, when i do (in scenario without ssh tunnel):

```
Error connecting to Mongo instance [192.168.1.2]
  com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that 
matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is 
{type=REPLICA_SET, servers=[]
```

I really don't get it. Any advice?

EDIT:
My RS status output from mongo:
```
/* 1 */
{
    "set" : "rs",
    "date" : ISODate("2017-08-14T00:07:22.324Z"),
    "myState" : 1,
    "term" : NumberLong(68),
    "heartbeatIntervalMillis" : NumberLong(2000),
    "members" : [ 
        {
            "_id" : 0,
            "name" : "wslu.sys:27017",
            "health" : 1.0,
            "state" : 1,
            "stateStr" : "PRIMARY",
            "uptime" : 366700,
            "optime" : {
                "ts" : Timestamp(1502667624, 2),
                "t" : NumberLong(68)
            },
            "optimeDate" : ISODate("2017-08-13T23:40:24.000Z"),
            "electionTime" : Timestamp(1502302543, 1),
            "electionDate" : ISODate("2017-08-09T18:15:43.000Z"),
            "configVersion" : 1,
            "self" : true
        }
    ],
    "ok" : 1.0
}
```

Btw. RoboMongo connects without issues.

**Comment by serge-rider** [comment] 2017-08-14 07:39
Might be correlated with #1874

**Comment by krzysztofantczak** [comment] 2017-08-14 08:05
"mongo - how to use javascript instead of SQL #1874" ? Really? :D

**Comment by serge-rider** [comment] 2017-08-14 08:08
Yes, perhaps something is wrong with auth mechanism. I saw similar problems (timeout errors) on some Mongo deployments and don't yet understand why this is happening.

**Comment by krzysztofantczak** [comment] 2017-08-14 08:21
Ok, so... Is there ANY scenario in which it connects correctly? Like specific mongo version? Or mongo on localhost?

**Comment by serge-rider** [comment] 2017-08-14 08:22
Sure, it works just fine on most Mongo deployments (including clusters).
Easiest way to test it - connect to local Mongo instance.

**Comment by serge-rider** [comment] 2017-08-14 08:24
I see that you are trying to connect with 127.0.0.1 and it fails. But it looks like wslu.sys is configured as cluster auth server or something.

**Comment by krzysztofantczak** [comment] 2017-08-14 08:28
Actually, i'm not using 127.0.0.1 anywere, i'm using 192.168.1.2 (even when using ssh tunnel). It's just dbeaver reporting connection attempt to 127.0.0.1. And my mongo setup is not using any kind of authorization, i'm connecting to it using robomongo without any kind of credentials.

**Comment by serge-rider** [comment] 2017-08-14 08:39
Weird. Do you have any idea what is wslu.sys then?

**Comment by krzysztofantczak** [comment] 2017-08-14 08:42
wslu.sys is my VM's hostname

**Comment by serge-rider** [comment] 2017-08-14 10:00
Then probably the real issue is: `java.net.UnknownHostException: wslu.sys`
For some reason mongo (driver or server?) can't resolve this host.

**Comment by krzysztofantczak** [comment] 2017-08-14 10:04
I guess. So the real question is, why its even trying?

**Comment by krzysztofantczak** [comment] 2017-08-14 16:36
Heh, ok. So it seem, that when i added wslu.sys to windows hosts file as 192.168.1.2 DBeaver connected correctly. But still, why it is even trying to do that is a mystery for me. I NEVER use this hostname on my system, its only internally known to this VM, it was never used outside of it.

**Comment by serge-rider** [comment] 2017-08-14 18:47
Well, I also have no idea why is this happening.
And I can't reproduce such behavior. Perhaps at some point driver converts IP address into host address (for whatever reason).
I'll investigate this a bit more (this shouldn't happen - as RoboMongo doesn't fall into this problem).

**Comment by serge-rider** [comment] 2017-09-02 06:08
After all I think this is a result of some specific network configuration.
Closing.
Please reopen if any additional details will appear.

**Comment by serge-rider** [comment] 2017-09-02 19:02
I totally agree that you should never edit hosts to make some app work.

However I just can't reproduce this and I can't figure out what is happening inside the driver (I need access to the specific environment to debug it - but it is not possible in this case).
DBeaver do not read replicaset address from the server - this happens in Mongo driver itself. 
I've googled quite a lot of similar problem with replicaset resolution in Java driver and there are no solutions so far (without making hosts resolvable from all involved clients/nodes).

Anyway, thanks for report. Probably the same issue will occur in other environments too. And perhaps we'll still be able resolve this one day (or Mongo team will fix the driver).

PS In fact "guys" is just me :)

**Comment by rymsha-phonect** [comment] 2017-11-29 11:51
We got the same issue. the problem for us is that DBeaver is not using SSH tunnel it creates to connect to replicaset members. it tries to connect to them directly and fails because (our mongodb is available only via SSH tunnel)

**Comment by serge-rider** [comment] 2017-12-02 16:35
I'll try something like this - https://blockdev.io/connecting-to-a-mongo-replica-set-via-ssh/
but this doesn't look like a general solution (even without manual patching of hosts file). 

I wondering does anybody succeed in connecting to replicaset using Java driver..

**Comment by serge-rider** [comment] 2017-12-02 16:38
Or maybe we should avoid replica set connect at all.
According to https://jira.mongodb.org/browse/JAVA-2211 this might work (by specifying single target host address).
Maybe we need a special checkbox on connection page or maybe it has to work like this by default (if only one mongo address is specified)

**Comment by serge-rider** [comment] 2017-12-02 21:38
Extra driver property was added. It may help in case of SSH tunnel and replica sets.
You could try it in version 4.3:

![image](https://user-images.githubusercontent.com/6398845/33519946-40ca4374-d7c2-11e7-8809-a0586afcade8.png)

**Comment by serge-rider** [comment] 2017-12-10 09:56
Please try this new config parameter in 4.3.
Reopen if problem persists.

**Closed by serge-rider** 2017-12-10 09:56 UTC
Labels: bug, p:major, question, x:mongo

**Comment by eassymo** [comment] 2018-05-08 16:55
i think we getting timeout error because URL template:
mongo://{host}[:{port}]/{database}

i have seen other clients using 
mongodb://{host}[:{port}]/{database}

but Driver Manager locks MongoDB Edition.

**Comment by serge-rider** [comment] 2018-06-04 10:16
DBeaver doesn't use JDBC driver for Mongo connection. This URL isn't actually used, it is just a brief form of connection info. So this is definitely not the problem which causes timeout.

**Comment by eassymo** [comment] 2018-06-05 17:35
well, what's the reason? if you have a hot fix, please let me know it, thanks.

**Comment by serge-rider** [comment] 2018-06-07 19:52
I can't say because I can't reproduce this. And I don't fully understand the nature of this problem.

Did you try to use some 3rd party SSH client (e.g. Putty) for SSH tunnel?
