### ISSUE TITLE
Feature Request: Add table/data comparison tool (even from different databases or DB types)

### ISSUE THREAD

**Issue by steromano87** [serge-rider/dbeaver#339] opened 2016-04-06 09:48 UTC
Compared to other tools (e.g. JetBrains DataGrip), the table (or data, if the result of a query is available) comparison between two different DB (both same or different type, like Oracle and Sybase) is the only feature missing in DBeaver.
This feature would be very, very useful to compare data in different environments (such as development and test DB) and would represent a real killer feature for DBeaver, compared to other free/open DB GUIs.

**Comment by serge-rider** [comment] 2016-04-06 20:46
Duplicate of #342

**Closed by serge-rider** 2016-04-06 20:46 UTC
Labels: duplicate
