### ISSUE TITLE
Add reconnect button

### ISSUE THREAD

**Issue by infectormp** [serge-rider/dbeaver#2420] opened 2017-10-27 07:48 UTC
In some cases i have error when executing query @ oracle
![image](https://user-images.githubusercontent.com/9958813/32093156-052648b6-bb04-11e7-8f06-2c881cfeb759.png)

![image](https://user-images.githubusercontent.com/9958813/32093108-d183e4aa-bb03-11e7-8c56-4d12cd4bcf21.png)

Please add reconnect button to this dialog.

**Comment by andreynering** [comment] 2017-10-27 12:11
I'd prefer DBeaver to try to reconnect automatically if the connection is closed.

**Comment by serge-rider** [comment] 2017-10-28 21:12
Looks like duplicate of #2201

**Closed** 2017-10-28 21:12 UTC
Labels: duplicate, feature request

**Comment by maxgalbu** [comment] 2017-11-07 11:04
@serge-rider this button was present on 4.1.x, but I think it was removed in 4.2! I rolled back to 4.1 for this reason.

**Comment by serge-rider** [comment] 2017-11-07 18:54
@maxgalbu I don't think so. There is invalidate/reconnect button in 4.2 as well.

**Comment by maxgalbu** [comment] 2017-11-08 10:43
4.1
![dbeaver-reconnect-4 1](https://user-images.githubusercontent.com/1782571/32543626-7135bf7a-c476-11e7-963e-44bafadf6978.png)

4.2
![dbeaver-reconnect-4 2](https://user-images.githubusercontent.com/1782571/32544803-ecf5b536-c479-11e7-8e09-113e3c288d47.png)

**Comment by serge-rider** [comment] 2017-11-08 19:33
Thanks for details. In fact it was a bug in DBeaver error handling.

**Comment by maxgalbu** [comment] 2017-11-15 09:38
Thanks!
