### ISSUE TITLE
Mariadb Binary data displayed  wrongly 

### ISSUE THREAD

**Issue by ahmed89albttashi** [serge-rider/dbeaver#2493] opened 2017-11-08 12:41 UTC
in PHPMYADMIN  all are 1
![image](https://user-images.githubusercontent.com/6708191/32549597-8230c59a-c4a3-11e7-8d92-ce62b7475b85.png)

in dbeaver , 1111111 converted to 1001111

![image](https://user-images.githubusercontent.com/6708191/32549608-8a77dcac-c4a3-11e7-8638-ece5573e1a9f.png)

**Comment by serge-rider** [comment] 2017-11-08 21:10
Can't reproduce this.
In fact DBeaver doesn't convert binary values in a any form.
Please post some SQL example.

**Comment by ahmed89albttashi** [comment] 2017-11-09 05:26
Dear Serge , 
![image](https://user-images.githubusercontent.com/6708191/32589794-131905c2-c530-11e7-9b4d-f0007aa6936c.png)

**Comment by serge-rider** [comment] 2017-11-09 22:22
I mean some example which will show that DBeaver shows value incorrectly (like INSERT+SELECT).
I can see/edit bit sets and they look valid.

**Comment by serge-rider** [comment] 2017-11-23 18:32
Closing as non-reproducible.

**Closed by serge-rider** 2017-11-23 18:32 UTC
Labels: can't reproduce, question
