### ISSUE TITLE
executing a query twice get different resultset when default database is set in connection properties

### ISSUE THREAD

**Issue by verajosemanuel** [serge-rider/dbeaver#1176] opened 2017-01-23 12:41 UTC
Steps to reproduce the issue:

- configure a connection to Mysql server choosing a default database
- open query editor and select a database from "active catalog/schema" dropdown
- write query, get results. Results are from selected database in "active/catalog schema" dropdown (as expected). 
- Ctrl+Enter (execute) again same query. Editor has changed inadvertedly to different catalog/schema. Seems that results are from default database, not the dropdown chosen one. By the way, the Schema dropdown is not changed and keeps showing the previous user selection.

The resultset must be always obtained from chosen database at user selection in "active catalog/schema" dropdown, or the user must be warned some way that the selected database is no longer the active database, otherwise this can lead to a cathastrophic outcome. 

Windows 7, java 32 & 64, Reproduced on Enterprise and Community versions. Mysql

**Comment by serge-rider** [comment] 2017-01-23 12:57
Can't reproduce.
How do you know that "Editor has changed inadvertedly to different catalog/schema"? Are combos in main toolbar update? Any messages?

BTW you can open Query Manager view, enable metadata queries logging (in view config) and see all queries DBeaver executes. For instance for MySQL it executes `USE schema_name` to change current schema.

**Comment by verajosemanuel** [comment] 2017-01-23 15:17
Tested on three different PC, all with windows 7.  I've mentioned Mysql but is MariaDB actually. My bad.

I know editor has changed catalog/schema because the same query (a simple count) delivered different numbers between first and second execution. (confirmed thanks to your suggestion of activating log)

Copied & pasted metadata queries logging following this procedure:

- open dbeaver & configured a connection to a MariaDB server setting "customer_db" as default database.
- restart dbeaver. Change catalog/schema to "brochures_db". Execute _Select count(*) from clients_. 
- Execute same select again. 

Noticed **"use customer_db"** at line 6. That's issued with no human intervention. 

16:10:05	SQL / META	SELECT DATABASE()	2 ms	1	Success	MariaDB - mariadb_server.com	Metadata
16:10:05	SQL / META	SELECT * FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='customer_db' AND TABLE_NAME='clients' ORDER BY ORDINAL_POSITION	20 ms	299	Success	MariaDB - mariadb_server.com	Metadata
16:10:05	SQL / META	SHOW FULL TABLES FROM customer_db LIKE 'clients'	2 ms	1	Success	MariaDB - mariadb_server.com	Metadata
16:10:05	SQL / USER	select count(*) from clients	3 ms	1	Success	MariaDB - mariadb_server.com	Main
16:09:33	SQL / UTIL	use customer_db	82 ms		Success	MariaDB - mariadb_server.com	Metadata
16:09:33	SQL / UTIL	use customer_db	79 ms		Success	MariaDB - mariadb_server.com	Main
16:09:33	SQL / META	SELECT DATABASE()	74 ms	1	Success	MariaDB - mariadb_server.com	Metadata
16:09:33	SQL / META	SELECT * FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='brochures' AND TABLE_NAME='clients' ORDER BY ORDINAL_POSITION	115 ms	299	Success	MariaDB - mariadb_server.com	Metadata
16:09:33	SQL / USER	select count(*) from clients	10 ms	1	Success	MariaDB - mariadb_server.com	Main
16:09:24	SQL / META	SHOW FULL TABLES FROM brochures	8 ms	67	Success	MariaDB - mariadb_server.com	Metadata
16:09:19	SQL / UTIL	use brochures	3 ms		Success	MariaDB - mariadb_server.com	Metadata
16:09:19	SQL / UTIL	use brochures	3 ms		Success	MariaDB - mariadb_server.com	Main
16:09:01	SQL / META	SELECT DATABASE()	2 ms	1	Success	MariaDB - mariadb_server.com	Metadata
16:09:01	SQL / META	SELECT * FROM information_schema.SCHEMATA	26 ms	57	Success	MariaDB - mariadb_server.com	Metadata
16:09:01	SQL / META	SHOW COLLATION	9 ms	202	Success	MariaDB - mariadb_server.com	Metadata
16:09:01	SQL / META	SHOW CHARSET	4 ms	39	Success	MariaDB - mariadb_server.com	Metadata
16:09:01	SQL / META	SHOW ENGINES	4 ms	10	Success	MariaDB - mariadb_server.com	Metadata
16:09:01	SQL / META	-- Load type info	2 ms	40	Success	MariaDB - mariadb_server.com	Metadata

**Comment by serge-rider** [comment] 2017-01-23 15:44
Seems to be a bug in active schema detection.  Still can't reproduce but now I have a clue.

Try to disable "Refresh active schema after SQL execution" option:
![image](https://cloud.githubusercontent.com/assets/6398845/22210701/c0f82d36-e19b-11e6-9ea0-8f3a7eb10685.png)

**Comment by serge-rider** [comment] 2017-01-23 16:04
Will be fixed in the next version, thanks for report.
For now you can use workaround suggested above.

**Comment by verajosemanuel** [comment] 2017-01-23 18:08
Thanks serge

Your workaround solves the issue.
not setting a default database when creating a connection seems to work too.

Great Work!!!

**Closed** 2017-01-24 16:54 UTC
Labels: bug
