### ISSUE TITLE
Can't open a table and read its data

### ISSUE THREAD

**Issue by Aetherus** [serge-rider/dbeaver#2214] opened 2017-09-27 04:40 UTC
Community Edition v4.2.1 Debian can no longer open a table by double-clicking it in the navigator. It just expands the node in the navigator. v4.2.0 is fine.

**Comment by serge-rider** [comment] 2017-09-27 08:03
Duplicate of #2160 
Old default behavior will be returned in 4.2.2

**Closed by serge-rider** 2017-09-27 08:03 UTC
Labels: duplicate, question
