### ISSUE TITLE
GTK issue?

### ISSUE THREAD

**Issue by mdontsov** [serge-rider/dbeaver#1213] opened 2017-02-01 11:24 UTC
DBeaver 3.8.3 and looks like GTK issue is back
Database Navigator got completely freezed upon connect

![selection_001](https://cloud.githubusercontent.com/assets/16574445/22504905/55233ffa-e881-11e6-869a-3a1a95beccf1.png)
![screenshot from 2017-02-01 13-18-00](https://cloud.githubusercontent.com/assets/16574445/22504912/5a5f4950-e881-11e6-93d2-6eabf05f0675.png)

!SESSION 2017-02-01 13:11:14.782 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2017-02-01 13:13:33.756
!MESSAGE Application error
!STACK 1
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.IllegalStateException: No workbench window)
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:138)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3794)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3433)
	at org.eclipse.swt.widgets.Display.release(Display.java:3485)
	at org.eclipse.swt.graphics.Device.dispose(Device.java:248)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:226)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
Caused by: java.lang.IllegalStateException: No workbench window
	at org.jkiss.dbeaver.core.DBeaverUI.getActiveWorkbenchWindow(DBeaverUI.java:175)
	at org.jkiss.dbeaver.ui.perspective.DataSourceManagementToolbar$2.run(DataSourceManagementToolbar.java:412)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	... 18 more

!ENTRY org.eclipse.e4.ui.workbench 4 0 2017-02-01 13:13:33.820
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.eclipse.e4.core.di.InjectionException: org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:898)
	at org.eclipse.e4.core.internal.di.InjectorImpl.disposed(InjectorImpl.java:398)
	at org.eclipse.e4.core.internal.di.Requestor.disposed(Requestor.java:148)
	at org.eclipse.e4.core.internal.contexts.ContextObjectSupplier$ContextInjectionListener.update(ContextObjectSupplier.java:78)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:111)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.handleInvalid(TrackableComputationExt.java:74)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.dispose(EclipseContext.java:174)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.dispose(EclipseContext.java:159)
	at org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.dispose(EclipseContextOSGi.java:106)
	at org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.bundleChanged(EclipseContextOSGi.java:139)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:902)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:165)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:75)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:67)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:102)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:466)
	at org.eclipse.osgi.container.Module.doStop(Module.java:624)
	at org.eclipse.osgi.container.Module.stop(Module.java:488)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:186)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:159)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.SWT.error(SWT.java:4377)
	at org.eclipse.swt.widgets.Display.error(Display.java:1186)
	at org.eclipse.swt.widgets.Display.checkDevice(Display.java:765)
	at org.eclipse.swt.widgets.Display.removeFilter(Display.java:3703)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.contextDisposed(MenuManagerRenderer.java:338)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	... 23 more

!ENTRY org.eclipse.core.jobs 2 2 2017-02-01 13:13:34.448
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.model.navigator.DBNModel$1

!ENTRY org.eclipse.core.jobs 2 2 2017-02-01 13:13:34.449
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.model.navigator.DBNModel$1

!ENTRY org.eclipse.core.jobs 2 2 2017-02-01 13:13:34.450
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.model.navigator.DBNModel$1

!ENTRY org.eclipse.core.jobs 2 2 2017-02-01 13:13:34.450
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.model.navigator.DBNModel$1

!ENTRY org.eclipse.core.jobs 2 2 2017-02-01 13:13:34.450
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.model.navigator.DBNModel$1

**Comment by mdontsov** [comment] 2017-02-01 11:27
Had to delete .metadata folder in order to get rid of the problem

**Comment by serge-rider** [comment] 2017-02-02 12:01
Weird.
Can you upgrade to 3.8.5? (No need to delete workspace or .metadata)

**Comment by mdontsov** [comment] 2017-02-02 12:11
Yes, already did that. I managed to get caught that issue by clicking 'Invalidate/Reconnect' when my Dbeaver being idle long enough to shutdown an existing DB connection

**Comment by serge-rider** [comment] 2017-02-02 12:49
So, does 3.8.5 works Ok or you still have this issue with query execution?

**Comment by serge-rider** [comment] 2017-02-12 09:15
Closing as non-reproducible,
Big number of GTK issues will be solved in 4.0 (because of migration to new Eclipse version).

**Closed by serge-rider** 2017-02-12 09:15 UTC
Labels: question
