### ISSUE TITLE
Cannot create table from navigation tree

### ISSUE THREAD

**Issue by sirber** [serge-rider/dbeaver#2604] opened 2017-12-05 19:15 UTC
on dBeaver 4.2.5, java 8, windows 10

![image](https://user-images.githubusercontent.com/3911428/33625752-9f75956c-d9c6-11e7-9bd8-88841fa1f5e1.png)

![image](https://user-images.githubusercontent.com/3911428/33625797-c3918672-d9c6-11e7-9dbb-bdcdd4c03b0e.png)

related to bug #2588 ?

**Comment by sirber** [comment] 2017-12-05 19:17
Same if I use "Create table" in the database tab, in the table list

**Comment by sirber** [comment] 2017-12-05 19:18
Restarted dBeaver. Create new table from database opened tab works now, I get the interface for a new table.

**Comment by sirber** [comment] 2017-12-05 19:21
I get the popup when I add a field, constraints, etc.

**Comment by sirber** [comment] 2017-12-05 19:34
Went down to 4.2.2, cannot create a table.

**Comment by serge-rider** [comment] 2017-12-06 06:22
Duplicate of #2588 (actually this bug is not so easy to catch, it is very dependent on local machine/OS).
I guess some 4.1.x should work.

BTW 4.3 (CE) will be released this Friday.

**Comment by sirber** [comment] 2017-12-06 12:39
Alright, will test 4.3 when it's out. Unless you want me to test a pre-release?

**Comment by sirber** [comment] 2017-12-06 12:43
4.1.3 is no go.

**Comment by sirber** [comment] 2017-12-06 12:46
4.0.0:

![image](https://user-images.githubusercontent.com/3911428/33662362-87350c88-da59-11e7-8231-1808e7935733.png)

**Comment by serge-rider** [comment] 2017-12-06 13:40
That's crazy :)
The most surprising part of this is that you are the first one who tuck into this.

**Comment by sirber** [comment] 2017-12-06 13:42
Yeah I'm lucky... 

Stupid question: should I empty "C:\Program Files\DBeaver" when I upgrade or downgrade?

**Comment by sirber** [comment] 2017-12-06 13:43
more infos:

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

windows 10 v1710

**Comment by serge-rider** [comment] 2017-12-06 22:56
> Stupid question: should I empty "C:\Program Files\DBeaver" when I upgrade or downgrade?

No, you shouldn't. Installer will do this for you.
Java is also included in Installer so you don't need to care about that.

Standard workaround for this problem is to open editor (double-click on "Tables") and then create table using editor context menu.

**Comment by serge-rider** [comment] 2017-12-06 22:57
Please check this in EA version: https://dbeaver.jkiss.org/files/ea/

**Comment by sirber** [comment] 2017-12-07 13:13
Seems fixed in 4.3.0! 👯‍♂️

**Comment by serge-rider** [comment] 2017-12-07 14:33
Great, thanks for testing

**Closed by serge-rider** 2017-12-07 14:33 UTC
Labels: bug, duplicate

**Comment by sirber** [comment] 2017-12-07 14:35
Thank you for your time and efforts!
