### ISSUE TITLE
Explain Plan not working in Oracle (but still working with other DB, such as MySQL)

### ISSUE THREAD

**Issue by steromano87** [serge-rider/dbeaver#340] opened 2016-04-06 10:11 UTC
If you try to execute an explain plan in an Oracle connection, the explain plan is not displayed in Explain Plan panel. However, using another DB that supports explain plan (such as MySQL), it works normally.

Here are listed all the grants for the given user from the USER_SYS_PRIVS table:

| PRIVILEGE | ADMIN_OPTION |
| ------------- | ------------- | ----- |
| ADVISOR | NO |
| EXECUTE ANY PROCEDURE | NO |
| UNLIMITED TABLESPACE | NO |
| ALTER ANY PROCEDURE | NO |
| SELECT ANY DICTIONARY | NO |

**Comment by serge-rider** [comment] 2016-04-06 11:56
Can't reproduce that.
Please post error with stacktrace

**Comment by serge-rider** [comment] 2016-04-06 20:47
Duplicate of #341

**Closed by serge-rider** 2016-04-06 20:47 UTC
Labels: can't reproduce, duplicate

**Comment by steromano87** [comment] 2016-04-08 07:59
Hi Serge,

I managed to reproduce the bug.
Here you can find the output of the query log for the explain plan not being generated:

!ENTRY org.jkiss.dbeaver.core 1 62 2016-04-08 09:53:10.553
!MESSAGE DELETE FROM PLAN_TABLE WHERE STATEMENT_ID='imrf0yah49g4d0' 
!SUBENTRY 1 org.jkiss.dbeaver.core 1 0 2016-04-08 09:53:10.558
!MESSAGE SUCCESS [-1]

!ENTRY org.jkiss.dbeaver.core 1 64 2016-04-08 09:53:10.558
!MESSAGE EXPLAIN PLAN 
SET STATEMENT_ID = 'imrf0yah49g4d0'
INTO PLAN_TABLE
FOR select * from STRAUT.DOM_TIPO_OPERZ_DEVC
!SUBENTRY 1 org.jkiss.dbeaver.core 1 0 2016-04-08 09:53:10.577
!MESSAGE SUCCESS [-1]

!ENTRY org.jkiss.dbeaver.core 1 66 2016-04-08 09:53:10.577
!MESSAGE SELECT * FROM PLAN_TABLE WHERE STATEMENT_ID='imrf0yah49g4d0' ORDER BY ID
!SUBENTRY 1 org.jkiss.dbeaver.core 1 0 2016-04-08 09:53:10.588
!MESSAGE SUCCESS [0]
