### ISSUE TITLE
ArrayIndexOutOfBoundsException when trying to create function

### ISSUE THREAD

**Issue by montao** [serge-rider/dbeaver#2106] opened 2017-08-30 11:19 UTC
![arrayindexoutofboundsexception](https://user-images.githubusercontent.com/51189/29870008-c2dbfd1c-8d85-11e7-8d2b-fb605759d1c5.png)

**Comment by serge-rider** [comment] 2017-08-30 21:41
Duplicate of #900

**Closed by serge-rider** 2017-08-30 21:41 UTC
Labels: duplicate, question
