### ISSUE TITLE
No real procedure parameters names in PostgreSQL

### ISSUE THREAD

**Issue by elring** [serge-rider/dbeaver#1082] opened 2016-12-19 15:37 UTC
In detail of PostgreSQL procedure I only see names of procedure parameters like $1, $2, $3 etc. - no real names (server version 9.3 and 9.5). Server supports named arguments since PorgreSQL 7.0, so this is no problem.

Is there some settings or hidden PostgreSQL driver property to allow real parameter names?

**Comment by serge-rider** [comment] 2016-12-19 15:44
Duplicate of #1081

**Comment by serge-rider** [comment] 2016-12-19 15:46
Will investigate PG meta catalog for possibility to obtain procedure parameter names.

**Comment by serge-rider** [comment] 2016-12-20 23:08
Well, generally DBeaver supports parameter names:
![default](https://cloud.githubusercontent.com/assets/6398845/21371344/de292570-c721-11e6-8747-14f55af0eb02.png)

All system procedures do not have parameter names in system catalog. Custom procedures should have them. If you have a SQL snipped (procedure DDL) which reproduces this problem - please post it.

**Comment by elring** [comment] 2016-12-21 07:54
I have this problem in all my functions (language SQL or PL/PGSQL) - look at screenshot.
![screen](https://cloud.githubusercontent.com/assets/24586123/21380855/3dd8f4f6-c758-11e6-94f8-8dd9c971ffa8.png)
Few minutes later - I see the problem here. In source code of your PostgreSQL plugin (plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/PostgreProcedure.java) at line 123 you are deciding if procedure has allArgTypes. If true, everything is ok (with real procedure names), if false you only fill "$"(i+1) name. But according to PostgreSQL documentation https://www.postgresql.org/docs/9.5/static/catalog-pg-proc.html this field is null in case no out parameters, so this is the problem. You have out parameters in your test procedure (I see it in screenshot), I don't.

So fix is to implement names false section, something like.

At beginning of false block: 
```String[] argNames = JDBCUtils.safeGetArray(dbResult, "proargnames");```
In loop:
```String paramName = argNames == null || argNames.length < inArgTypes.length ? "$" + (i + 1) : argNames[i];```

**Comment by serge-rider** [comment] 2016-12-21 09:43
You are right.
Fix in the next version.

**Closed by serge-rider** 2016-12-21 09:43 UTC
Labels: can't reproduce, feature request
