### ISSUE TITLE
Cassandra: dbeaver displays the day prior for all date columns in results.

### ISSUE THREAD

**Issue by revelation1** [serge-rider/dbeaver#1405] opened 2017-03-07 19:02 UTC
Version 3.85. Notice I query for the July 3 and Dbeaver displays July 2!

`CREATE KEYSPACE test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;;

CREATE TYPE test.udt_citystate (
    city text,
	state text
);

CREATE TABLE test.people (
    Name text,
    date date,
    citystate FROZEN<udt_citystate>,
    PRIMARY KEY (Name, date));

insert into test.people (Name,date,citystate) values ('FRED','2017-07-03',{city:'Houston',state:'Texas'});

select * from test.people where name = 'FRED' and date = '**2017-07-03**';`

![image](https://cloud.githubusercontent.com/assets/7517411/23673027/c0623f50-033e-11e7-9035-9c45ad55d2de.png)

**Comment by serge-rider** [comment] 2017-03-10 13:35
Can't reproduce in 4.0.2. Probably this was auto-fixed by some other issue resolution.

**Closed by serge-rider** 2017-03-10 13:35 UTC
Labels: bug
