### ISSUE TITLE
Teradata UTF8 Struggles

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#511] opened 2016-06-06 18:33 UTC
I'm trying to return unicode strings with my teradata connection and I can't seem to get it to work.

the following query works in oracle, postgres, & mysql but not teradata. I've successfully gotten this query to work in aquadata studio (and have copied all of the config options to dbeaver but still no luck).

Is it somehow related to #499, #502, or #505?

Dbeaver - Teradata
![image](https://cloud.githubusercontent.com/assets/9246654/15833080/d1d5f4f8-2bd9-11e6-9e47-7eb0a7c52adc.png)

Aquadata - Teradata
![image](https://cloud.githubusercontent.com/assets/9246654/15833155/50cd2ff6-2bda-11e6-85b9-bc3323ce0c6d.png)

Dbeaver - Postgres
![image](https://cloud.githubusercontent.com/assets/9246654/15833211/a62bf91e-2bda-11e6-8b4f-4870dc681217.png)

**Comment by serge-rider** [comment] 2016-06-06 18:42
Well, JDBC URLs are a bit different in AquaData and in DBeaver.
`,?CHARSET=UTF8` vs `,CHARSET=UTF8`
Maybe its the problem? Please check, I can't validate this.

**Comment by r-richmond** [comment] 2016-06-06 20:04
good catch... i would have had to hang my head in shame if that was the issue.... however after fixing that i'm still having the issue

![image](https://cloud.githubusercontent.com/assets/9246654/15835753/50aac144-2be6-11e6-9ff1-1dc007f98a06.png)

**Comment by serge-rider** [comment] 2016-06-06 20:38
There was a very similar issue:  #402
It was solved by setting CHARSET parameter in the driver properties tab but not by modifying URL. Although there shouldn't be any difference.
Note that connection caches generated JDBC URL in the persisted config. It is not enough to restart DBeaver, you have to change anything in connection properties to generate new URL. Doesn't sound good, maybe this behavior should be qualified as a bug..

**Comment by r-richmond** [comment] 2016-06-06 21:02
I had tried that previously and was unsuccessful 

and in fact I've created a brand new driver instance to test it (as well as modifying the original) with no luck...

![teradata_utf8](https://cloud.githubusercontent.com/assets/9246654/15837696/2addb206-2bef-11e6-948d-b0452b691d05.gif)

**Comment by serge-rider** [comment] 2016-06-06 21:39
Well, have no other ideas so far.
What's your Teradata server/driver versions?

**Comment by r-richmond** [comment] 2016-06-06 22:21
server: 15.00.03.03
driver: 15.10, 15.0 (I've tried several including the ones that worked with Aqua Data studio)

yea I can't figure out what it could be.. I thought at first it was a config issue but after I duplicated the config settings from aquadata i was hoping it was a client side fix for dbeaver.

Are there any other log files I can provide / Settings I can provide that would help you debug/narrow down the issue further?

**Comment by serge-rider** [comment] 2016-06-07 07:40
Maybe this is a duplicate of #511. 
Please check last comment there.

**Comment by r-richmond** [comment] 2016-06-07 16:18
Ok I have some more clues... hopefully anyways..

I tried downloading ea version and running `dbeaver.exe -vmargs -Dfile.encoding=UTF8` no luck

After that i re-installed 3.6.10

I tried to export results from query (format json) to see how that would do.

first attempt
```
{
"with test as (
select '????' as "label"
)
select * from test": [
	{
		"label" : "????"
	}
]}
```
at which point i noticed that encoding wasn't set to utf8... (I think it defaulted to this but i'm not sure)
![image](https://cloud.githubusercontent.com/assets/9246654/15865244/ea2b380a-2c8e-11e6-9617-bea5a416d8d4.png)

anyways changed the encoding to utf8 and then got this result (sql script was at least encoded properly)

```
﻿{
"with test as (
select 'ŔİĆǶ' as "label"
)
select * from test": [
	{
		"label" : "????"
	}
]}
```

anyways the next thing i tried was connecting using the odbc bridge and found out that odbc bridge connection returns the expected results

![image](https://cloud.githubusercontent.com/assets/9246654/15865392/6947ad44-2c8f-11e6-89a3-9d0e4e566053.png)

**Comment by r-richmond** [comment] 2016-06-07 16:31
also just fyi this bug is present in version 3.5.9 (so it isn't the result of a recent change)

**Comment by serge-rider** [comment] 2016-06-07 17:12
One note - you don't need to set file.encoding in command line (in EA version). It was a recommendation for some weird JDBC driver which, probably, uses local file encoding to decode strings. In version 3.6.9 (I guess) I've explicitly set file.encoding to utf-8 (to resolve #499 issue). In EA I replaced this with Eclipse specific configuration.

Just try EA with default options. It should work with Teradata driver exactly as DBeaver versions before 3.6.9. But if this issue happens in 3.6.8 and earlier then this is something very different.

ODBC bridge works because it encodes/decodes strings differently (using standard network rules I guess, maybe in UCS2 or something).

**Comment by r-richmond** [comment] 2016-06-07 18:00
running EA with no command line arguments didn't resolve the issue. 

I confirmed that the bug also existed in 3.6.8

**Comment by serge-rider** [comment] 2016-06-07 18:14
Well, I think I need to test against real Teradata server.
Unfortunately that's not easy. Teradata Express VMWare image >7gb. And I'm not even sure what version to download.
Will try it a little later..

**Comment by r-richmond** [comment] 2016-06-07 20:36
ok so querying teradata's session info and comparing my aquadata session to my dbeaver session i'm noticing a key difference

Dbeaver `JAVA=1.8.0_77;MEM=7596408832;TZ=-08:00;CID=33E47815;TYPE=DEFAULT;GOV=Y;SCS=ASCII;CCS=ASCII;LOB=Y;SIP=Y;TM=T;ENC=N;SE=N;RED=3,3;`

Aquadata 
`JAVA=1.7.0_60;MEM=954728448;TZ=-08:00;CID=33932f51;TYPE=DEFAULT;GOV=Y;SCS=UTF8;CCS=UTF8;LOB=Y;SIP=Y;TM=T;ENC=N;SE=N;RED=3,3;`

**Comment by serge-rider** [comment] 2016-06-07 20:49
Ok. Let's then go to the beginning. Add CHARSET=UTF8 in the URL template.
Then connect.
Then open Properties view and click on the connection. See server URL property (you can copy it).
This is the URL DBeaver uses to connect. Is there any difference between DBeaver and AquaData URLs?

**Comment by r-richmond** [comment] 2016-06-07 21:26
How are the properties intended to behave?

if i have a driver template like `jdbc:teradata://{host}/DBS_PORT=1025,CHARSET={charset}`
and i have a connection_properties.driver_property.user_property = {name:charset,value:'utf16'} will the final connection be `jdbc:teradata://{host}/DBS_PORT=1025,CHARSET=utf9`? 

or

do user_properties just append themselves to the connection url?

**Comment by serge-rider** [comment] 2016-06-08 10:19
Connection properties usually aren't present in URL. They are passed as additional parameters during connection.
Maybe Teradata driver has some bug and all properties must be in the URL, I'm not sure about that.
Anyhow DBeaver doesn't support properties->URL substitution. It understands only {database}, {host}, {port} and a couple of other URL variables. And I don't think that adding such support makes sense (driver MUST understand properties in the standard JDBC way). If it is not then you can put them in URL as a workaround.

But refreshing connection URL after driver settings changes makes sense. I'll make a separate issue for that.

**Closed by serge-rider** 2016-06-08 10:19 UTC
Labels: question
