### ISSUE TITLE
Dbeaver not getting records change on Table

### ISSUE THREAD

**Issue by acsdev** [serge-rider/dbeaver#2070] opened 2017-08-23 19:16 UTC
Good afternoom,
There is a strange behavior with my connections.
This happens following this steps. 

1. Connecting on database
2. Use SELECT command to query some data.
3. Use an application to create or to update a record.
4. Execute select from step 2 again. (You will observe that the result of SQL query remais the same)
5. Disconnect on database
6. Reconnect on database
7. Execute select from step 2 again (You will observe that the result of SQL now has the right information)

This behavior starts with the last version I have updated.
I am using Oracle database connecting with service name.

I'll be greatfull for any help,
Thanks

**Comment by carlosspohr** [comment] 2017-08-23 19:41
Hi there,

It seems from uncommitted data, are you using transaction control under your connection on DBeaver and/or on your application?
Changes only will be visible after they're committed.

**Comment by acsdev** [comment] 2017-08-23 19:52
There is no Repeatable read option in my DBeaver.

I very sure that all data was already committed and DBeaver just show the correct data after reconnect.

**Comment by syerad** [comment] 2017-08-28 11:31
Same for me! Most of the times I'm not getting the actual data from the database except I'm doing a manual reconnect. This problem is there since I'm Using Dbeaver (~ 6 Months).
To be sure that the correct data are displayed, I have to reconnect manually.

System: Linux (Ubuntu 16.04)

**Comment by acsdev** [comment] 2017-08-28 12:41
Recently, I found something that helps. We do not need reconnect to see correct data, you just have to close all tabs e open again.

It is not the best way, at least we do not have to reconnect al the time.

**Comment by syerad** [comment] 2017-08-29 08:22
Hmm, thanks for your help. But nevertheless it's a big issue because we can't be sure if the displayed data is up to date or not.

**Comment by serge-rider** [comment] 2017-08-30 22:18
In fact DBeaver doesn't have any kind of data cache so I still think it is related to transactions.

Does this problem exists in auto-commit mode?

**Comment by acsdev** [comment] 2017-08-31 13:52
Serge,
I could not verify if that happens with auto-commit because I am not use this feature but I am sure that is not related to transactions.

You see, I have a Java App that changes information in database, after the java application ends I just see the new information on DBeaver after reconnect or after close and reopen an SQL editor.

Yesterday, I did something and I think that I won't have this problem anymore. I exported all my connections, close deaver, deleted the folder $HOME/.dbeaver4, reopen dbeaver and imported the connections that I had exported. After that, the problem stops to occur. I hope that stays this way.

**Comment by serge-rider** [comment] 2017-08-31 18:23
> You see, I have a Java App that changes information in database, after the java application ends I just see the new information on DBeaver after reconnect or after close and reopen an SQL editor.

This makes me think that this is still related to transactions. Because reconnect/DBeaver restart ends transaction in DBeaver and it can see changes made by other applications (this actually depends on database and transaction isolation level).

You could try to turn autocommit on or just perform manual commit or rollback operation (in the main toolbar) to see changes made by other applications.

**Comment by tati-kru** [comment] 2017-09-17 17:45
It looks like this question was solved. It will be closed. If you think that it is actual just let us know.

**Closed by tati-kru** 2017-09-17 17:45 UTC
Labels: question

**Comment by andreav** [comment] 2018-04-04 11:40
Hi,
I'm experimenting same behaviour on version: 5.0.1 against MySQL dataabse.

I'm executing the query using DBeaver but modifying it by HeidiSQL.
Tab is configured for "Repeatable Read".

If I close all tabs, then re-issue the query, data is correctly displayed updated.

By the way,
DBeaver is a great!

**Comment by orbanbalage** [comment] 2018-09-22 02:39
Wow,

I've recereated the .dbeaver4 directory, and copied over only the connections & project.
The GUI is MUCH snappier and responsive. (also many errors about missing icons are gone)

However the commit is again lost/missing after restart.
Steps:
- set to manual commit
- execute INSERT INTO (...) query
- during query execution this popup appears:
![image](https://user-images.githubusercontent.com/285574/45912329-d3b63f00-be1f-11e8-9b41-44f322710007.png)
- statistic page shows query completed, updated 7 rows
- observe the Commit button is greyed out (maybe the DB forces the commit?)
- also observe the query is green and Result = Success in the Query Manager
- switch to another tab and run a SELECT to verify the inserted data is there

- restart DBeaver -> data is not there. -.-

**Comment by orbanbalage** [comment] 2018-09-22 02:55
It is always reproduceable.
I have created a new connection, and there it is not reproducible. maybe it's a good idea to start with a fresh profile after the major Eclipse version update...

**Comment by orbanbalage** [comment] 2018-09-22 16:50
compared the entries in .dbeaver-data-sources.xml,
and the only difference seems to be:
`<property name="autocommit" value="true"/>`
that might be causing some unexpected state

**Comment by orbanbalage** [comment] 2018-09-24 19:27
if the connection type is changed to "Development", then the commit is not lost with the existing DB connection
but with the new connection it doesn't make a difference, it can be set to "Production" and the commit is there (after restarting DBeaver)

**Comment by serge-rider** [comment] 2018-10-01 20:51
@orbanbalage I think this deserves a separate ticket. 
BTW is this Invalidate notification happens always? Usually it i shown when connection was broken by some reason (and transaction will be obviously rolled back - this might be the reason why data is not committed)

**Comment by sdklab007** [comment] 2025-03-27 05:24
I was facing the same issues. I was thinking may be AWS RDS is doing something. 

When I turned on the auto-commit, it got resolved. 

<img width="339" alt="Image" src="https://github.com/user-attachments/assets/d2d01a17-bed0-4117-90dc-8c7a35e21836" />
