### ISSUE TITLE
Unable to create new MySQL table 

### ISSUE THREAD

**Issue by gloss82** [serge-rider/dbeaver#1364] opened 2017-02-28 13:40 UTC
When I am click "Create table" in popup menu, using MySQL or MariaDB, following error has appeared.

![2017-02-28-screenshot](https://cloud.githubusercontent.com/assets/14799396/23407254/e3ea872a-fde4-11e6-8885-368429f04f66.png)

Log contents:

```
!ENTRY org.jkiss.dbeaver.model 4 0 2017-02-28 18:35:13.892
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at java.util.ArrayList.<init>(ArrayList.java:177)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLTableBase.getAttributes(MySQLTableBase.java:98)
	at org.jkiss.dbeaver.ext.mysql.edit.MySQLTableManager.getChildObjects(MySQLTableManager.java:146)
	at org.jkiss.dbeaver.ext.mysql.edit.MySQLTableManager.getChildObjects(MySQLTableManager.java:1)
	at org.jkiss.dbeaver.model.impl.sql.edit.SQLStructEditor.createObjectReferences(SQLStructEditor.java:82)
	at org.jkiss.dbeaver.model.impl.sql.edit.SQLObjectEditor.createNewObject(SQLObjectEditor.java:94)
	at org.jkiss.dbeaver.model.impl.sql.edit.SQLObjectEditor.createNewObject(SQLObjectEditor.java:1)
	at org.jkiss.dbeaver.ui.actions.navigator.NavigatorHandlerObjectCreateBase$CreateJob.run(NavigatorHandlerObjectCreateBase.java:126)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by serge-rider** [comment] 2017-02-28 13:45
Duplicate of #1310.

**Closed by serge-rider** 2017-02-28 13:45 UTC
Labels: bug, duplicate
