### ISSUE TITLE
procedure names are blank in MSSQL databases

### ISSUE THREAD

**Issue by michimartini** [serge-rider/dbeaver#780] opened 2016-09-28 09:19 UTC
This is a regression.
Names of stored procedures are just blank - they can be doubleclicked though and open normally in a separate tab.
Does not happen with MySQL databases.
screenshot: https://drive.google.com/open?id=0B4Rc_tTmMIgJV3dPVjYteDhQTk0

**Comment by serge-rider** [comment] 2016-09-28 09:56
I think this is a duplicate of #774.
Thanks for report anyway.

**Comment by michimartini** [comment] 2016-09-28 13:45
yes, obviously a duplicate, could not find #774 because it used  a nondescriptive subject line

**Comment by kalerovic** [comment] 2016-10-24 11:12
Hi serge-rider, 
sorry but I must disagree. I think this is not a duplicate of #774. #774 is closed and was included at milestone v3.7.6 but I have the very same problem michimartini reported in v3.7.6. 
This morning I've just tested v3.7.7 and the problem is still there. 
I'm using v3.7.7 and sqlserver 2016

**Comment by serge-rider** [comment] 2016-10-24 12:31
Can't reproduce that.
Do you use standalone version or Eclipse plugin?
CE or EE?
What OS?
Also you can check product version in Installation Details (in main menu Help).

**Comment by serge-rider** [comment] 2016-10-24 13:43
Yep, I've reproduced that.

**Comment by serge-rider** [comment] 2016-10-24 14:03
Yes, that was a very different problem.
Will be fixed in the next version, thanks for bringing this up.

**Closed** 2016-10-24 22:45 UTC
Labels: bug

**Comment by kalerovic** [comment] 2016-10-25 11:00
perfect. That was really fast 👍
