### ISSUE TITLE
Strange encoding in 'data view' tab

### ISSUE THREAD

**Issue by vckbarth** [serge-rider/dbeaver#494] opened 2016-05-30 11:43 UTC
Hello,

After testing DBeaver 3.6.8 (standalone) I've encountered very strange encoding issue of 'data view' tab durning table editing. It seems to encode result sets data always with ISO-8859-1 (Latin-1). 
My data base is encoded using ISO-8859-2 (Latin-2) and I'm running dbeaver on windows_7_64 and Java 8.

Changing option in '**Preferences -> Database -> Result Sets -> Binaries -> String encoding'** doesn't affect on data view at all (my tests revealed that this combo box is actually dummy). 
When I set db connection encoding attribute to Latin-2 it makes totally mess (I cannot decode it properly with any editor).

I've even changed JVM default encoding properties to ISO-8859-2 (by editing 'dbeaver.ini' file) and they seem to load OK (example from '**Installation details**'):

`file.encoding=ISO-8859-2`
`sun.jnu.encoding=ISO-8859-2`

But still result set is encoded with ISO-8859-1.

Furthermore, I think this issue messed up the export to *.cvs functionality. Dbeaver thinks now that strings are binaries and it puts nulls to output.

Are there any workarounds?

Regards from Poland,
Bartek

**Comment by serge-rider** [comment] 2016-05-30 12:04
What is your database?
What exactly is wrong with encoding (some screenshot could help)?

**Comment by serge-rider** [comment] 2016-06-01 12:22
Please test EA version
http://dbeaver.jkiss.org/files/ea/

**Comment by vckbarth** [comment] 2016-06-06 15:09
My database (Fis Profile) is connected with external JDBC (developed by FIS). As I've mentioned it is decoded on server side with ISO-8859-2.

First step - setting jdbc connection with ISO-8859-2 encoding:
![latin2](https://cloud.githubusercontent.com/assets/19408985/15826491/092e8e82-2c08-11e6-9f85-fcbec57a7460.png)

Second step - retrieving data from STBLPAT table:
![resultset_latin2](https://cloud.githubusercontent.com/assets/19408985/15826570/520d5142-2c08-11e6-8544-2fea7168afaa.png)

Here I cannot figure out what is the encoding. I was trying every combination using notepad++ and still same mess.

Third step - First step - setting jdbc connection with ISO-8859-1 encoding:
![latin1](https://cloud.githubusercontent.com/assets/19408985/15826625/93301d26-2c08-11e6-8d1e-1842370b60bf.png)

Fourth step - again retrieving data from STBLPAT table:
![resultset_latin1](https://cloud.githubusercontent.com/assets/19408985/15826655/b6c34aba-2c08-11e6-9b13-09a0262bfab1.png)

Stiil mess but something is different.

Fifth step - using notepad++ I'm changing encoding from ISO-8859-1 to ISO-8859-2
![np_latin1_to_latin2](https://cloud.githubusercontent.com/assets/19408985/15826700/df42c27c-2c08-11e6-8625-8c62bae438d3.png)

As you can see there is no mess anymore. Polish special characters looks just fine.

I've tried the EA version but got same results.

Any ideas?

**Comment by serge-rider** [comment] 2016-06-06 23:00
This looks like some mess of encodings. 
Value of `file.encoding` or `sun.jnu.encoding` doesn't actually matters in DBeaver. Strings comes from JDBC driver in that form. It is driver's work to transform bytes from network stream into valuable strings.
A few questions:
- What data type column DESC has?
- Are you sure that these strings were originally stored in ISO-8859-2?
- Are there any other connection properties which may affect server/client encoding? Fis products are not very public so I can't check it by myself.

**Comment by vckbarth** [comment] 2016-06-07 06:58
Well,

DESC is VARCHAR 40. I'm absolutely sure about data base encoding (ISO-8859-2). Simple app written in java shows that everything should work just fine.
![java_code](https://cloud.githubusercontent.com/assets/19408985/15848376/f52c10dc-2c8c-11e6-9e51-04626d615006.png)

Result is OK:
![java_result](https://cloud.githubusercontent.com/assets/19408985/15848381/01cc082e-2c8d-11e6-962f-62f2bbf3810d.png)

There is no any other parameters set in connection definition. 
As I mentioned in the first post change charset in result set settings to the right one should fix the issue.
**'Preferences -> Database -> Result Sets -> Binaries -> String encoding'**
![combo_box](https://cloud.githubusercontent.com/assets/19408985/15848488/994dabd0-2c8d-11e6-8906-68a150aa99be.png)

Problem is this combo box just doesn't work. It doesn't change anything. Maybe this is the clue to solution?

**Comment by serge-rider** [comment] 2016-06-07 07:39
Well, I have a clue. I think this is the same problem as in #511.
Possibly this error is a side effect of the fix of #499 (DBeaver explicitly set file.encoding to utf-8).
I've just changed this behavior one more time.
Please try EA version (http://dbeaver.jkiss.org/files/ea/), maybe your issue is resolved there.

**Comment by vckbarth** [comment] 2016-06-07 08:11
I'm afraid that EA version still got the problem. 
Please note that when JDBC is getting bytes from the network (srcBytes[]) it saves them to String object using something like this:
`String result = new String(srcBytes[], srcFileEncoding)`

The `srcFileEncoding` in that case is of course **ISO-8859-2**. The result object (our destination) is decoded with charset inherited from platform (JVM, but JVM takes it from Windows using `file.encoding`) so in fact that should be Cp1250.

That's why I thought the result set view just needs a different destination charset.

**Comment by serge-rider** [comment] 2016-06-07 09:52
Yeah, that's how Java strings can be constructed from bytes. But JDBC drivers usually don't use "file.encoding" explicitly because it is system dependent and may differ from server-side encoding. That's why there are no problems with standard drivers (like mysql, postgresql, oracle, etc) - they always use database encoding or universal network encoding (like UTF).

Anyhow Binaries->String encoding options has nothing to do with that. It affects only binary (BLOB) data types encoding.

You could try to run DBeaver (EA version) with file.encoding parameter:
`dbeaver.exe -vmargs -Dfile.encoding=ISO-8859-2`
It could help.

**Comment by vckbarth** [comment] 2016-06-08 13:00
I've tried this solution but no progress.

Is there any instruction how to debug this feature? I have never treated with Eclipse Platform before.

**Comment by serge-rider** [comment] 2016-06-08 14:22
Generally you can open DBeaver projects in Eclipse Java IDE and then run DBeaver.product file in debugger. But there could be some issues, Eclipse environment is quite sophisticated.

Another way is to attach to running DBeaver process. run DBeaver with the following parameters:
`dbeaver.exe -vmargs -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5015`
Now you can attach to it with your preferred Java debugger (to the port 5015 in this example).

This is where DBeaver reads values from resultset:
https://github.com/serge-rider/dbeaver/blob/f299b23deb0e68a2d545a35f2a5e0344fee964f9/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/jdbc/data/handlers/JDBCStringValueHandler.java#L48

**Comment by vckbarth** [comment] 2016-06-16 12:46
Hello again, 

I've successfully build Dbeaver project with Maven and inserted breakpoints to the source code in Eclipse Mars. But I don't know how to execute debug session.

Can you tell me please how to run 'Dbeaver.product' in debug mode?

**Comment by serge-rider** [comment] 2016-06-17 20:13
Open DBeaver.product file - you will see a toolbar button (on the top of editor toolbar): "Launch an Eclipse application in Debug mode". Usually it works ok.

**Comment by serge-rider** [comment] 2016-07-07 10:08
Any news?
As I can't fix it by myself I can just wait for any further details or just close this issue as non-reproducible..

**Comment by vckbarth** [comment] 2016-07-08 09:56
I haven't got time recently to work this out. But I'll have some this weekend. 
So if you give me just a little bit more time, I will finish this job.

**Comment by vckbarth** [comment] 2016-07-17 15:40
I have a little problem with running DBeaver.product. It's odd because 'maven install' works fine.
I've attached log file. 
[log.txt](https://github.com/serge-rider/dbeaver/files/367939/log.txt)

**Comment by serge-rider** [comment] 2016-07-17 16:01
That's odd, looks like some kind of misconfiguration.
Open product "Debug configuration" and check that `com.ibm.icu` plugin is included in the build.

**Comment by vckbarth** [comment] 2016-07-17 16:18
I'm not sure where to find "Debug configuration". Did you mean "configuration tab" in "dbeaver/product/standalone/Dbeaver.product"?
I've attached a screenshot: 
![dbeaver](https://cloud.githubusercontent.com/assets/19408985/16901692/e33e9452-4c4a-11e6-9d2d-8ac4f4295e5f.png)

**Comment by serge-rider** [comment] 2016-07-17 16:51
As I understand build passes fine but DBeaver doesn't start. 
So click on dropdown of "Debug" icon in the main toolbar and choose "Debug configuration" command (or main menu Run->Debug configurations). On tab "Plugins" you will see all plugins which will be used in runtime.

**Comment by vckbarth** [comment] 2016-07-23 20:46
Bad news. I still have issues with debug dbeaver using Eclipse Mars. Even maven builds the product successfully It just won't start (it keeps telling that some packages are missing). I've tried attach existing Dbeaver process but no luck either.

In case that I don't have much time to remove this issues I think there are 2 options:
- you could prepare for me Dbeaver project workspace dedicated to Eclipse Mars and Win7 just to run it in debug without any glitches
- you could prepare a binary of Dbeaver for Win7_x64, with some extra logging functionality added just to catch these couple places where result set data could be damaged.

Note that I've tested Dbeaver insert/update functionality  (using SQL INSERT/UPDATE and directly from rows editor) and it works fine. So the problem must be connected with transport result set data from JDBC to Editor.

**Comment by serge-rider** [comment] 2016-07-25 18:25
That's very weird. Text editor always works in UCS2 (UTF-16) - the only internal Java encoding. IF strings were received from remote server in the correct form then they must be visible.

Can you reproduce this problem with any other database/driver?
Maybe the problem is in the bad fonts on you local machine?

**Comment by vckbarth** [comment] 2016-08-07 20:49
Hello there,

I've done for you basic Fidelity Database instance. I'ts all prepared as a virtualbox image (Linux Debian). To downoload all files you need (image and JDBC + some screenshots) check out this links:
[https://dl.dropboxusercontent.com/u/60701501/jdbc_and_screens.zip](url)
[https://dl.dropboxusercontent.com/u/60701501/debian_pip.vdi.7z](url)

To configure it properly see screenshots. Steps:
1. Unpack *.vdi image.
2. Create new 'Debian' virtual mashine using existing image. Mount it as a IDE hdd drive.
3. Set network settings - let's say 'bridge adapter'.
4. Boot Debian with login: pip, and password: PIPRocks
5. Check VM ip with command: /sbin/ifconfig
6. Open dbeaver and create new driver settings using 'fidelity_jdbc_driver_settings.png' picture (very important in this part is to set encoding to ISO-8859-2). 
7. Make new db connection using VM ip and 'database_connection_settings.png'. Db login is '1' and password is 'xxx'
8. Connect to the DB and run a select query: SELECT * FROM UTBLMSG;

That's it. You should see broken result. Properly data should be like this:
![database](https://cloud.githubusercontent.com/assets/19408985/17465155/4a23632c-5cf0-11e6-93cd-f43e02dc2234.png)

I hope this gonna help you to reproduce the problem and to fix it. Next week I will be unavailable. But a week after I'll check how we are doing.

Cheers

**Comment by serge-rider** [comment] 2016-08-09 08:44
Ok, I'll try it when I'll be back from vacation

**Comment by serge-rider** [comment] 2016-08-13 19:20
Well, I've reproduced that. Thanks for detailed instructions.
The problem was in column data type (driver says that it is BINARY while actually it is a string - VARCHAR). 
Anyhow, when DBeaver tried to convert a string into BINARY type it corrupted the actual value.
Now fixed:
![fidelity_encoding](https://cloud.githubusercontent.com/assets/6398845/17645098/d839b712-61a3-11e6-9701-c9a53700d079.png)

**Comment by serge-rider** [comment] 2016-08-13 19:42
Actually it is a bug in Fidelity driver.
Function DatabaseMetaData.getTypeInfo() returns information about supported data types. This driver returns multiple definitions of VARCHAR data type and also sets type id Types.BINARY for some of them.

After all I've added a special workaround for that.

**Closed** 2016-08-13 19:49 UTC
Labels: bug

**Comment by MttCastelli** [comment] 2018-07-20 08:23
Hi, may this attached depends from a similar issue? It's an **Oracle DB**, **very latest DBeaver CC** and _Preferences -> Database -> Result Sets -> Binaries -> String_ encoding is set on UTF-8

![dbeaver_issue494](https://user-images.githubusercontent.com/11462157/42991565-466d4f4e-8c06-11e8-9ea9-8f832f0b6862.JPG)

**Comment by rjxby** [comment] 2020-04-27 13:31
@MttCastelli I have the same problem as you, try change Binaries format to HEX, it's works for me.
<img width="619" alt="Screenshot 2020-04-27 at 16 27 40" src="https://user-images.githubusercontent.com/2773638/80377869-7eb49780-88a4-11ea-9b37-1c2938ea15e6.png">

**Comment by zzbyy** [comment] 2024-05-04 14:33
> @MttCastelli I have the same problem as you, try change Binaries format to HEX, it's works for me.
> 
> <img alt="Screenshot 2020-04-27 at 16 27 40" width="619" src="https://user-images.githubusercontent.com/2773638/80377869-7eb49780-88a4-11ea-9b37-1c2938ea15e6.png">

This helps!
 I got the same issue with all fields with data type  `bytea`, change Binary data formates from String to HEX helps! Thanks to @MttCastelli
