### ISSUE TITLE
Auto complete stops working on quoted columns

### ISSUE THREAD

**Issue by esulistio** [serge-rider/dbeaver#2191] opened 2017-09-21 00:20 UTC
Due to port from SQL Server we are using quoted tables and columns, the auto complete has been working until version 4.1.2 but it stops working on column names after that version.

**Comment by serge-rider** [comment] 2017-09-21 04:59
Duplicate of #2169.
Thanks for report anyway.

**Closed by serge-rider** 2017-09-21 04:59 UTC
Labels: bug, duplicate
