### ISSUE TITLE
SSH User Issue: Can't initialize tunnel   org.jkiss.dbeaver.DBException: SSH user not specified

### ISSUE THREAD

**Issue by rezetta** [serge-rider/dbeaver#1685] opened 2017-05-22 14:19 UTC
After upgrade to 4.0.7 all my connections have issues with SSH user.

**Comment by serge-rider** [comment] 2017-05-22 17:58
Can't reproduce.
Does this mean that user name was reset in all connections? What happens if you re-enter user name for these connections?

**Comment by rezetta** [comment] 2017-05-23 08:26
I click “Edit connection” on any connection. Then “Network settings (SSH, SSL...)”. Under “SSH Tunnel”, I enter my “User Name”, but it does NOT save the user name.

**Comment by rezetta** [comment] 2017-05-23 08:29
![screenshot from 2017-05-23 10-26-53](https://cloud.githubusercontent.com/assets/10758834/26345251/a21dfd5e-3fa2-11e7-8b69-bfe9d5b875de.png)

**Comment by serge-rider** [comment] 2017-05-23 08:45
Still can't reproduce. Probably this is somehow related to other configuration.

Please post debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files).

**Comment by p-sanchez** [comment] 2017-05-25 00:00
Relevant part of the debug log:
`2017-05-24 17:51:48.695 - org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:674)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:73)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:101)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.initConnection(DataSourceDescriptor.java:605)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:121)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:188)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:562)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:85)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.jkiss.dbeaver.DBException: SSH user not specified
	at org.jkiss.dbeaver.model.impl.net.SSHTunnelImpl.initializeTunnel(SSHTunnelImpl.java:84)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:672)
	... 14 more`

> Does this mean that user name was reset in all connections? 

Yes.
> What happens if you re-enter user name for these connections?

The user name resets again.

**Comment by rebeccab411** [comment] 2017-05-25 13:55
I can also report this problem with 4.0.7... Reinstalled 4.0.6 and connections succeed again.

**Comment by serge-rider** [comment] 2017-05-25 18:14
Could you provide a bit more details:
- Do you also have "Save password" checked off
- Does DBeaver show "Enter password" dialog during connection?

**Comment by rebeccab411** [comment] 2017-05-25 18:15
I will have to reinstall the new version later today and will report back ~ I need the working version for the next few hours ~

**Comment by serge-rider** [comment] 2017-05-25 18:19
Nevermind, I've just reproduced that.  Fix will be in the next version.
This happens only if you authenticate with private key and "Save password" was switched off.

Workaround: enable "Save password" (even if you have empty password).

**Comment by rebeccab411** [comment] 2017-05-25 18:22
Right on ~ Thanks!

**Comment by rezetta** [comment] 2017-05-25 18:45
That's what I found out too. Sorry for not replying back sooner.

Den tor. 25. mai 2017, 20.23 skrev rebeccab411 <notifications@github.com>:

**Closed** 2017-05-25 19:07 UTC
Labels: bug
