### ISSUE TITLE
Exception when trying to connect on oracle

### ISSUE THREAD

**Issue by matiouz** [serge-rider/dbeaver#1301] opened 2017-02-21 14:22 UTC
When I try to connect to an oracle database, I get the following exception:

2017-02-21 14:54:45.016 - Connect with 'Oracle MGY - New Connection' (B7126058-DB95-0EEB-6A2C-2CF09994CF8C-15a60f355e6-7cbc8b26277e94f9)
2017-02-21 14:54:45.271 - Connection failed (B7126058-DB95-0EEB-6A2C-2CF09994CF8C-15a60f355e6-7cbc8b26277e94f9)
2017-02-21 14:54:45.286 - org.jkiss.dbeaver.DBException: Internal error connecting to Oracle MGY - New Connection
org.jkiss.dbeaver.DBException: Internal error connecting to Oracle MGY - New Connection
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:766)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:73)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.initializeContextState(OracleDataSource.java:144)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:119)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeMainContext(JDBCDataSource.java:117)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:111)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:100)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.<init>(OracleDataSource.java:80)
	at org.jkiss.dbeaver.ext.oracle.OracleDataSourceProvider.openDataSource(OracleDataSourceProvider.java:131)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:715)
	... 3 more

I'm running on windows, I've installed dbeaver-ce-4.0.0-win32.win32.x86_64.zip

I've setup a new oracle driver with :
    ojdbc6.jar (Implementation-Version: 11.2.0.1.0)
    orai18n.jar
    xdb6.jar

It works fine on dbeaver 3.5.2

**Comment by serge-rider** [comment] 2017-02-21 14:25
Duplicate of #1284
Hotfix version will be released later on this week.

**Closed by serge-rider** 2017-02-21 14:25 UTC
Labels: bug, duplicate
