### ISSUE TITLE
4.2.5 Oracle Date Truncating Time

### ISSUE THREAD

**Issue by nealrout** [serge-rider/dbeaver#2551] opened 2017-11-20 14:57 UTC
Once upgrading to version 4.2.5 from 4.2.4 the Oracle Date fields (which contain timestamp) are now no longer showing.  I have reverted my version to 4.2.4 for now.  Just thought you all should know this.

View from 4.2.5
![image](https://user-images.githubusercontent.com/21213885/33024419-08562f0a-cdd9-11e7-961a-6c205331f1f9.png)

View from 4.2.4
![image](https://user-images.githubusercontent.com/21213885/33024454-1a7f169c-cdd9-11e7-8508-4b4cdbc7f2e8.png)

I went in and updated the format in preferences
![image](https://user-images.githubusercontent.com/21213885/33024462-25c40030-cdd9-11e7-8294-026d933ebf5e.png)

But it results in the time showing all zeros
![image](https://user-images.githubusercontent.com/21213885/33024471-2cda47a8-cdd9-11e7-8cee-b1e54f99d8a2.png)

**Comment by serge-rider** [comment] 2017-11-20 17:55
Yep, it is a bug in 4.2.5. Duplicate of #2511
Thanks for report anyway.

**Closed by serge-rider** 2017-11-20 17:55 UTC
Labels: bug, duplicate
