### ISSUE TITLE
New logo looks really grainy on the OS X Dock

### ISSUE THREAD

**Issue by nchammas** [serge-rider/dbeaver#615] opened 2016-07-20 17:09 UTC
The new logo looks really grainy compared to some of the others:

![screen shot 2016-07-20 at 1 06 40 pm](https://cloud.githubusercontent.com/assets/1039369/16995581/17a476a8-4e7b-11e6-8f1a-b359cc10ecfd.png)

It's a harmless cosmetic issue, obviously, but I figure it's something you might want to fix.

**Comment by serge-rider** [comment] 2016-07-20 17:18
Duplicate of #601 
Already fixed. Thanks for report anyway.

**Comment by nchammas** [comment] 2016-07-20 17:21
Ah OK, sorry about that. I looked for "logo" instead of "icon" before posting, so I missed #601.

**Comment by dimitriadisg** [comment] 2016-09-23 08:25
Well, old logo was awesome, too bad it changed. Still love DBeaver though

**Comment by serge-rider** [comment] 2016-09-23 09:12
What is wrong with new logo?

**Comment by ydq** [comment] 2016-09-24 12:37
@serge-rider The logo has a black background in the Launchpad of Macbook Retina (OSX10.11/10.12) since updated a new one.
![image1](https://cloud.githubusercontent.com/assets/8097340/18807101/9006face-8271-11e6-82a8-f6db8582ede2.png)
![image2](https://cloud.githubusercontent.com/assets/8097340/18807158/cb1150c8-8272-11e6-9ace-c129d14e8021.png)

**Comment by serge-rider** [comment] 2016-09-24 13:29
:(
It is strange that on my local machine it looks ok (black background is transparent).
I'll talk with MacOS guys, hopefully somebody will make icns better..

**Comment by dimitriadisg** [comment] 2016-09-24 22:15
I don't mind even if the logo looks as ugly as my avatar, since DBeaver is such an awesome tool, free and the team is very active. But in my honest opinion the old logo looked better, more detailed and professional, while the new one looks simple and cartoonistic, take a look :
![beaver-head](https://cloud.githubusercontent.com/assets/14919500/18811546/b02f71e0-82b3-11e6-969d-d6bf84eb5cae.png) vs ![beaver-head-new](https://cloud.githubusercontent.com/assets/14919500/18811549/cc1478ec-82b3-11e6-85ca-6954c60e7825.png)

Just look at this 8MB masterpiece !
![dbeaver-logo-drawing](https://cloud.githubusercontent.com/assets/14919500/18811572/a537db8c-82b4-11e6-9bcf-a4c426aad745.png)

But Serge, I can't help but feel curious, is there a reason behind the logo change ? Copyrights or something ?

**Comment by serge-rider** [comment] 2016-09-25 08:11
There is only one reason - I like new logo more than old one. New guy is more clearly a beaver (and it is easier to scale).
There are no copyright issues, both icons were drawn specifically for DBeaver.

**Comment by dimitriadisg** [comment] 2016-09-25 10:19
Aha, I see.

**Comment by nchammas** [comment] 2016-10-12 19:16
I am also seeing the black background that @ydq reported. The strange thing is that the black background shows up in the dock on my main screen, but not when I pull up the dock on my external monitor. Same goes for when I pull up Launchpad.

**Comment by serge-rider** [comment] 2016-10-14 07:41
Problem with black background was resolved in #759, thanks to @josemodena

**Closed by serge-rider** 2016-10-14 07:41 UTC
Labels: bug, duplicate
