### ISSUE TITLE
Unable to edit values for Redshift driver properties

### ISSUE THREAD

**Issue by boxuancui** [serge-rider/dbeaver#272] opened 2016-03-09 16:48 UTC
When I try to create a new connection with Redshift, I can't set values for `ssl` and `sslfactory`. I can only select `?` from the dropdown menu.

I also tried to connect with PostgreSQL driver. I can connect fine, but I can't open schemas, because `pg_catalog.pg_authid` table is missing.

**Comment by serge-rider** [comment] 2016-03-09 18:19
Redshift driver seems to be poorly configured. It says that the only valid value for all properties is "?".
I'll add a workaround in the next version (will make all properties with predefined values editable).
Thanks for report.

(ph_authid issues is a duplicate of  #271)

**Closed** 2016-03-11 18:38 UTC
Labels: bug
