### ISSUE TITLE
Connection chooser broken

### ISSUE THREAD

**Issue by AlginMaduro** [serge-rider/dbeaver#1039] opened 2016-12-07 14:55 UTC
I have 2 cassandra connections.

i click on `New SQL Editor` -> i choose which connection i would like to use -> it connects to cassandra instance.

The issue is that after it (succesfully?) connects to cassandra the connection selector becomes "unclickable". which means i cannot choose some other instance/keyspace. The dropdown menu does not drop.

Issue started in version 3.8.0

![image](https://cloud.githubusercontent.com/assets/1469047/20972281/ac57b0b2-bc94-11e6-8d68-9c89de18259a.png)

![image](https://cloud.githubusercontent.com/assets/1469047/20972377/f339f940-bc94-11e6-9766-9ea127d17ef3.png)

**Comment by serge-rider** [comment] 2016-12-08 20:36
Seems to be a duplicate of #893

**Closed** 2016-12-08 20:36 UTC
Labels: bug, duplicate
