### ISSUE TITLE
Can't export data to another DB and skip column

### ISSUE THREAD

**Issue by p-kozlov** [serge-rider/dbeaver#753] opened 2016-09-21 12:09 UTC
I have two databases with two identical tables, except one of them has one additional column. Suppose the old version has 10 columns, the new one has 11 columns.
I want to copy all rows from new table to the old one, but I want to not create, to ignore such column. I marked "skip" in export dialog window.

However, export (from one database to another) fails with the following error message:
`org.jkiss.dbeaver.model.exec.DBCException: Target attribute for [column_name] wasn't resolved`

Actually, it doesn't work even if I don't skip this column - dbeaver tried to create it (I guess with `ALTER TABLE` query) and also fails. But I am not interested in that - I want to copy 10 columns and skip 1.

**Comment by serge-rider** [comment] 2016-09-21 12:20
Duplicate of #731
Will be fixed in the next version.

**Closed by serge-rider** 2016-09-21 12:20 UTC
Labels: duplicate

**Comment by p-kozlov** [comment] 2016-09-21 12:29
OK.

Well, also I found out the reason why it can't create new column in another table. The reason is that it tried to use the following command `ALTER TABLE <table> ADD <column> smallint NOT NULL` without default value. It would be nice to have ability to substitute default value here. It could be tricky to do in the next version, but it is nice thing to have.

I think should be fine for columns without `NOT NULL` constraint.
