### ISSUE TITLE
dbeaver eats gigabytes of RAM

### ISSUE THREAD

**Issue by gintas** [serge-rider/dbeaver#290] opened 2016-03-17 10:28 UTC
I use DBeaver on a daily basis and keep the application open for days on end. Today I got a warning from the OS about low memory. I checked the list, and DBeaver was eating 5.6GB! This is on Windows 7, DBeaver v3.5.9.

I poked around with VisualVm. The DBeaver process had 5.6GB of heap allocated, 2.2GB of that in use. I tried to get a heap dump, which, I think, triggered a GC, and "used memory" fell to 195MB (!). However, the size of the allocated heap only fell to 3.8GB, and indeed, according to the system monitor, the process is still taking up 3.8GB of RAM.

Any idea what's going on here? Can the process be made to behave better in terms of memory use?

**Comment by infectormp** [comment] 2016-03-17 10:29
@gintas could you update to latest version and try reproduce this problem?

**Comment by serge-rider** [comment] 2016-03-17 10:44
Memory consumption is very dependent on drivers you are using and on actions you are doing.
Some of them (e.g. Hive and some other NoSQL drivers) may eat tons of memory by themselves.

You can turn on heap status info (Preferences->General) and see what action leads to so huge memory consumption.
And yes, it's better to use the most recent version.

**Comment by codebling** [comment] 2016-03-20 05:43
@gintas this is kind of just an issue with how Java deals with garbage collection. When an application requests more memory from the Java Virtual Machine, the JVM will often grow the heap before it attempts to garbage collect. In doing so, the JVM requests a heap allocation from the OS. At this point, even if the JVM garbage collects, the memory is never returned to the OS. Subsequently the JVM will generally continue letting the application heap to grow until it triggers another heap grow and requests more memory from the OS. 

It's not because of a memory leak or bad design decisions in DBeaver, it's simply the way Java works. You'll find that the same is true of any Java application.

You can try limiting the maximum memory used by Java.

**Comment by carlosjrcabello** [comment] 2016-03-24 12:15
I have used bdeaver for a long time and I never got a problem with high memory consumption, even when I was working with migration scripts handling millions of rows (in MySQL and postgres).

Sometimes, dbeaver gets a little bit slow when I run select statements that returns lots of row, but its normal, since its expected.

**Comment by codebling** [comment] 2016-03-24 19:30
@carlosjrcabello can you define "a long time"? It's not necessarily related to the number of rows returned. Just general usage.

To me it's more strange that DBeaver becomes slow when you return a lot of rows !   I don't think that's normal, unless you have made "ResultSet fetch size" very large or set it to 0 (all results fetched). Or, if you have set it to a relatively low number but have made many many fetches (scrolling to the bottom of the results many times). Or it might make sense if you were not speaking about the slowness of DBeaver itself but of the query execution time. Can you clarify?

**Comment by carlosjrcabello** [comment] 2016-03-24 20:40
Hi there,

I just tried to explain what happens to me when I'm using dbeaver as coding and running giant queries...I just trying to understand what may caused what was described in this issue.

I think I couldn't explain it right :/

**Comment by serge-rider** [comment] 2016-03-24 21:26
> coding and running giant queries

Maybe it is the same issue as in #304 (giant queries). If so then it'll be fixed in 3.6.3.

**Comment by carlosjrcabello** [comment] 2016-03-25 00:19
uhmmm...I'll test it when you commit.

thanks serge;

**Comment by gintas** [comment] 2016-03-30 17:41
FWIW, some GC implementations are reasonably good at releasing memory, see

http://www.stefankrause.net/wp/?p=14

I wonder if DBeaver could be made more well-behaved by tweaking the JVM GC parameters. The defaults are intended for max-throughput bounded-memory servers, while DBeaver as a desktop app calls for a more use-only-as-much-as-you-need a pproach.

**Comment by serge-rider** [comment] 2016-03-30 17:49
I'd wish to, but in fact there are too many different VMs with different GCs and different parameters.
Generally I rely on Eclipse framework facilities - as Eclipse is a desktop application too.
But maybe some GC tuning makes sense for Windows version (with JRE included).
If you have any particular suggestions - please tell.

**Comment by codebling** [comment] 2016-04-02 20:01
@gintas Good find! Nice!

**Closed** 2016-04-11 10:27 UTC
Labels: can't reproduce, help wanted

**Comment by gintas** [comment] 2016-06-17 09:45
By the way, what's the default heap limit supposed to be? I still run into this from time to time - and I just found out that the -Xmx heap limit for my instance was 7GB, which seems way high to be a default.

**Comment by serge-rider** [comment] 2016-06-17 20:09
DBeaver doesn't set any explicit Xmx value. 
Generally it depends on your Java version and calculated from total amount of physical memory: http://stackoverflow.com/questions/4667483/how-is-the-default-java-heap-size-determined

**Comment by wampirr** [comment] 2018-06-14 09:02
Always ~10GB after some days.
Used functional:
- 2 opened forever bd connections (Oracle, Postgres)
- 2-4 hand made primitive selects per day

**Comment by Bsplesk** [comment] 2019-06-02 20:16
ate 16GB for a couple of hours. 
`` 
cat dbeaver.ini 
-startup
plugins/org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.1000.v20190125-2016
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Xms64m
-Xmx512m


2019-06-02 23:15:01.879 - > Start org.jkiss.dbeaver.core [6.0.5.201905192012]
2019-06-02 23:15:01.884 - DBeaver 6.0.5.201905192012 is starting
2019-06-02 23:15:01.885 - OS: Linux 4.19.29-1-lts (amd64)
2019-06-02 23:15:01.885 - Java version: 1.8.0_202 by Oracle Corporation (64bit)
2019-06-02 23:15:01.886 - Install path: '/opt/dbeaver'
2019-06-02 23:15:01.886 - Instance path: 'file:/home/XX/.dbeaver4/'
2019-06-02 23:15:01.886 - Memory available 109Mb/455Mb
2019-06-02 23:15:01.896 - Starting RMI server at 43699
2019-06-02 23:15:01.944 - Run workbench
``

**Comment by pencilcheck** [comment] 2021-04-07 17:23
Still happening on latest version
