### ISSUE TITLE
Open Declaration in Package View

### ISSUE THREAD

**Issue by Jayshua** [serge-rider/dbeaver#1908] opened 2017-07-21 13:22 UTC
When I'm in SQL Script view and press F4, DBeaver jumps to the definition of whatever is under my cursor. But when I'm in the package body view, F4 does nothing. Is this intended behavior, am I missing something?

(DB: Oracle, DBeaver version 4.1.10)

**Comment by serge-rider** [comment] 2017-07-30 14:57
This is actually a bug, thanks for report. It'll be fixed in the next version.

As a workaround you can use <kbd>CTRL</kbd>+mouse click to open object declaration.

**Closed** 2017-07-30 14:59 UTC
Labels: bug

**Comment by Guegs64** [comment] 2024-01-26 11:28
Hi, 
The feature discribed by Jayshua still does not work in the most recent version.
_I'm in SQL Script view and press F4, DBeaver jumps to the definition of whatever is under my cursor. But when I'm in the package body view, F4 does nothing. Is this intended behavior, am I missing something?_

If you can fixed it, thanks a lot !
(DB: Oracle, DBeaver version 23.3.3)

**Comment by mydlo** [comment] 2025-08-27 07:15
Version 25.1.5.202508171444 (DB: Oracle) and it still does not work. I know there is a workaround, but not very convenient for keyboard users...
