### ISSUE TITLE
can'n save changes of stored procedure

### ISSUE THREAD

**Issue by stepjacky** [serge-rider/dbeaver#210] opened 2016-02-20 15:10 UTC
create a stored procedure
open it for edit, change  sql ddl of this procedure and press save button[disk icon in toolbar],but the change of this stored procedure not saved to database ,error log is flowing:
`null
org.jkiss.dbeaver.model
Error
Sat Feb 20 23:01:43 CST 2016
org.eclipse.swt.SWTException: Invalid thread access`

dbeaver 3.5.9  MySQL [5.5.5-10.0.15-MariaDB] mysql-connector is 5.1.38 or mariadb java-client 1.35

**Comment by serge-rider** [comment] 2016-02-20 16:35
Duplicate of #174

**Closed by serge-rider** 2016-02-20 16:35 UTC
Labels: duplicate

**Comment by stepjacky** [comment] 2016-02-21 05:21
get it
