### ISSUE TITLE
Active catalog/schema dropdown is empty

### ISSUE THREAD

**Issue by cnizzardini** [serge-rider/dbeaver#2390] opened 2017-10-20 16:16 UTC
Since upgrading to 4.2.3 I cannot select an active catalog/schema using the the top menu bar dropdown. The dropdown is empty, when I click it, it opens an empty window.

**Operating System:**
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
Linux chris 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
gnome-shell             3.18.5-0ubuntu0. amd64

**Screenshot**: 
https://i.imgur.com/kweuaDV.png

**Comment by serge-rider** [comment] 2017-10-20 18:58
Duplicate of #2348 (see comments for workaround)

**Closed by serge-rider** 2017-10-20 18:58 UTC
Labels: bug, duplicate
