### ISSUE TITLE
Informix table information : Triggers

### ISSUE THREAD

**Issue by amivanovano** [serge-rider/dbeaver#1981] opened 2017-08-08 07:02 UTC
When I clicked on Tab Triggers dbeaver said:

![image](https://user-images.githubusercontent.com/28041955/29059992-9d73f9c4-7c20-11e7-81f2-d160dd24e0e5.png)

**Comment by serge-rider** [comment] 2017-08-08 07:13
Duplicate of #1968

**Closed by serge-rider** 2017-08-08 07:13 UTC
Labels: bug, duplicate
