### ISSUE TITLE
Auto completion removes `

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#867] opened 2016-10-20 11:55 UTC
When I try to write a query and I use auto completion for table names between two ` the two ` get removed.

**Comment by serge-rider** [comment] 2016-10-20 14:04
Can't reproduce. Please provide more details (BTW you could create a short video with tool like ScreenToGif - sometimes it is much more descriptive than tons of text).

**Comment by GiantCrocodile** [comment] 2016-10-20 15:00
1. copy and paste this query: https://gist.github.com/carlosjrcabello/9b30f4c61724d7c8d38e3ad8d794d182
2. press backspaces to remove 'your_table'
3. press `CTRL+SPACE` for auto completion and select some table.

Your ` are gone afterwards.

**Comment by serge-rider** [comment] 2016-10-20 15:04
Umm, what's the point having ` in that case? Identifier quoting makes sense if it contains any special characters, spaces, etc. DBeaver doesn't insert quotes around "good" identifiers.

**Comment by GiantCrocodile** [comment] 2016-10-20 15:07
Like you said it makes sense for special characters and also if you have a name which is a keyword so this is why I just put them around any name: This prevents me from thinking about if I could trigger some keyword or whatever. It is just the default way I do it because I learned it like this ages ago. Of course it is not necessary but I would expect it to insert just the name and not remove characters.

**Comment by serge-rider** [comment] 2016-10-20 15:19
Well, I can add some option like "Always quote identifiers" on SQL auto-completion prefs page.

**Comment by carlosjrcabello** [comment] 2016-10-20 16:31
Adding quote for special content makes sense, however I use quote (as in gist instance) because usually I have to generate sql scripts to run in a lot of servers, for other reasons, I don't think it's necessary.

**Comment by GiantCrocodile** [comment] 2016-10-20 16:45
I think I have to see if this is still necessary to me when I use DBeaver right more in praxis. So far I'm testing if the other functions work as expected to make sure next release will make it more usable for me.

**Comment by serge-rider** [comment] 2016-10-29 17:10
Ok. I'll close this for now. Reopen if you'll have some news.

**Closed by serge-rider** 2016-10-29 17:10 UTC
Labels: can't reproduce, question
