### ISSUE TITLE
oracle clob value panel - not able to select

### ISSUE THREAD

**Issue by nathanjohnson3181** [serge-rider/dbeaver#1357] opened 2017-02-27 19:46 UTC
Unable to select text in the Value panel when viewing a CLOB column in an Oracle db with 4.0.1. This works in 3.7.8

**Comment by serge-rider** [comment] 2017-02-27 19:56
Can't reproduce.
Is there some error? 
Error dialog? Maybe something in Error Log view?

**Comment by nathanjohnson3181** [comment] 2017-02-27 20:08
Hmm. Nothing in Error Log view and no errors. It shows the data in the panel, but I cannot highlight or select it. Ctrl-A doesn't work either. I can copy it from the actual cell so there is a workaround. I was just used to the other way.

**Comment by serge-rider** [comment] 2017-02-27 20:20
Now I can reproduce that. Fix will be in the next version.

Workaround: disable "auto-save value" option (in value view panel toolbar).

**Closed** 2017-02-27 21:10 UTC
Labels: bug
