### ISSUE TITLE
PostgreSQL autocomplete with schema name not working

### ISSUE THREAD

**Issue by shannonxfiles** [serge-rider/dbeaver#919] opened 2016-10-31 21:35 UTC
I'm using the latest version of dbeaver community and/or enterprise, but the autocomplete for PostgreSQL doesn't seem to be working for me. By autocomplete, if I drag and drop a table to the sql editor, or right click and select "read data in sql console", the schema doesn't automatically complete. One of my co-workers is using dbeaver and the autocomplete in the above mentioned fashion works for them.

This becomes an issue when trying to import or export data, because schema selection for the target isn't an option (co-worker has schemas)

![image](https://cloud.githubusercontent.com/assets/18333668/19872625/2696d5d6-9f91-11e6-8393-f6d7422a420f.png)

Is there some setting that has to be applied? 

Thanks!

**Comment by serge-rider** [comment] 2016-11-01 16:07
Can't reproduce that. And there is no special option to enable/disable schemas.
- Do you and your coworker use the same PostgreSQL database?
- What PostgreSQL driver do you use?
- Do you see schemas in database navigator?

**Comment by shannonxfiles** [comment] 2016-11-22 20:27
Seems like it was a driver issue, I was taking the default given. Once specifying a newer driver and restarting the application it worked. I can try to provide more detail if that would be useful.

Thanks for the response!

**Comment by serge-rider** [comment] 2016-11-22 22:15
Ok. I'll close this as non-reproducible.

**Closed by serge-rider** 2016-11-22 22:15 UTC
Labels: can't reproduce, question
