### ISSUE TITLE
PostgreSQL - schema suppression error

### ISSUE THREAD

**Issue by ced75** [serge-rider/dbeaver#395] opened 2016-04-22 07:39 UTC
Hi,

DBeaver : v 3.6.5 (linux)
PostgreSQL : v 9.5 (linux)

When I perform a right-clic on a schema and choose "Delete", two different problems occur:

1. If I clic on "View Script" : nothing happens, no script appears;
2. If I clic on "Yes", an error occures because the schema contains table and the deletion performs a DROP command without CASCADE. Is it possible to add CASCADE in the deletion command?

Thanks in advance.
Regards,

Cedric

**Comment by serge-rider** [comment] 2016-04-22 09:30
1. Can't reproduce. What's your OS?
2. Will be fixed in the next version, 10x for report

**Comment by ced75** [comment] 2016-04-22 09:33
1. Linux Mint 17.3
2. Thanks.

**Comment by serge-rider** [comment] 2016-04-24 22:27
Check Error Log view for any errors.
If there is nothing there then check debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by ced75** [comment] 2016-04-25 07:40
No error in log files

**Closed** 2016-04-25 12:10 UTC
Labels: enhancement
