### ISSUE TITLE
Generate SQL -> INSERT writes column name in quotes

### ISSUE THREAD

**Issue by Schultha** [serge-rider/dbeaver#597] opened 2016-07-14 08:42 UTC
Hello,

runinng the action Generate SQL for a selected row writes the column in quotes.
Column Name is value. 
Therefor the button "apply data Change" is not working too:
SQL Error [42000]: A syntax error has occurred.
  A syntax error has occurred.
    java.sql.SQLException: 

![issue](https://cloud.githubusercontent.com/assets/5869577/16833382/5be0b0be-49af-11e6-9bff-02405cda7b74.png)

**Comment by serge-rider** [comment] 2016-07-14 12:32
What's your database?

**Comment by carlosjrcabello** [comment] 2016-07-14 12:37
Hi @Schultha ,

Must probably it's happens because value is one of reserved words, anyway, that one could enveloped by 
backquotes.

**Comment by Schultha** [comment] 2016-07-14 20:35
This was an informix database. This error shouldn't happen.

**Comment by serge-rider** [comment] 2016-07-25 17:57
It seems to be a duplicate of #594

**Closed by serge-rider** 2016-07-25 17:57 UTC
Labels: bug, duplicate, question
