### ISSUE TITLE
Constraints column names not appearing

### ISSUE THREAD

**Issue by jk3us** [serge-rider/dbeaver#815] opened 2016-10-05 18:36 UTC
In the "Constraints" tab for a table, the names of the columns for the constraints aren't showing up.  This sometimes also happens for indexes, but I couldn't quickly reproduce it with my dummy table:

![image](https://cloud.githubusercontent.com/assets/41621/19126454/a45148b2-8b00-11e6-82fc-53ed8a2b3914.png)

Edit: this is using postgres, if that matters. I've seen if working with 9.4 and 9.6.

**Comment by serge-rider** [comment] 2016-10-05 19:32
Duplicate of #774

**Closed by serge-rider** 2016-10-05 19:32 UTC
Labels: duplicate
