### ISSUE TITLE
Table Indexes folder error

### ISSUE THREAD

**Issue by garbles9100** [serge-rider/dbeaver#2146] opened 2017-09-14 20:57 UTC
When I click on any table's Indexes folder I get the following error:

![image](https://user-images.githubusercontent.com/21175926/30455318-70889d4c-996d-11e7-8410-058da1b1a981.png)

I'm using DBeaver 4.2.0 with postgres 9.6.2.

**Comment by serge-rider** [comment] 2017-09-15 06:13
Duplicate of  #2069

**Closed by serge-rider** 2017-09-15 06:13 UTC
Labels: bug, duplicate
