### ISSUE TITLE
ADD command line option: disconnect all

### ISSUE THREAD

**Issue by allanlaal** [serge-rider/dbeaver#1927] opened 2017-07-27 12:42 UTC
start DBeaver with all active connections disconnected
could be combined with #1928 into one option

referenced in: https://github.com/serge-rider/dbeaver/issues/890#issuecomment-314892639

**Comment by serge-rider** [comment] 2017-07-27 20:56
Duplicate of #1928

**Closed by serge-rider** 2017-07-27 20:56 UTC
Labels: duplicate, feature request
