### ISSUE TITLE
Updating bind parameters dialog doesn't consistently 'notice' updated parameters

### ISSUE THREAD

**Issue by anophelesgreyhoe** [serge-rider/dbeaver#1368] opened 2017-02-28 22:18 UTC
When I execute a PL/SQL script with bind parameters multiple times, changing the values of the parameters in the "Bind Parameter(s)" dialog, I find that 30-50% of the time my updates are not used. 

What happens instead is that the value from the last execution is used, so I presume this is some kind of caching issue.

Indeed, if I re-execute the script, I see that the value(s) I updated on the previous execution are not remembered.

I haven't found a way to consistently make dbeaver use the updated values, so I end up just running the script repeatedly until it works. It almost seems random.

This error has been present in the last 4 versions of dbeaver that I have used, including the recent 4.x version.

**Comment by serge-rider** [comment] 2017-03-01 08:52
Can't reproduce.
Does this happen with all queries and all parameters? 
Note: DBeaver remembers values for all named parameters (e.g. `:param1`) but not for anonymous (`?`).

**Comment by anophelesgreyhoe** [comment] 2017-03-01 09:06
Thanks for investigating.

Yes, it seems to happen with all queries.

These are named parameters. I'm happy for the previous value to be remembered when I run the script, but when I change the value assigned to the named parameter, it's currently reverting to the value from the previous run.

As mentioned, this is PL/SQL script, e.g.something like

`
DECLARE
    v_param1  VARCHAR2(1000) := :MYPARAM1;
    v_param2  VARCHAR2(1000) := :MYPARAM2;
   
BEGIN
    DBMS_OUTPUT.PUT_LINE(v_param1);
    DBMS_OUTPUT.PUT_LINE(v_param2);
END;`

I am executing the code by highlighting from the entire code block and then pressing Ctrl+ENTER.

My OS is Ubuntu 16.04.

**Comment by serge-rider** [comment] 2017-03-01 09:22
Still can't reproduce. 
You can switch Execution Log tab (or to Query Manager view) and see what actual queries DBeaver executes. Are parameters correct there?

**Comment by anophelesgreyhoe** [comment] 2017-03-01 09:26
Thanks. I'll try that tomorrow (late evening here) and report back.

**Comment by quiescer** [comment] 2017-03-02 00:14
In the log the parameters are not the ones I entered. I just had a thought - when trying to reproduce the error, did you have autocommit enabled?

In this instance I am running code on a production DB and I don't have autocommit enabled.

**Comment by anophelesgreyhoe** [comment] 2017-03-02 00:16
In the log the parameters are not the ones I entered.

I just had a thought - when trying to reproduce the error, did you have autocommit enabled? If so, can you try without autocommit active?

In this instance I am running code on a production DB and I don't have autocommit enabled. I will see if the fault still occurs if I commit after every execution of the script.

**Comment by anophelesgreyhoe** [comment] 2017-03-02 00:42
Okay, so even if I commit after each execution the error still happens. Sometimes I have to run the script multiple times in a row, not doing anything differently, until my changes to the bind parameters are noticed.

**Comment by serge-rider** [comment] 2017-03-02 11:33
Have no clues so far. This is very weird.
Could you post debug log? (https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by anophelesgreyhoe** [comment] 2017-03-02 21:20
Okay, will do that when I'm back at work next week.

**Comment by anophelesgreyhoe** [comment] 2017-03-06 21:09
Okay, I've just run the same PL/SQL script about a dozen times. I should only have had to run it 3 times but I had to keep re-running and changing the bind parameters until they were seen by dbeaver.

I just kept repeating the same actions and eventually it would see the updated params after several retries.

It doesn't look like there's much in the log - please let me know if I should turn on some extended logging.

Thanks for investigating this issue.

[dbeaver-debug.txt](https://github.com/serge-rider/dbeaver/files/822503/dbeaver-debug.txt)

**Comment by serge-rider** [comment] 2017-03-06 21:57
Thanks.
Yep, log is empty. Still no clue. I've rechecked source code which manages query parameters and I can't realize how this can happen.
Maybe you use some unusual (for me) way to bind parameters.

Could you record a short video to let me understand what happens? You can use some anigif recorder like ScreenToGif - that's quite easy and gif can be attached right to GitHub comment.

**Comment by anophelesgreyhoe** [comment] 2017-03-07 05:13
Here's one example - notice when I enter 9 for VAR1 and leave VAR2 unchanged it still sees VAR1 as 8. If I had re-run the script again it would have displayed 8 in the Bind Parameters dialog.

![dbeaver_bind_variables1](https://cloud.githubusercontent.com/assets/11037075/23642722/a5087882-0361-11e7-84e8-7abe22e295c5.gif)

**Comment by anophelesgreyhoe** [comment] 2017-03-07 05:31
It seems to happen more often when I'm running a large PL/SQL script of several hundred lines in length, although that may just be my perception.

I can't see anything I'm doing that might be responsible for this behaviour.

I'm attaching another example - in the 3rd run, I change VAR1 to 3, but it's not 'noticed'. This is seen in both the script output and the fact that bind parameter still shows as 2 the next time I run.

I also had one case where I changed multiple variables and one of the changes was noticed, and the other not.
![dbeaver_bind_variables2](https://cloud.githubusercontent.com/assets/11037075/23643086/51c424ac-0364-11e7-9b5b-b406b2c78aeb.gif)
![Uploading dbeaver_bind_variables2.gif…]()

**Comment by anophelesgreyhoe** [comment] 2017-03-09 22:39
Here's is another issue with text entry fields that I've just encountered, and which I suspect could be related:

![dbeaver_dbexport_text_field_update_issue](https://cloud.githubusercontent.com/assets/11037075/23773924/27682554-0586-11e7-80b5-38c5ede9505b.gif)

**Comment by anophelesgreyhoe** [comment] 2017-03-10 18:52
I've just reproduced this issue on my home system, which is running Debian Stretch/Testing (9), with the i3 window manager, and JRE 1.8.0_121-b13.

**Comment by serge-rider** [comment] 2017-03-12 23:08
I've reproduced that, thanks for details. Problem caused by differences in traverse events handling on Windows/Linux and Mac. Will be fixed in the next version.

Workaround: in parameters binding dialog click on Ok button instead of Enter key. In columns mapping dialog press Enter after changing table name.

**Comment by quiescer** [comment] 2017-03-13 01:53
Great that you've been able to reproduce the issue and have a fix in mind. I'd have thought this is the kind of thing you shouldn't have to deal with if the underlying frameworks were doing their jobs properly :) Oh well.

**Comment by adamitj** [comment] 2017-03-13 16:47
I'm experiencing the same issue running DBeaver x64 on Windows 10 Pro connecting to DB2 LUW databases. If it's worth to mention, when the parameter is changed only the first instance is changed in the processed SQL that goes to the database driver:

Using this simple SQL:

`SELECT
	:RA_NUMBER AS n1, 
	:RA_NUMBER AS n2,
	:RA_NUMBER AS n3,
	:RA_NUMBER AS n4
FROM 
	SYSIBM.SYSDUMMY1`

Execute the statement passing 1 as the argument RA_NUMBER, then execute it again and change it to 2. You'll notice that only n1 has changed to 2 while n2, n3 and n4 still 1 on the second running.

NOTE: it doesn't matter if press ENTER or click OK button, the issue happens on both UI actions.

**Comment by serge-rider** [comment] 2017-03-13 17:30
@adamitj This is a different issue but it was also fixed. You can see this is EA version.

**Comment by serge-rider** [comment] 2017-03-13 21:25
Database transfer mapping page was also fixed and improved.

**Closed by serge-rider** 2017-03-13 21:25 UTC
Labels: bug
