### ISSUE TITLE
Connections hang after resume from RAM

### ISSUE THREAD

**Issue by michimartini** [serge-rider/dbeaver#1588] opened 2017-04-20 06:39 UTC
If computer is resumed from RAM in the morning dbeaver connections will hang and the only way out is to use the _**"Emergency Exit"**_. **_"Invalidate/Reconnect"_** will not work.
Both MSSQL and MySQL will recover after a lengthy (more than 8 minutes) timeout.

Reproduce: Leave DBeaver open with active connections before you initiate a suspend to RAM. Next morning wake up computer and try execute any kind of SQL statement or **_"Invalidate/Reconnect"_** .

Tested on Ubuntu 16.04 with DBeaver 4.0.5 #

**Comment by michimartini** [comment] 2017-04-20 06:56
Ah, sorry, this is a duplicate of 
http://dbeaver.jkiss.org/forum/viewtopic.php?f=2&t=918
I did not find this issue in these github issues here though.

**Comment by michimartini** [comment] 2017-04-20 07:04
Well, I can already say that parameter "loginTimeout" does not help MSSQL driver to behave. It was set to 15s, but still hung for over 8minutes.

**Comment by serge-rider** [comment] 2017-04-20 20:41
I don't think that this is duplicate of above mentioned issue.
And I can't say that this is a designed behavior. Regular connection should work ok (or break) after sleep/hibernation. But I saw similar problems with database connections over VPN - they just hang if VPN channel dies unexpectedly.

There is no workaround for this yet. All I can suggest is to use Database->Disconnect All and the reopen connections.

**Closed** 2017-05-01 20:12 UTC
Labels: question

**Comment by michimartini** [comment] 2017-06-20 07:03
I know this is a closed issue - but this bug seems to be gone in V4.0.8, which is awesome.
