### ISSUE TITLE
Postgresql: Resultset shows only the ArrayValues from the initial fetch

### ISSUE THREAD

**Issue by christian-macher** [serge-rider/dbeaver#690] opened 2016-08-30 11:02 UTC
Hello,

The Fetchsize ResultSet  is set to 10: 
.. Only the first 10 lines of ArrayValues would be displayed.

![image](https://cloud.githubusercontent.com/assets/17639280/18086616/20f04cf4-6eb1-11e6-8ba1-be2e9ec90d5d.png)

Thank you in advance.

**Comment by serge-rider** [comment] 2016-08-30 11:46
Can't reproduce.
Please send some SQL snippet  (DDL + inserts).
Also you can check error/debug logs: https://github.com/serge-rider/dbeaver/wiki/Log-files

**Comment by christian-macher** [comment] 2016-08-30 13:01
Datadump from table array_test
Columns involvedAgent and involvedAccountingArea has no NULL values

[data.sql.gz](https://github.com/serge-rider/dbeaver/files/444912/data.sql.gz)

Result from
`select a.*, array_length(a."involvedAccountingArea",1), array_length(a."involvedAgent",1) from array_test a`

![image](https://cloud.githubusercontent.com/assets/17639280/18089902/5fb0665c-6ec2-11e6-8c08-4e4a2684167a.png)

**Comment by serge-rider** [comment] 2016-08-30 13:28
Thanks for report and details.
Arrays reading will be fixed in the next version.

**Closed** 2016-08-30 21:52 UTC
Labels: bug
