### ISSUE TITLE
[Apache Derby] Create and Alter Table Statement is adding null to nullable fields

### ISSUE THREAD

**Issue by AJDulk** [serge-rider/dbeaver#1263] opened 2017-02-14 10:20 UTC
Current Version: 3.8.5

When adding a column to an existing table I get:
> ALTER TABLE APP.TEST_FOR_BUG_REPORT ADD BUG_REPORT VARCHAR(100) **NULL** ;

When trying to persist the change I get the following message:
> SQL Error [30000] [42X01]: Syntax error: Encountered "NULL" at line 1, column 62.
>   Syntax error: Encountered "NULL" at line 1, column 62.
>     org.apache.derby.iapi.error.StandardException: Syntax error: Encountered "NULL" at line 1, column 62.

I also noticed that the DDL has the same mistake with the same result, eg:
> CREATE TABLE APP.PUBLIC_CUSTOMERS (
> 	ID_ORDER BIGINT NOT NULL,
> 	NAME VARCHAR(100) NOT NULL,
> 	ID_ADDRESS BIGINT NOT NULL,
> 	DATE_ORDER DATE NOT NULL,
> 	EMAIL VARCHAR(254) **NULL**,
> 	CONSTRAINT PK_PUBLIC_CUSTOMERS PRIMARY KEY (ID_ORDER)
> ) ;

I am using the embedded driver of Derby version 10.11.1.1

**Comment by serge-rider** [comment] 2017-02-14 10:38
Duplicate of #1249.
Already fixed in 4.0 EA.

**Closed by serge-rider** 2017-02-14 10:38 UTC
Labels: bug, duplicate
