### ISSUE TITLE
Error on disconect if ession was killed or lose connectivity

### ISSUE THREAD

**Issue by infectormp** [serge-rider/dbeaver#250] opened 2016-03-01 07:29 UTC
If oracle session was killed or lose connectivity and we try disconnect from session dbeaver get an error.
```
JDBCException: SQL Error [17002] [08006]: IO Error: Connection reset
SQL Error [17002] [08006]: IO Error: Connection reset
SQLRecoverableException: IO Error: Connection reset
IO Error: Connection reset
SocketException: Connection reset
Connection reset
```
can we do some thing with this?

**Comment by serge-rider** [comment] 2016-03-01 09:39
Just click on "Invalidate/Reconnect" action in the main toolbar, main menu or context tools menu.

**Comment by infectormp** [comment] 2016-03-01 09:54
@serge-rider  "Invalidate/Reconnect" will Reconnect me to database. But i choice "Disconnect".
In case of lose connectivity user don't know that session was already broken and trying "Disconnect". After this he get this error. 

I think we need catch this error and do not show error or give info message about session already closed. How you think?

**Comment by serge-rider** [comment] 2016-03-02 08:16
I think that it always good to know what happens. Suppressing error messages isn't a good idea - unless they are too abuse. One extra error message on disconnect shouldn't be too harmful, right?

**Comment by infectormp** [comment] 2016-03-02 09:02
Agree. But i think i have another case. 

I think i see this error when close dbeaver because dbeaver try close all opened connection and some connection can be broken already. But in this case i can't read error because dbeaver windows destroyed after show error.

**Comment by serge-rider** [comment] 2016-03-03 09:51
I can't reproduce that. But I can see errors in error log..

**Comment by serge-rider** [comment] 2016-03-03 19:03
Reproduced (this happens when transaction is active and DBeaver tries to rollback it on disconnect).
Will be fixed in the next version.

**Comment by infectormp** [comment] 2016-03-03 19:23
:+1:

**Closed** 2016-03-04 09:14 UTC
Labels: enhancement
