### ISSUE TITLE
Dates are wrongly displayed in result set (Oracle)

### ISSUE THREAD

**Issue by cpum** [serge-rider/dbeaver#2511] opened 2017-11-13 10:12 UTC
Dates are wrongly displayed in the result set. It looks like instead of the month, minutes are displayed (mi instead of mm).

Example: 2017-47-10

I do have a global date format of the following: yyyy-mm-dd
There are no "local" overrides for my DB connection, they all use the global setting.

Also, the "Sample" textbox, which shows an example date, is showing a wrong date, please see screenshot attached.

![image](https://user-images.githubusercontent.com/20456094/32719850-ff02c408-c861-11e7-8007-3c0663448f84.png)

It's an Oracle 12c DB connection, I'm using newest DBeaver version (4.2.5), and I believe it has been introduced with this version. From 4.2.5 changelog:

- Oracle: DATE data type support was fixed

**Comment by serge-rider** [comment] 2017-11-13 10:38
Duplicate of #2510
(yep, it is a bug in 4.2.5)

**Closed by serge-rider** 2017-11-13 10:38 UTC
Labels: bug, duplicate
