### ISSUE TITLE
“Dbeaver” is damaged and can’t be opened. You should move it to the Trash.

### ISSUE THREAD

**Issue by orbanbalage** [serge-rider/dbeaver#216] opened 2016-02-22 16:40 UTC
Tried both .dmg and tar.gz version of 3.6.0, deleted the .dbeaver directory, but I'm still getting this error:

> “Dbeaver” is damaged and can’t be opened. You should move it to the Trash.

If I run: `spctl --asses DBeaver.app`
I'll get: `DBeaver.app: invalid Info.plist (plist or signature have been modified)`

I'm on iOS 10.11.3 (15D21)

**Comment by serge-rider** [comment] 2016-02-22 17:04
Duplicate of  #95
I still have no solution for that (besides workaround in #95)

**Closed** 2016-02-22 19:58 UTC
Labels: duplicate

**Comment by jgroves-hw** [comment] 2016-09-16 22:47
I resolved this by replacing the invalid code signature with a new one with the following command:

`sudo codesign --force --sign - /Applications/DBeaver.app`

OS X will then treat the app as a normal unsigned application and allow you to open it accordingly 

The answer by user495470 in http://apple.stackexchange.com/questions/18306/fixing-a-sealed-resource-is-missing-or-invalid-warning  lead me to this solution.

**Comment by ninoabbate** [comment] 2017-01-10 17:15
I had a similar issue and forcing the code sign wasn't enough to resolve this issue:
```sudo codesign --force --sign - /Applications/DBeaver.app
/Applications/DBeaver.app: replacing existing signature
/Applications/DBeaver.app: resource fork, Finder information, or similar detritus not allowed
```
So I've followed this: https://developer.apple.com/library/content/qa/qa1940/_index.html  
```
xattr -cr /Applications/DBeaver.app
sudo codesign --force --sign - /Applications/DBeaver.app
```
And I have resolved the issue.

**Comment by nasht00** [comment] 2017-05-07 06:54
This is an old issue, yet it still happens to me every time I upgrade DBeaver.
I have to do the above workaround.
Is there a long term fix?

**Comment by SiNaPsEr0x** [comment] 2017-05-12 18:23
working metod of ninoabbate

**Comment by serge-rider** [comment] 2017-05-14 18:07
Version 4.0.7 will use new DMG installer. Hopefully this will resolve most of problems.

**Comment by kgdpevj** [comment] 2021-02-01 03:46
> This is an old issue, yet it still happens to me every time I upgrade DBeaver.
> I have to do the above workaround.
> Is there a long term fix?

I solved this issue after I execute `xattr -cr /Applications/DBeaver.app` .
Good luck
