### ISSUE TITLE
Problem after migration from 3.x to 4.x

### ISSUE THREAD

**Issue by mystdeim** [serge-rider/dbeaver#1306] opened 2017-02-22 07:45 UTC
After upgrade to 4.x version I get exception when I try to connect to oracle DB.
I use oracle 11c express ediotion and ojdbc6. Postgresql works ok

> 2017-02-22 09:43:53.619 - Connection failed (oracle_thin-157ad5a2014-5fdb7df8c9dcb0f6)
2017-02-22 09:43:53.621 - org.jkiss.dbeaver.DBException: Internal error connecting to Oracle - Nq
org.jkiss.dbeaver.DBException: Internal error connecting to Oracle - Nq
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:766)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:73)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:101)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:105)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.initConnection(DataSourceDescriptor.java:641)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:121)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:187)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:560)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:85)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.initializeContextState(OracleDataSource.java:144)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:119)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeMainContext(JDBCDataSource.java:117)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:111)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:100)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.<init>(OracleDataSource.java:80)
	at org.jkiss.dbeaver.ext.oracle.OracleDataSourceProvider.openDataSource(OracleDataSourceProvider.java:131)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:715)
	... 14 more

**Comment by serge-rider** [comment] 2017-02-22 07:48
Duplicate of #1284.
Version 4.0.1 was just released - it fixes this problem.

**Closed by serge-rider** 2017-02-22 07:48 UTC
Labels: bug, duplicate
