### ISSUE TITLE
Letters being digited when edit a cell are put into the cell value in wrong order in SQL Server

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [serge-rider/dbeaver#539] opened 2016-06-14 14:47 UTC
If I perform a select, and then I want to edit a cell value, I click the cell value once, just to select it, and start typing `Created` in my case, so `Shift + C`, then `R`, and so on.

The cell enters in edit mode while I'm doing so, but the value that's been displayed is `recated`

This is not happening when I double-click the cell to enter in edit mode before start typing

**Comment by williamokano** [comment] 2016-06-17 18:11
:+1: 

This happen to me too. I have to type twice the first character.

**Comment by gabriele-ricci-kyklos** [comment] 2016-09-15 15:08
I'm still experimenting this issue in version 3.7.3

**Comment by serge-rider** [comment] 2016-09-15 15:37
Paste command (cell redraw) will be fixed in the next version, thanks for report.
But i can't reproduce this double-type problem. What happens if you just type one letter?

**Comment by gabriele-ricci-kyklos** [comment] 2016-09-15 15:44
If I just type one letter it works fine. I don't understand what you mean with double-type problem (sorry, I'm not native english)

**Comment by serge-rider** [comment] 2016-09-15 15:49
Sorry, that's another issue with double-type (you had to type a letter twice).

So you problem looks exactly as described above - when you quickly type `Created` it turns into `recated`? (or something similar).
I fixed this one a time ago and can't reproduce it now.

**Comment by gabriele-ricci-kyklos** [comment] 2016-09-15 15:59
Yes it's exactly as I explained in the first post. Plus I just found out the copy-paste issue

**Comment by serge-rider** [comment] 2016-09-15 17:42
What's your OS?

**Comment by serge-rider** [comment] 2016-09-15 18:30
Although I can't reproduce that I'll try a couple of other tricks..

**Comment by gabriele-ricci-kyklos** [comment] 2016-09-16 09:50
My OS is Windows 10 Enterprise N

**Comment by gabriele-ricci-kyklos** [comment] 2016-09-30 14:27
I'm sorry to tell you that I still have this problem after updating to the latest version

**Comment by serge-rider** [comment] 2016-09-30 15:58
Well, I eventually reproduced that on another machine (Windows 7). This issue is very OS/hardware dependent (because it was about keyboard events processing).
Anyhow, I have fixed inline editors activation strategy. Now it should work fine.

**Closed** 2016-09-30 22:01 UTC
Labels: bug

**Comment by gabriele-ricci-kyklos** [comment] 2016-10-14 12:50
I can confirm that this issue has been fixed! Special thanks

**Comment by gabriele-ricci-kyklos** [comment] 2016-12-06 09:13
I have to report an issue related to this. When I type into the cell in upper case (pressing Shift), the programs shows me as lower case

**Comment by serge-rider** [comment] 2016-12-06 09:35
Yep. Will fix that.
