### ISSUE TITLE
DB2 iSeries: foreign keys missing (with metadata source=0)

### ISSUE THREAD

**Issue by xantari** [serge-rider/dbeaver#1349] opened 2017-02-24 15:32 UTC
In 4.0.1 the Foreign Keys on IBM DB2 (IBM i OS) do not show up for tables that do have foreign key relationships.

**Comment by serge-rider** [comment] 2017-02-24 16:07
Can't reproduce.
Please clarify. You don't see foreign keys in table properties? Or no FK navigation in data results?

**Comment by xantari** [comment] 2017-02-27 19:07
The foreign keys do not show up in the Database Navigator even though there are foreign keys:

![image](https://cloud.githubusercontent.com/assets/6610039/23375319/8698514e-fced-11e6-94d6-d449a003078c.png)

I did confirm that "read table references (foreign keys) is marked:

![image](https://cloud.githubusercontent.com/assets/6610039/23375335/9b4f4d9a-fced-11e6-9c9d-6ef4323da339.png)

Perhaps I might be missing something on my JDBC driver settings. Is there a way to debug what DBeaver is trying to do to retrieve the foreign keys from the database to see if perhaps an exception is happening that I don't see in the UI?

**Comment by xantari** [comment] 2017-02-27 19:11
Here is what I have for driver properties:

![image](https://cloud.githubusercontent.com/assets/6610039/23375489/2e682c50-fcee-11e6-8016-ece105152222.png)

![image](https://cloud.githubusercontent.com/assets/6610039/23375494/343f590a-fcee-11e6-9ae5-c18ecbef3012.png)

**Comment by xantari** [comment] 2017-02-27 19:16
I believe I may have found something. Here is the error log:

![image](https://cloud.githubusercontent.com/assets/6610039/23375704/e875e448-fcee-11e6-9b3d-2beef3eb4cd4.png)

**Comment by serge-rider** [comment] 2017-02-27 19:19
Looks like some problem with schema list reading.
Please post debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by xantari** [comment] 2017-02-27 19:30
[Logs.zip.zip](https://github.com/serge-rider/dbeaver/files/804792/Logs.zip.zip)

Attached are logs

**Comment by serge-rider** [comment] 2017-02-27 19:53
Interesting.
1. What JDBC driver do you use?
2. Do you see any catalogs and/or schemas in database navigator?

I'm not familiar with DB2 iSeries. Is schema `*USRLIB` has some special meaning?

**Comment by xantari** [comment] 2017-02-27 20:03
JTOpen 7.1 JDBC Driver

I do see all catalogs and schemas in database navigator.

If I knew what it is doing to try find the foreign keys I could try a few things.

*USRLIBL is the user library list. It's basically a list of schemas for my login to put in the "default" list. I'm not sure why it is even looking at that.

**Comment by serge-rider** [comment] 2017-02-27 20:18
Well, I think it tries to find target table for foreign key and doesn't find it. That's why there are no foreign keys.
So, most likely problem is in schemas/tables reading.

I see lots of errors like this:
`Catalog name (ARRTI5) found for schema 'XXXX' while schema doesn't have parent catalog`
JDBC driver says that schema XXXX belongs to catalog ARRTI5 but catalog list is empty.
Do you see catalog ARRTI5 in database navigator? Is it a real catalog?

Also I see a bunch of errors `Schema '*USRLIBL' not found`.
This happens when DBeaver searches for FK target tables. Driver says that target table belongs to schema '*USRLIBL' but there is no such schema.

**Comment by xantari** [comment] 2017-02-27 20:47
ARRTI5 is the "database name". Inside that database contains many Schemas.

I'm not sure why *USRLIBL is saying it is a schema.

What query is it trying to use to find foreign keys? select * from  SYSIBM.SYSRELS or SYSIBM.SYSFOREIGNKEYS?

**Comment by serge-rider** [comment] 2017-02-27 21:16
Is there only one database? Could you post a screenshot of database navigator?

It looks like driver mixes schemas and catalogs. In some cases it reports correct schema name, in others it returns catalog (database) name instead of schema.

I can't say what exactly SQL query executed to read metadata. DBeaver uses JDBC driver API to read this information for DB2 iSeries.

I'll try to make some workaround. Or at least add some extra logging.

**Comment by xantari** [comment] 2017-02-27 21:18
I found that 3.8.3 works correctly. Attached is log from 3.8.3.

[3.8.3 debug logs.zip](https://github.com/serge-rider/dbeaver/files/805026/3.8.3.debug.logs.zip)

I'm going to make connection information and settings exactly same in 3.8.3 and see if I can end up breaking it in 3.8.3 as well. Perhaps there is some combination of settings that messes it up.

**Comment by serge-rider** [comment] 2017-02-27 21:35
So you can see foreign keys in 3.8.3?

Are you 100% sure that you use the same driver version? There are too many differences in these logs.

**Comment by xantari** [comment] 2017-02-27 21:44
It is the same driver version. I found the setting in the JDBC driver that causes this.

If you have metadata source = 0, this problem starts occuring.

If you leave metadata source = -1 (default value) then the problem doesn't occur.

Now the question is what why that settings causes the foreign key lookup to break. Is there some JDBC driver verbose logging flag to turn on somewhere?

**Comment by xantari** [comment] 2017-02-27 21:48
I just noticed something. The recommended JTOpen driver that DBeaver installs is 7.1, latest version is 9.2.

Trying to see if an update to JTOpen fixes this issue.

**Comment by serge-rider** [comment] 2017-02-27 21:53
Hmm. DBeaver uses Maven artifact for iSeries drivers (jtOpen).
Currently it is `dk.kewill.thirdpartymavencentral:jt400-full`.
Probably it should be changed on `net.sf.jt400:jt400`. It has the most recent jtOpen version (9.2).

Could you test it? If it'll work Ok then I'll change default configuration in the next DBeaver version.

**Comment by xantari** [comment] 2017-02-27 22:02
Updated to net.sf.jt400, that does have the latest version.

But error still occurs in that version.

I'm not sure where I should report this, to JTOpen folks, and if so what would I say to them for this?

**Comment by serge-rider** [comment] 2017-02-27 22:06
Ok. But what's the point in setting "metadata source" to 0? 
As I understood everything is fine with default value.

**Comment by xantari** [comment] 2017-02-27 22:07
Interesting. A value of "1" in the metadata source property works as well. So it can be -1, or 1. But not 0.

The problem is, if you leave it at 1 or -1 you loose ability to get column text descriptions. Which I have enabled (feature you added a month or so ago, which is awesome!)

**Comment by xantari** [comment] 2017-02-27 22:10
http://javadoc.midrange.com/jtopen/index.html?com/ibm/as400/access/doc-files/JDBCProperties.html

Metadatasource 0 uses the old mechnism to get column titles. I'm guessing I should be using 1, which is the "newer" method to get column descriptions. But not entirely sure. I tried 1 and it doesn't work.

**Comment by xantari** [comment] 2017-02-27 22:19
In order to give them more information can you tell me what function in the JDBC driver you are calling to get column comments?

**Comment by serge-rider** [comment] 2017-02-27 22:21
The standard one.
JDBC API function DatabaseMetaData.getColumns, column REMARKS.

**Comment by xantari** [comment] 2017-02-27 22:28
Thanks, and which function are you calling to get Foreign keys?

**Comment by serge-rider** [comment] 2017-02-27 22:41
DatabaseMetaData.getImportedKeys

**Comment by xantari** [comment] 2017-02-27 22:42
Great, thanks!

**Comment by xantari** [comment] 2017-02-27 22:43
Closing issue as it appears to be JTOpen issue.

**Comment by xantari** [comment] 2017-02-28 16:51
I think I should reopen this.

I did a bit more digging, and setup the same JDBC connection properties with SQL Workbench, and it is able to show the comments AND foreign keys without issue.

Is it possible to put in more logging statements to find out where this error is happening?

I turned on JDBC tracing and it seems like this might actually be occuring somewhere in DBeaver as shown in the follow log that includes the JDBC trace data.

Look at line 6725. Those errors are not actually coming from JDBC, but rather DBeaver is having a hard time interpreting the results coming back from the JDBC driver.

What I believe is happening, is that for some reason the JDBC driver is returning a schema DBeaver is not expecting. Rather than ignoring it and moving on, it errors and stops processing, and thus no foreign keys are displayed.

Here is a link to the logs: [https://drive.google.com/open?id=0B__g7EhWQEETM08tN08wcFJyeU0 ](https://drive.google.com/open?id=0B__g7EhWQEETM08tN08wcFJyeU0 )

**Comment by serge-rider** [comment] 2017-03-01 20:25
Unfortunately logs do not contain anything new. Still the same errors about schema *USRLIBL.

I'm pretty sure that I can make it work but I need to know metadata structure. It obviously differs from what DBeaver expects (and most likely isn't JDBC compliant). But almost any metadata, even corrupted, can be loaded with some workarounds.

I can give you JDBC dumper utility which will tell what exactly is returned by jtOpen driver. Then you can send me this log. Write me on serge@jkiss.org (I believe your detailed schema information isn't public).

**Comment by serge-rider** [comment] 2017-03-02 19:27
Fix committed. Actually it is a bug in jtOpen driver (wrong FK schema) so this fix is a workaround.
You can test it in EA version (http://dbeaver.jkiss.org/files/ea/).

**Comment by xantari** [comment] 2017-03-02 23:41
Agreed, I will update jtopen bug with more info so they can fix it

Matt

**Comment by serge-rider** [comment] 2017-03-03 09:51
So, does it work now?

**Closed** 2017-03-07 22:00 UTC
Labels: enhancement

**Comment by xantari** [comment] 2017-03-08 15:55
Sorry for the late reply. The EA version does fix the issue. Thank you so much!
