### ISSUE TITLE
Currently open SQL editor returns error after deleting connections

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#1887] opened 2017-07-15 17:15 UTC
1. open a SQL editor
2. delete current connection

Error: `Factory org.jkiss.dbeaver.ui.editors.DatabaseEditorInputFactory returned null from createElement for editor id=org.jkiss.dbeaver.ui.editors.entity.EntityEditor name=null`

**Comment by serge-rider** [comment] 2017-07-26 20:13
Can't reproduce. In my env SQL editor just closes when you delete connection. In fact this is also not correct behavior (it should just set current connection to None). I'll fix this.

Anyhow - please post error stacktrace. Maybe I have different configuration/something and bug you reported is still there.

**Comment by GiantCrocodile** [comment] 2017-07-26 20:23
I can't reproduce this with v4.1.1 anymore. Maybe it was a side-effect of some other bug.

**Comment by serge-rider** [comment] 2017-07-26 21:27
Ok, closing.
Thanks for report anyway.

**Closed by serge-rider** 2017-07-26 21:27 UTC
Labels: bug, can't reproduce
