### ISSUE TITLE
jdbc driver error SQL Editor when IF-THEN statements

### ISSUE THREAD

**Issue by ilya-merkushin** [serge-rider/dbeaver#2241] opened 2017-10-01 10:54 UTC
DBeaver 4.2.1 
Next function works properly in pgAdmin, but not in DBeaver.

`
CREATE OR REPLACE FUNCTION public.get_test(_id integer)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
begin
	if _id > 0 
	then
		RAISE NOTICE '>0'; 
	else
    	RAISE NOTICE '<=0'; 
	end if;
END;
$function$;
`

<img width="709" alt="sql err" src="https://user-images.githubusercontent.com/12416592/31053841-68314ed2-a6bf-11e7-9bf9-e9bd041941bf.PNG">

**Comment by serge-rider** [comment] 2017-10-01 12:25
Duplicate of #2206.
See fix in 4.2.2

**Closed by serge-rider** 2017-10-01 12:25 UTC
Labels: bug, duplicate
