### ISSUE TITLE
Launch ssh command in before connect not working

### ISSUE THREAD

**Issue by BriceJamin** [serge-rider/dbeaver#1669] opened 2017-05-17 13:39 UTC
Hi,
If I launch this command in shell (not in DBeaver) 
`ssh -L 3133:ip:5433 user@server -N`
And I click on Test connection in DBeaver, it works.

If I kill my command in shell, add in DBeaver same command in "Before Connect" and click on Test connection, it not works.
I have this error 

> Connection to 127.0.0.1:3133 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
>   java.net.ConnectException: Connexion refusée (Connection refused)

Version of DBeaver I use : dbeaver-ce_4.0.7_amd64.deb

**Comment by serge-rider** [comment] 2017-05-20 14:45
Probably this happens because DBeaver doesn't make any pause before ssh command execute and connection attempt (so SSH doesn't have a chance to establish tunnel before db connect).
I've added extra config parameters:
![default](https://cloud.githubusercontent.com/assets/6398845/26276651/f39d6eb0-3d83-11e7-8f63-992e063ff01c.png)

Try this in 4.1.0.

**Comment by serge-rider** [comment] 2017-05-20 14:51
BTW do you have issues with DBeaver embedded SSH support?

**Comment by BriceJamin** [comment] 2017-05-20 17:16
Thank you for your work.
I understand why it's not work now.
I will able to do some tests next week.
I'll keep you informed.

**Comment by BriceJamin** [comment] 2017-05-30 13:28
> BTW do you have issues with DBeaver embedded SSH support?

I don't know how to use UI for this ssh connexion exemple : 
`ssh -L 3133:ip:5433 user@server -N`
Is it possible ?

It's why I try to use Shell command before connect.
A call to a script permit to change behavior without manually UI change.

To try, I try to call this script "/home/bja/Documents/DBeaver/test.bash"
```
#!/bin/bash

file="/home/bja/Documents/DBeaver/it_works"
localport=""
ip=""
serverport=""
user=""
server=""

(ssh -L $localport:$ip:$serverport $user@$server -N &) 2>&1 >$file
sleep 10
echo "process found : " > $file
ps -ef | grep "$user@$server" | grep -v 'grep' >> $file
echo end >> $file
```
If I execute this script manually in shell, it create new file it_works, with this result 

> process found :
bja      32173 32172  0 15:06 pts/1    00:00:00 ssh -L XXXX:ip:YYYY user@server -N
end

If I execute this script by DBeaver, I use this configuration
![beforeconnect](https://cloud.githubusercontent.com/assets/3600741/26583317/06971e62-4545-11e7-8638-6eb6ef0f70de.png)
When I click on Test connection, it create new file it_works, which contains 

> process found : 
end

For any reason, process is not born...
I don't understand why.

**Comment by serge-rider** [comment] 2017-05-30 18:34
You need to run `sh <script path>` or `bash <script path>`.

4.0.8 will be released tomorrow.

**Comment by BriceJamin** [comment] 2017-05-31 06:23
With 4.0.7 and 4.0.8 I obtain same error result when I use `bash <script path>`
With 4.0.8 when I use command `ssh -L 3133:ip:5433 user@server -N` instead of `bash <script path>` and use new UI _Pause after execute_ with `2000` value, I obtain same error as described in first post.

**Comment by serge-rider** [comment] 2017-05-31 06:58
Try to specify executable full path (e.g. `/usr/bin/bash`).
Also you can open process panel and see its output.

**Comment by BriceJamin** [comment] 2017-05-31 07:39
> Try to specify executable full path (e.g. /usr/bin/bash).

```
bja@debian:~/Documents/DBeaver$ whereis bash
bash: /bin/bash /etc/bash.bashrc /usr/share/man/man1/bash.1.gz
```
So i add /bin/bash
But same error/result

> Also you can open process panel and see its output.

I found process panel in 
![showview](https://cloud.githubusercontent.com/assets/3600741/26620879/e36bf7a0-45e4-11e7-82d8-376d925809d4.png)

![other](https://cloud.githubusercontent.com/assets/3600741/26620899/f334e9b2-45e4-11e7-923b-114e646f02a8.png)

![process](https://cloud.githubusercontent.com/assets/3600741/26620888/e8e0c5a8-45e4-11e7-9eac-1a95dfb8f8c2.png)

But it is empty.

**Comment by serge-rider** [comment] 2017-06-25 15:39
I can't reproduce the problem with ssh tunnel. It works just fine even without any timeout.

Note: you must use private key auth otherwise ssh will stuck in password prompt. Generally shell command shouldn't try to interact with user thru console.

However error logging has to be improved (currently it is very hard to understand what is going on if something went wrong).

**Comment by serge-rider** [comment] 2017-06-25 18:10
Additional logging was added (process stderr will be dumped into DBeaver debug log)

**Closed by serge-rider** 2017-06-25 18:10 UTC
Labels: bug, can't reproduce

**Comment by programus** [comment] 2019-10-31 06:44
@serge-rider I have the same problem and google search brought me to this issue. 
In my case, I have to jump two servers to make an ssh tunnel, so I don't think the UI ssh tunnel settings could accomplish this. 

I set up the two server jump tunnel in my .ssh/config like this:

```
Host my-tunnel
  HostName xxx.xxx.xxx.6
  User user-a
  ProxyCommand sshpass -ppassword-a ssh user-b@xxx.xxx.xxx.145 -W %h:%p
```

and I put this command in the following command into the Before Connect
```
ssh my-tunnel -L 5439:d-server:5439
```

Then I got this connection refused error: 
```
Connection to localhost:5439 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
  Connection refused (Connection refused)
  Connection refused (Connection refused)
```

The same as @BriceJamin 's case, if I execute the same command in my terminal, I can connect to the database. 

I also tried the pause time. But I found that it seems pause before the command is executed instead of between the command execution and the connection, because the Process Panel show after the pause time. 

Any advice to help me out? No matter the command or the UI setting. 

I am using Version 6.2.3.201910201831 macos. installed from dmg.

**Comment by metanerd** [comment] 2021-01-05 21:31
Thank you for DBeaver :heart: !
I run into the same problem on linux. I am trying to run an elaborate vault command to ssh into a machine. I wanted to run the ssh command instead of painfully figuring out the right cert for the right form field. I don't see any output in the checked process panel that the command gets run. Playing around with the timing for vault/ssh to give the command enough time to connect don't seem to yield results. 

Edit: Ah, :facepalm: I have to try with the tunnel. Thank you!

**Comment by davideasaf** [comment] 2021-10-30 18:44
**Environment**: macOS
Other Details: 
- Normally in my terminal i use OH MY ZSH
- I wrote a dbeaver.sh script to call from "Shell Commands" in Dbeaver
- I called that .sh command via: `/bin/bash dbeaver.sh`

FWIW, 

I had a lot of issues trying to leverage commands within the shell executor that DBeaver started. It all came down to Dbeaver starting a shell execution with a different $PATH than my usual. 

standard PATH within running script: `/usr/bin:/bin:/usr/sbin:/sbin`

**Comment by blandong** [comment] 2022-06-17 19:50
@BriceJamin,
I'm facing the same issue as yours with Dbeaver Version 22.0.0.202203060510 in Mac, did you solve the issue, if yes, would you please help tell me how?

**Comment by BriceJamin** [comment] 2022-08-05 12:57
> @BriceJamin, I'm facing the same issue as yours with Dbeaver Version 22.0.0.202203060510 in Mac, did you solve the issue, if yes, would you please help tell me how?

Hello, sorry I never try again since I don't need it, and I forget it.

By reading last comment I think (not sure) it comes from my ssh key which need a passphrase entry.
Perhaps checking if your ssh key use passphrase and using last loging improvment can help you ?

I don't remenber why I need to use `ssh -L 3133:ip:5433 user@server`
I'm asking too if using
`Host *
 ForwardAgent yes`
in my ssh config file can avoid facing this kind of need.

**Comment by toonerd** [comment] 2023-09-30 17:53
> BTW do you have issues with DBeaver embedded SSH support?

Yes:
1. Not supporting aliases
It cannot use aliases defined in `~/.ssh/config`
So, each time a connection gets change in that file, DBeaver configs should be modified too.
I prefer defining connections in that file and mention their aliases in all other apps, so I should change only one file each time changing a connection.
2. Missing `${datasource}`
`${datasource}` has no value in embedded SHH tab, while it has a value in "Shell Commands".

**Comment by birkenbach** [comment] 2024-07-24 08:58
For OSX it helped me to run an apple script to start the shell script. It is a bit odd, however it worked:

osascript -e 'tell app "Terminal" to do script "YOUR_EXECUTABLE_SCRIPT_PATH"'
