### ISSUE TITLE
importing data not possible if target column doesnt exist

### ISSUE THREAD

**Issue by farmboy0** [serge-rider/dbeaver#742] opened 2016-09-19 12:35 UTC
I wanted to import data from one table to another.
The tables were mostly identical, only the target table lacked one column
the source table had.
I changed the column mapping to skip that column
nevertheless dbeaver insisted i didnt resolve the mapping for the missing column
and didnt import the data.

**Comment by serge-rider** [comment] 2016-09-19 12:39
Duplicate of #731.
Will be fixed in the next version.

**Closed by serge-rider** 2016-09-19 12:39 UTC
Labels: duplicate
