### ISSUE TITLE
Feature: DBeaver add of zoom with use of Ctrl+Mouse wheel

### ISSUE THREAD

**Issue by pdanie** [serge-rider/dbeaver#2315] opened 2017-10-11 11:25 UTC
DBeaver - **Version 4.2.2 CE**
Operating System: **Windows 7 / Windows 8.1**

I miss the ability to zoom editor window/diagram with the use of Ctrl+MouseWheel.

Compare functionality with _Microsoft Internet Explorer_ or _Notepad++_.

I have mapped the DBeaver zoom functionality with both **Ctrl++**/**Ctrl+Numpad_Add** and **Ctrl+-**/**Ctrl+Numpad_Subtract**. But miss the ability to zoom using **Ctrl+MouseWheel**.

**Comment by serge-rider** [comment] 2017-10-11 15:45
Duplicate of #2273

**Closed** 2017-10-11 20:12 UTC
Labels: question
