### ISSUE TITLE
Hitting assertion failure in Oxygen on 64bit linux (kubuntu 14.04)

### ISSUE THREAD

**Issue by microwheels** [serge-rider/dbeaver#1130] opened 2017-01-08 05:10 UTC
When I try to launch dbeaver enterprise I hit the following assertion error from Oxygen: `java: /build/buildd/gtk2-engines-oxygen-1.4.5/src/animations/oxygencomboboxdata.cpp:87: void Oxygen::ComboBoxData::setButton(GtkWidget*): Assertion `!_button._widget' failed.`

I've tried this with OpenJDK 7 as well as Oracle JDK versions 7 and 8.

**Comment by serge-rider** [comment] 2017-01-08 15:24
Duplicate of #1131

**Closed by serge-rider** 2017-01-08 15:24 UTC
Labels: duplicate, question
