### ISSUE TITLE
[feature] CSV import with creating table

### ISSUE THREAD

**Issue by offstate** [serge-rider/dbeaver#2415] opened 2017-10-26 00:12 UTC
Sometimes I have a table with data (csv/xls) that I need to load to DB and make some queries with existing tables. 
It would be great to import csv file as one operation using wizard.
The wizard would request table name, read column names from the first line of the file and allow to change their types, allow to append primary key and finally create the table filled with data.

**Comment by serge-rider** [comment] 2017-11-09 22:10
Duplicate of #130
We going to add this feature in 4.2.6

**Closed by serge-rider** 2017-11-09 22:10 UTC
Labels: duplicate, feature request

**Comment by JivanRoquet** [comment] 2020-04-17 08:49
@serge-rider I'm using 7.0 and can't see this feature anywhere — neither in docs, nor in searching the menus. Has it been implemented and/or documented?

**Comment by JivanRoquet** [comment] 2020-04-17 08:53
Also @serge-rider I don't see this issue as being a duplicate of #130 at all.

Issue #130 is about adding a flat-file (like csv) option when importing into an existing table.

This present issue (#2415) is about *creating a table* while importing a flat-file.

**Comment by p91paul** [comment] 2020-04-18 20:45
You can do it by creating a CSV data source and exporting data from the csv table to a new database table.
Otherwise I suggest you create a new issue, commenting on closed ones can be easily overlooked by the developers.
