### ISSUE TITLE
Problem when installed on win and profile has spaces

### ISSUE THREAD

**Issue by marinamarinina-biz** [serge-rider/dbeaver#504] opened 2016-06-01 10:05 UTC
Have a problem when it installed on windows and profile has spaces.
After installed DBeaver 3.6.9 it was created a new profile folder where spaces are encoded as '%20'.
It is reset all settings, because previous settings are in the other folder.

Example:
Profile name 'Sergey and Marina' become as 'Sergey%20and%20Marina' folder where only new '.dbeaver' folder placed.

P.S. Thank you for DBeaver developing, support and maintenance!

**Comment by serge-rider** [comment] 2016-06-01 10:26
Seems to be duplicate of  #504. 
Or at least it is a very similar problem.
Is this a 3.6.9 problem?

**Comment by marinamarinina-biz** [comment] 2016-06-01 11:09
Yes, only 3.6.9
3.6.6 works fine

**Comment by serge-rider** [comment] 2016-06-01 12:04
Please try EA version:
http://dbeaver.jkiss.org/files/ea/

**Comment by carlosjrcabello** [comment] 2016-06-01 12:16
@marinamarinina-biz, 

See my comment and checks if you got the same problem as described here:

https://github.com/serge-rider/dbeaver/issues/495#issuecomment-222972278

**Comment by serge-rider** [comment] 2016-06-01 12:18
Closing it as a duplicate

**Closed by serge-rider** 2016-06-01 12:18 UTC
Labels: bug, duplicate
