### ISSUE TITLE
Problem with PostgreSql and Foreign Table

### ISSUE THREAD

**Issue by FabFederer** [serge-rider/dbeaver#275] opened 2016-03-11 08:00 UTC
Since version 3.6.0 it's not possible to see the list of postgresql foreign table in the table folder on the database navigator tree.
The error windows shows:
Unsupported PostgreClass 'f'

**Comment by infectormp** [comment] 2016-03-11 08:53
Duplicate of https://github.com/serge-rider/dbeaver/issues/264

**Closed** 2016-03-11 09:02 UTC
Labels: duplicate
