### ISSUE TITLE
How export all [schema + data] to other database PostgreSQL

### ISSUE THREAD

**Issue by mateuspadua** [serge-rider/dbeaver#879] opened 2016-10-24 02:22 UTC
I tried to do it all at once, but it was not possible.
First, because I can only create the tables to another schema. And after created tables, it does not export the data.

![dbeaver](https://cloud.githubusercontent.com/assets/515075/19631891/dc6d8638-997f-11e6-8a6a-6e290f7b3698.png)

In the second time that I tried, the tables were created then I can export the data, but the foreign keys were not created.

![dbeaver_2](https://cloud.githubusercontent.com/assets/515075/19632035/40ed9494-9981-11e6-9da2-dfd0465b84a7.png)

I wanna to know if is possible export at once [schema + data] to annother PostgreSQL database?
And the fact that not create the foreign Keys after created tables, I guess this is a bug.

Thanks and sorry my english, :)

**Comment by serge-rider** [comment] 2016-10-31 17:33
I think this is the duplicate of #796. Full database export/import can be accomplished by PG command line tools. Going to add this feature in 3.8.

**Closed** 2016-11-12 21:30 UTC
Labels: duplicate, question

**Comment by mateuspadua** [comment] 2016-11-17 10:55
Thanks for reply, i will wait for version 3.8 to use this feature.
