### ISSUE TITLE
Double-clicking a database table in Database Navigator no longer opens table for editing

### ISSUE THREAD

**Issue by zejji** [serge-rider/dbeaver#2216] opened 2017-09-27 10:02 UTC
Since version 4.2.1, double-clicking a database table name in the Database Navigator no longer opens the table for editing, but rather expands the entry for table in the Database Navigator.

In my view, this is a definite regression and an unnecessary duplication of existing functionality - if the user wanted to expand the entry in the Database Navigator, they would click on the arrow button to the left of the table name. To edit the table / view table data (which is the more commonly required action), the user now has to right-click on the table and select 'Edit Table'.

Please could you revert this to the old behaviour?

**Comment by serge-rider** [comment] 2017-09-27 10:26
Duplicate of #2214 
See fix in the next version

**Closed by serge-rider** 2017-09-27 10:26 UTC
Labels: duplicate, question

**Comment by zejji** [comment] 2017-09-27 10:39
Ah, that's great - thanks
