### ISSUE TITLE
Informix table information: Triggers

### ISSUE THREAD

**Issue by amivanovano** [serge-rider/dbeaver#1982] opened 2017-08-08 09:20 UTC
When I cliсked on Tab Triggers error occured:
**Number of input values does not match number of question marks**
It happens always.

eclipse.buildId=unknown
java.version=1.8.0_111
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ru_RU
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Aug 08 12:16:59 MSK 2017
Number of input values does not match number of question marks

java.sql.SQLException: Number of input values does not match number of question marks
	at com.informix.util.IfxErrMsg.buildException(IfxErrMsg.java:474)
	at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:443)
	at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:394)
	at com.informix.jdbc.IfxPreparedStatement.checkParameterIndex(IfxPreparedStatement.java:2462)
	at com.informix.jdbc.IfxPreparedStatement.setString(IfxPreparedStatement.java:1220)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.setString(JDBCPreparedStatementImpl.java:351)
	at org.jkiss.dbeaver.ext.informix.model.InformixMetaModel.loadTriggers(InformixMetaModel.java:80)
	at org.jkiss.dbeaver.ext.generic.model.GenericTable.loadTriggers(GenericTable.java:450)
	at org.jkiss.dbeaver.ext.generic.model.GenericTable.getTriggers(GenericTable.java:444)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:793)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:479)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:403)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:190)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:563)
	at org.jkiss.dbeaver.ui.controls.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:229)
	at org.jkiss.dbeaver.ui.controls.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by amivanovano** [comment] 2017-08-08 09:24
It happens always.

**Comment by serge-rider** [comment] 2017-08-08 09:34
Duplicate of #1968

**Closed by serge-rider** 2017-08-08 09:34 UTC
Labels: bug, duplicate
