### ISSUE TITLE
Hot key: Ctrl + Alt + S (Delete recored) not working

### ISSUE THREAD

**Issue by QSnake1308** [serge-rider/dbeaver#1260] opened 2017-02-14 02:46 UTC
Hello, Thanks for your awesome work.
I selected some recored and press Alt + Delete for deleting these, this worked, but when it came to save deleted records, I pressed Ctrl + Alt + S but it didn't work?

**Comment by serge-rider** [comment] 2017-02-14 10:00
Does clicking on "Save" button work?
Does CTRL+ALT+S works in table data editor?

**Comment by QSnake1308** [comment] 2017-02-21 07:59
Does clicking on "Save" button work? <<< Work
Does CTRL+ALT+S work in table data editor? <<< I tried but still didn't

**Comment by anophelesgreyhoe** [comment] 2017-02-28 22:10
I also have this issue with Ubuntu 16.04 under the Unity desktop environment.

I have checked and can't find any Ubuntu hotkeys that might be intercepting CTRL+ALT+s.

**Comment by anophelesgreyhoe** [comment] 2017-03-10 18:55
I've found that on my home system which runs Debian 9 with the i3 Window Manager, CTRL+ALT+S works fine.

I will try again on my work PC under a different WM as I suspect it could be related to Unity.

**Comment by anophelesgreyhoe** [comment] 2017-03-28 21:56
@QSnake1308 can you try holding CTRL+ALT+S for about 2 seconds.

I found that on Ubuntu with the Unity desktop that works for me, whereas if I just press the keys quickly it doesn't register.

@serge-rider not sure if this is something that could be coded around, or just a fact we have to live with when using some desktop environments under Linux.

**Comment by QSnake1308** [comment] 2017-03-29 02:27
@anophelesgreyhoe Wow, holding CTRL+ALT+S for about 2 seconds works. This is a little weird right! :)

**Comment by Robust1308** [comment] 2017-05-31 04:37
CTRL+ALT+S now works perfectly, no more waiting :+1:

**Comment by serge-rider** [comment] 2017-05-31 05:29
Great. 
Closing. Please reopen if this is still reproducible in some environments.

**Closed by serge-rider** 2017-05-31 05:29 UTC
Labels: question
