### ISSUE TITLE
postgres arrays

### ISSUE THREAD

**Issue by vladojr** [serge-rider/dbeaver#460] opened 2016-05-19 12:09 UTC
arrays in postgres are treated as stitngs

- exports
- imports
- edit

**Comment by serge-rider** [comment] 2016-05-19 12:57
Duplicate of #403 
This is not PostgreSQL specific (although it assumes special handler in PG extension).

**Closed by serge-rider** 2016-05-19 12:57 UTC
Labels: duplicate

**Comment by vladojr** [comment] 2016-05-19 13:11
Hi Serge, please note also the export problem, not just editing. When I
array values It can not be imported.

Appreciate your efforts, thank you

On Thu, May 19, 2016 at 2:57 PM, Serge Rider <notifications@github.com>
wrote:

> Closed #460 <https://github.com/serge-rider/dbeaver/issues/460>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/serge-rider/dbeaver/issues/460#event-665754762>
>



-- 
S pozdravom
Vladimír Houba ml.
