### ISSUE TITLE
Oracle procedure error PLS-00103

### ISSUE THREAD

**Issue by lisdoo** [serge-rider/dbeaver#950] opened 2016-11-08 06:24 UTC
I execute this procedure: 

declare 
  var_level_no NUMBER;
begin
  for var_level_no in 1..10 LOOP
    DBMS_OUTPUT.PUT_LINE('-------------------');
  END LOOP;
end;

And it reports me this error:
PLS-00103

I found log record with:
declare 
  var_level_no NUMBER;
begin
  for var_level_no in 1..10 LOOP
    DBMS_OUTPUT.PUT_LINE('------------------');
  END LOOP;

It shows the procedure was not complete, the last line "END;" was absenced.

**Comment by serge-rider** [comment] 2016-11-08 21:08
Duplicate of #907

**Closed by serge-rider** 2016-11-08 21:08 UTC
Labels: duplicate, question

**Comment by lisdoo** [comment] 2016-11-09 03:40
thx
