### ISSUE TITLE
ODBC connection failed : Version 4.0.0

### ISSUE THREAD

**Issue by Wespontin** [serge-rider/dbeaver#1296] opened 2017-02-21 08:00 UTC
Hello,
Since the last update, i can't connect with ODBC.
![image](https://cloud.githubusercontent.com/assets/21580607/23155742/32564bc8-f814-11e6-9ae1-827be7b04f2e.png)
Thanks for help

**Comment by dalbocha** [comment] 2017-02-22 06:35
I'm having the same error while connecting to Oracle DB with DBeaver application

**Comment by Wespontin** [comment] 2017-02-22 09:52
I put the update 4.0.1 but the problem always exists

**Comment by serge-rider** [comment] 2017-02-22 10:00
Can't reproduce.
Please post error stacktrace (you can get it in Error Log view)

**Comment by ferrazp** [comment] 2017-02-22 12:03
4.0.1 works fine, i had oracle issue too but with 4.0.1 no more. Sorry for my bad english

**Comment by serge-rider** [comment] 2017-02-22 12:04
I think this is duplicate of #1312.
Looks like some problems with particular ODBC driver..

**Closed by serge-rider** 2017-02-22 12:04 UTC
Labels: bug
