### ISSUE TITLE
Autocomplete doesn't work on aliases

### ISSUE THREAD

**Issue by urbain37** [serge-rider/dbeaver#483] opened 2016-05-25 12:55 UTC
Updated to 3.6.8 and using DB2. 

Autocomplete doesn't work on aliases (used to work on 3.6.4). 

Example: 
select (autocomplete work)
from client

select c.(autocomplete doesn't work)
from client c

**Comment by serge-rider** [comment] 2016-05-25 13:06
Duplicate of #467

**Closed by serge-rider** 2016-05-25 13:06 UTC
Labels: bug, duplicate
