### ISSUE TITLE
ConcurrentModificationException while renaming constants

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#1009] opened 2016-11-29 08:59 UTC
1. Create a constant like a unique or primary key
2. Rename this constant before saving
3. ConcurrentModificationException occurs.

**Comment by serge-rider** [comment] 2016-11-30 12:40
Can't reproduce.
What is your database?
Could you post error stacktrace?

**Comment by GiantCrocodile** [comment] 2016-11-30 16:47
I'm using MariaDB. I think it could be necessary for reproduction to create an unique or primary key with a name that already exists. After you click on it to rename it, you get this ConcurrentModificationException.

According to error view: 'An exception stack trace is not available.'

**Comment by serge-rider** [comment] 2016-11-30 17:00
I still can't reproduce (i.e. I can rename constrains without errors).
If there are multiple errors (or error hierarchy) in the list you can click on the next one - one of them should have stacktrace.

**Comment by GiantCrocodile** [comment] 2016-11-30 17:26
If there are multiple errors - are they only logged from the current session of using DBeaver or are there old errors logged too? Because if it is not old errors, this has 3 - 4 other errors.

**Comment by serge-rider** [comment] 2016-11-30 17:37
There are errors from all sessions. Unless you have cleared the log.
Just find any error with ConcurrentModificationException in it.

**Comment by GiantCrocodile** [comment] 2016-11-30 17:59
I got this:
'Some data source listeners are still registered: [org.jkiss.dbeaver.ui.editors.entity.properties.TabbedFolderPageProperties@674546ea, org.jkiss.dbeaver.ui.editors.entity.properties.TabbedFolderPageProperties@7f9c5c04]' as a warning and:

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.setCache(JDBCCompositeCache.java:214)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceEditable.setPropertyValue(PropertySourceEditable.java:124)
	at org.jkiss.dbeaver.ui.controls.itemlist.ItemListControl$CellEditingSupport.setValue(ItemListControl.java:243)
	at org.eclipse.jface.viewers.EditingSupport.saveCellEditorValue(EditingSupport.java:113)
	at org.eclipse.jface.viewers.ColumnViewerEditor.saveEditorValue(ColumnViewerEditor.java:463)
	at org.eclipse.jface.viewers.ColumnViewerEditor.applyEditorValue(ColumnViewerEditor.java:319)
	at org.eclipse.jface.viewers.ColumnViewerEditor$2.applyEditorValue(ColumnViewerEditor.java:158)
	at org.eclipse.jface.viewers.CellEditor$1.run(CellEditor.java:336)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.CellEditor.fireApplyEditorValue(CellEditor.java:333)
	at org.eclipse.jface.viewers.TextCellEditor.handleDefaultSelection(TextCellEditor.java:298)
	at org.eclipse.jface.viewers.TextCellEditor$1.widgetDefaultSelected(TextCellEditor.java:147)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:119)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4481)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1329)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3819)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3430)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:208)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
```

Can you try to rename a constant like I said before but pressing ENTER to confirm the name instead of clicking somewhere else? This triggers it more often to me.

**Comment by serge-rider** [comment] 2016-11-30 18:09
Thanks, now I can reproduce that.
Fix will be in the next version.

**Comment by GiantCrocodile** [comment] 2016-11-30 18:10
Thanks @serge-rider for being such an active and really nice maintainer of such a good software! I really appreciate your fast fixes and your commitment.

**Comment by serge-rider** [comment] 2016-11-30 18:53
You are welcome)

**Closed by serge-rider** 2016-11-30 18:53 UTC
Labels: bug
