### ISSUE TITLE
Keyspaces nodes duplication

### ISSUE THREAD

**Issue by SZubarev** [serge-rider/dbeaver#1358] opened 2017-02-28 00:44 UTC
If I right click "Refresh" in Database Navigator window while connected to Cassandra DB it shows duplicated keyspace nodes in the Database Navigator tree after the refresh.

DBeaver EE 3.8.5

**Comment by serge-rider** [comment] 2017-02-28 06:35
Duplicate of #1236

**Closed by serge-rider** 2017-02-28 06:35 UTC
Labels: bug, duplicate
