### ISSUE TITLE
exporting large number of rows to multiple csv files

### ISSUE THREAD

**Issue by cdeterman** [serge-rider/dbeaver#2401] opened 2017-10-23 14:32 UTC
In section 1.7 of the features listed [here](https://dbeaver.jkiss.org/docs/features/) it says:

> You can export data to file(s) or to another database table(s). It is possible to create a new table to export to.

This seems to suggest it is possible to export a large query to multiple files.  Is this possible?  I have been trying to accomplish this as I have a large query that would work best for me to handle in multiple files.

**Comment by serge-rider** [comment] 2017-10-28 21:17
Duplicate of #1646

**Closed by serge-rider** 2017-10-28 21:17 UTC
Labels: duplicate, feature request
