### ISSUE TITLE
Some Postgres relationships don't show on table focussed ER diagrams

### ISSUE THREAD

**Issue by rubenfilteris** [serge-rider/dbeaver#1554] opened 2017-04-09 13:06 UTC
Version 4.0.x (first noticed in the last 3.8.x release)
For Postgres connections only the main schema ERD shows all relationships. When selecting a table, the ERD only shows relationships owned by the table (for MySQL the views work as expected showing both types):

Some Postgres examples: 
For the main database ERD view, the `files_file` table has many outgoing relationships:
<img width="176" alt="screen shot 2017-04-09 at 14 35 04" src="https://cloud.githubusercontent.com/assets/1697731/24837339/63ab9dd4-1d32-11e7-881c-42ebf9fd632b.png">

when viewed from `files_file` table focus, no connections are shown.
<img width="115" alt="screen shot 2017-04-09 at 14 35 28" src="https://cloud.githubusercontent.com/assets/1697731/24837338/63a9c838-1d32-11e7-845f-bf46becc0861.png">

Another example where the main view shows 2 connections on the `actions_email_attatchments` table:
<img width="323" alt="screen shot 2017-04-09 at 14 48 16" src="https://cloud.githubusercontent.com/assets/1697731/24837414/bf1605be-1d33-11e7-93c5-508adc6ea539.png">

When viewed from the `actions_email_attatchments` table view  the connections are shown:
<img width="206" alt="screen shot 2017-04-09 at 14 35 38" src="https://cloud.githubusercontent.com/assets/1697731/24837340/63ac9dce-1d32-11e7-8cfa-d0dc424ffe50.png">

Finally a mixed example where both types of FKs are on the table:
<img width="170" alt="screen shot 2017-04-09 at 14 36 32" src="https://cloud.githubusercontent.com/assets/1697731/24837336/63a569dc-1d32-11e7-9f28-1434e0b2b17a.png">
When this table is viewed in focus only the owned FKs are shown:
<img width="354" alt="screen shot 2017-04-09 at 14 36 41" src="https://cloud.githubusercontent.com/assets/1697731/24837335/63a3462a-1d32-11e7-98e8-2fef4a332205.png">

-------------------------------------

For comparison, here is an example from MySQL working as expected in a similar context. The main ERD shows all connections:
<img width="177" alt="screen shot 2017-04-09 at 14 59 55" src="https://cloud.githubusercontent.com/assets/1697731/24837474/5ed81582-1d35-11e7-880c-37befd15494a.png">
And in the table focussed ERD the connections and associated tables still show up:
<img width="461" alt="screen shot 2017-04-09 at 15 00 11" src="https://cloud.githubusercontent.com/assets/1697731/24837473/5ed06d0a-1d35-11e7-82af-765c2cd18962.png">

**Comment by serge-rider** [comment] 2017-04-09 14:29
Can't reproduce on my test database. 
Maybe problem is in column types or in specific fk definition.

Could you post sample DDL? Here or on serge@jkiss.org

**Comment by rubenfilteris** [comment] 2017-04-09 19:48
Thanks you for looking at this.

I reduced the DDL down to 4 tables and on my install it still shows.  
Postgres version: `psql (PostgreSQL) 9.6.2`

The DDL I used for the screenshot in this comment is:
```SQL
DROP TABLE IF EXISTS dbeaver_test.import_dependant_imports;
DROP TABLE IF EXISTS dbeaver_test.import;
DROP TABLE IF EXISTS dbeaver_test.users_user;
DROP TABLE IF EXISTS dbeaver_test.file; 


CREATE TABLE dbeaver_test.file (
	id int4 NOT NULL,
	CONSTRAINT file_pkey PRIMARY KEY (id)
);

CREATE TABLE dbeaver_test.users_user ( 
    id int4 NOT NULL,
	CONSTRAINT users_user_pkey PRIMARY KEY (id) 
);

CREATE TABLE dbeaver_test.import (
	id int4 NOT NULL,
	created_by_id int4 NULL,
	import_file_id int4 NULL,
	report_file_id int4 NULL,
	CONSTRAINT import_pkey PRIMARY KEY (id),
	CONSTRAINT import_created_by_id_e72bfbc5_fk_users_user_id 
	  FOREIGN KEY (created_by_id) 
	    REFERENCES dbeaver_test.users_user(id),
	CONSTRAINT import_import_file_id_830b6c08_fk_file_id 
	  FOREIGN KEY (import_file_id) 
	    REFERENCES dbeaver_test.file(id) 
);

CREATE TABLE dbeaver_test.import_dependant_imports (
	id int4 NOT NULL ,
	from_import_id int4 NOT NULL,
	to_import_id int4 NOT NULL,
    CONSTRAINT import_dependant_imports_pkey 
      PRIMARY KEY (id),
    CONSTRAINT import_depen_to_import_id_a3a6136d_fk_import_id 
      FOREIGN KEY (to_import_id) 
        REFERENCES dbeaver_test.import(id)
);
```

Result:
<img width="1402" alt="screen shot 2017-04-09 at 21 43 14" src="https://cloud.githubusercontent.com/assets/1697731/24840447/98ac4c5a-1d6d-11e7-8ace-f21b72e34da2.png">

**Comment by rubenfilteris** [comment] 2017-04-09 20:18
FYI: I confirmed the same behaviour on DBeaver 3.7.8  and DBeaver 3.5.1 so it does not seem like a recent regression in DBeaver. Possibly this behaviour is brought about by a Postgres version 9.6.x upgrade. 

(BTW: Going back to the older versions on my machine, I do realise now how much amazing effort has gone into the DBeaver project, and that I have been clicking "update" every time a new version is available without worrying about the new version breaking things. Your project is indeed a great example of KISS continuous improvement. DBeaver "moves fast" with out the "break things" part 👍. Thanks!) 

<img width="957" alt="screen shot 2017-04-09 at 21 58 20" src="https://cloud.githubusercontent.com/assets/1697731/24840588/0fe00e40-1d70-11e7-9862-93853a488817.png">

<img width="1070" alt="screen shot 2017-04-09 at 22 08 30" src="https://cloud.githubusercontent.com/assets/1697731/24840689/cb570038-1d71-11e7-96b0-2db867713732.png">

**Comment by serge-rider** [comment] 2017-04-09 20:44
Thanks for detailed report.
I did find the bug (it was in schema constraints/indexes caching function), it'll be fixed in the next version.

**Closed** 2017-04-12 05:59 UTC
Labels: bug

**Comment by markk-fmi** [comment] 2021-04-23 17:53
I have a similar (maybe worse?) issue with DBeaver 21.0.2.202104042040 and postgres-db, but not with an oracle-db. 

In postgres, if I click a table from the tree, the ER-Diagram shows ONLY that table and NO foreign key relationships, even ones owned by the table.  But if I click the schema, all tables with fk relationships are shown.  E.g. see images below.

In oracle, if I click a table from the tree, the ER-Diagram shows that table in the center with all fk relationships shown in the diagram.

![schema-pg](https://user-images.githubusercontent.com/13799605/115910254-9df3ef80-a43a-11eb-8ba9-780daecfd1a7.jpg)

![table-pg](https://user-images.githubusercontent.com/13799605/115910266-a2b8a380-a43a-11eb-846c-1a4557f3397a.jpg)
