### ISSUE TITLE
Coloring by value crashes with an NPE

### ISSUE THREAD

**Issue by gintas** [serge-rider/dbeaver#319] opened 2016-03-30 17:07 UTC
I noticed an interesting-looking option "View->Color by X", but trying to use it got me a stack trace:

java.lang.NullPointerException
	at org.jkiss.dbeaver.model.virtual.DBVUtils.findVirtualEntity(DBVUtils.java:65)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ColorAction.getVirtualEntity(ResultSetViewer.java:2300)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$SetRowColorAction.run(ResultSetViewer.java:2334)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:110)

**Comment by gintas** [comment] 2016-03-30 17:07
This is DBeaver 3.6.2.

**Comment by serge-rider** [comment] 2016-03-30 17:43
Seems to be a bug but I can't reproduce it.
Do you try to color results of simple select (like "select * from table") or something sophisticated with joins/functions?
Some SQL snippet would be very helpful.

**Comment by serge-rider** [comment] 2016-05-03 16:06
Could you try it in the recent version (3.6.6)?

**Comment by serge-rider** [comment] 2016-05-13 10:31
Will close this for now.
If anybody can reproduce that - please post new error details and I'll reopen it.

**Closed by serge-rider** 2016-05-13 10:31 UTC
Labels: bug, can't reproduce
