### ISSUE TITLE
Delete and others keys stopped working on SQL Editor

### ISSUE THREAD

**Issue by tiagohipolito** [serge-rider/dbeaver#370] opened 2016-04-14 22:35 UTC
Some keys like delete button stop working on SQL Editor after generating sql.

I'm having this problem for a while. It occurs still on version 3.6.5

Here is how to reproduce this :
1 - Open SQL Editor for any connection
2 - Execute any query
3 - On the result grid, right click on result line number and go to Generate SQL > Insert
4 - On the generated insert statement, select its text and hit delete button

It executes this delete on the grid. 

Although the focus is on the text part of SQL Editor some actions happens on the result grid. 

After that I can't use buttons delete, insert, ctrl + x, ctrl + c, ctrl + v, ctrl + z, etc.

To make things work again I have to restart SQL Editor

**Comment by serge-rider** [comment] 2016-04-15 10:47
Can't reproduce.
What is your OS/environment?

**Comment by tiagohipolito** [comment] 2016-04-15 14:11
$ cat /etc/linuxmint/info
RELEASE=17.1
CODENAME=rebecca
EDITION="MATE 64-bit"
DESCRIPTION="Linux Mint 17.1 Rebecca"
DESKTOP=MATE
TOOLKIT=GTK
NEW_FEATURES_URL=http://www.linuxmint.com/rel_rebecca_mate_whatsnew.php
RELEASE_NOTES_URL=http://www.linuxmint.com/rel_rebecca_mate.php
USER_GUIDE_URL=help:linuxmint
GRUB_TITLE=Linux Mint 17.1 MATE 64-bit

**Comment by tiagohipolito** [comment] 2016-04-15 20:31
Tried to reproduce it on a machine with WinXP 32bits with the latest version o DBeaver and it didn't happen there too.

**Comment by syci** [comment] 2016-05-26 18:02
Hello, I have problems with the " ALT Gr " key when I load the program stops working throughout the system .

This is my setup :

Windows 10 Home x64
JDK x64 and 32

**Comment by serge-rider** [comment] 2016-10-13 10:34
Problem with SQL editor commands (after context switch) was fixed in 3.7.5.
Closing (if you still can reproduce this - please reopen/comment).

**Closed by serge-rider** 2016-10-13 10:34 UTC
Labels: bug
